### ISSUE TITLE
What should the property descriptor for @@unscopeable look like?

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#102]
Should it be enumerable?  Writable?  Configurable?

The spec currently just says:

>  then there MUST be a property on the interface prototype object whose name is the @@unscopeables symbol and whose value is an object created as follows

with nothing about the other parts of the property descriptor.  I'm assuming this thing should be writable, configurable, and enumerable.

**Comment by domenic** [comment]
ES objects have writable: false, enumerable: false, configurable: true for this. I.e. the "you really shouldn't mess with this, but we won't prohibit you" propdesc.

**Comment by domenic** [comment]
And by ES objects I guess I just mean `Array.prototype`.

**Comment by bzbarsky** [comment]
Matching Array.prototype seems worthwhile.

**Comment by bzbarsky** [comment]
OK, what I'm going to implement in Firefox matches Array.prototype.
