### ISSUE TITLE
Should we match the ES spelling of "unscopable"

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#103]
ES has `Symbol.unscopable".  IDL has `[Unscopeable]` (with the 'e').

Note that this will require changes to DOM and the like...

**Comment by annevk** [comment]
Happy to update DOM.

**Comment by bzbarsky** [comment]
OK.  I don't think anything other than DOM will need changes here.

**Comment by annevk** [comment]
Updated DOM as well.
