### ISSUE TITLE
Should specify that all JS functions created by IDL are "built-in functions"

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#106]
That is, they should follow the rules in https://tc39.github.io/ecma262/#sec-built-in-function-objects. Notably:

- No .prototype property
- No [[Construct]] unless otherwise specified
- No arguments or caller properties

According to https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/, Chrome and Edge violate the arguments and caller prohibition. Not sure about the rest.

/cc @ajklein

Filed https://bugs.chromium.org/p/chromium/issues/detail?id=601272 on Chrome

**Comment by bzbarsky** [comment]
> No [[Construct]] unless otherwise specified

That's not what built-in function objects seem to do in the spec.  And I don't see why we would want it.  Having the default spec [[Construct]] which is equivalent to [[Call]] except for setting newTarget and not initializing this seems correct; we'd just need to make all IDL stuff except interface objects throw when this is not initialized or something.

**Comment by domenic** [comment]
> Built-in function objects that are not identified as constructors do not implement the [[Construct]] internal method unless otherwise specified in the description of a particular function. 

This is tested in various test262 tests for e.g. the various functions created for during promises. It's observable by using a proxy.

Interfaces could have a throwing [[Construct]], but methods should have no [[Construct]] at all.

**Comment by bzbarsky** [comment]
Ah, I see.  OK, that seems fine.
