### ISSUE TITLE
MapClass should not put Map.prototype in the prototype chain

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#11]
[MapClass] should not put Map.prototype in the prototype chain, since all the Map.prototype methods will throw on such objects (since they don't create objects with [[MapData]]). Even if [[MapData]] was added, the algorithms specified for [MapClass] methods don't use [[MapData]].

[MapClass] should be a macro for adding a few default methods that let the class in question quack like a map, and not some kind of weird way of creating an object that shadows all the Map methods with versions of them that have different, incompatible semantics.

**Comment by heycam** [comment]
Removing Map.prototype from the prototype chain was done as part of the [MapClass] -> maplike change.
