### ISSUE TITLE
FrozenArray<dictionary>?

### ISSUE THREAD

**Issue by jyasskin** [heycam/webidl#115]
[`FrozenArray`](http://heycam.github.io/webidl/#idl-frozen-array) doesn't specify any restrictions on its element type, but if it contains a sequence of dictionaries, those dictionaries might be modifiable. It'd be nice to be able to specify that the contents of the `FrozenArray` are recursively frozen.

**Comment by domenic** [comment]
Let's dupe this against https://www.w3.org/Bugs/Public/show_bug.cgi?id=29004 which has much more discussion.
