### ISSUE TITLE
Conversion for (SomeDictionary or sequence<T>) seems incorrect

### ISSUE THREAD

**Issue by bashi** [heycam/webidl#123]
A dictionary and a sequence<T> are [distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable) so `(SomeDictionary or sequence<DOMString>)` should be a valid union type when `SomeDictionary` is a dictionary. When an implementation follows [the conversion algorithm](https://heycam.github.io/webidl/#es-union) to convert an ECMAScript array to the union type, step 11 will be executed and the conversion would result in `SomeDictionary`. I think this is incorrect. Instead, step 12 should be executed so that the array is converted to `sequence<DOMString>`.

We encounter this bug while implementing WebRTC in Blink. [Here](https://codereview.chromium.org/1977513004/) is the specific change.

**Comment by annevk** [comment]
Why does WebRTC have dictionary or sequence though? That seems like a pretty bad pattern.

**Comment by annevk** [comment]
Or has that already shipped in multiple browsers and now we need to cleanup their mess?

**Comment by alvestrand** [comment]
This is part of the constrainable pattern, where people wanted to specify a single value (a="foo"), a set of alternative values (a=["foo", "bar"]), or a complex set of restrictions on values (a={exact: ["foo", "bar"]}), all with the fewest number of brackets.

This part of the spec hasn't changed for years, and I suspect that Firefox and Edge implement it - Chrome's been the laggard because it's been waiting for the support for unions to improve in general.
Tagging @jan-ivar and @aboba to reply on whether they implemented this.

**Comment by alvestrand** [comment]
In general: If the spec allows it, it has to specify sensible handling of it. Parsing ["a", "b"] as equivalent to {} will surprise users, and surprising the users is bad.

The alternative is to outlaw the construct.

**Comment by annevk** [comment]
I thought sequence or dictionary was outlawed since generally you cannot really distinguish an object from something that's iterable. E.g., `{ 0: ..., 1: ..., length:2 }` is that a dictionary or a sequence?

**Comment by alvestrand** [comment]
The table in the "overloading" section says they're distinguishable.

http://heycam.github.io/webidl/#dfn-distinguishable

Neither can be distinguished from {object}, but they're (claimed to be) distinguishable from each other.

**Comment by bzbarsky** [comment]
This is definitely an IDL spec bug.  Compare https://heycam.github.io/webidl/#es-overloads which checks for sequences in step 13 and dictionaries in step 14.  That is the intended behavior of this stuff, union handling is supposed to match overload resolution in terms of its behavior, and yes we purposefully added a way to distinguish dictionaries from sequences; see .https://github.com/heycam/webidl/pull/19/

I tried looking up the blame to see when the discrepancy crept in, but there are too many unrelated changes and identical-looking diffs involved to figure it out.  Anyway, we should just fix this.

**Comment by bzbarsky** [comment]
Oh, and I just checked Gecko's union implementation, and it checks for iterable before doing the dictionary stuff when both are present in the union.  So we're doing what the spec meant to say...
