### ISSUE TITLE
"Restricted" Float32Array

### ISSUE THREAD

**Issue by padenot** [heycam/webidl#126]
In <https://github.com/WebAudio/web-audio-api/issues/815#issuecomment-220375880>, we need the concept of a `Float32Array` that does not contain `{+,-}Infinity` or `NaN`, and throw when this is the case.

For now we're doing it manually. Asking around, this is currently not supported, is this something we'd be interested in?

**Comment by domenic** [comment]
Is the idea to create a type such that whenever you try to convert a JS Float32Array to it, it loops through all values and checks them to make sure they're not in the "bad" set?

Or is it to create an entirely new JS typed array type?

**Comment by padenot** [comment]
The former.

**Comment by bzbarsky** [comment]
I don't quite understand the intent here, actually, and would like to understand better.

Are we copying the input Float32Array or using it by reference?  If we're copying, then it seems like you could just use a `sequence<float>` (albeit at some performance cost, in case it matters).  If you're using it by reference, non-finite things can be placed in it after you return, right?

So are we just talking about situations in which the value is used by copy (or not used after the call returns) but the overhead of the ES iteration protocol is too high for the use case, right?

**Comment by padenot** [comment]
This issue was created in particular for [AudioParam.setValueCurve](http://webaudio.github.io/web-audio-api/#widl-AudioParam-setValueCurveAtTime-AudioParam-Float32Array-values-double-startTime-double-duration), that does a copy. This function is not very hot, it's just setting an array once, making a copy so it's used internally by another thread.

Because of the fact that the Web Audio API uses multiple threads, buffers that are passed in are usually detached or copied.

**Comment by bzbarsky** [comment]
Seems like setValueCurve could just use a `sequence<float>` argument then, and not overconstrain callers in terms of how they provide the floats (typed array, array, whatever)...

**Comment by tobie** [comment]
Closing as this issues seems resolved.
