### ISSUE TITLE
Should probably spec a hasInstance for named constructors

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#134]
`(new Image) instanceof Image` is true in Firefox, Edge, Safari, Chrome.

//cc @domenic, @annevk, @travisleithead, @esprehn

**Comment by domenic** [comment]
Is a special hasInstance behavior necessary? I thought this just followed from `Image.prototype === HTMLImageElement.prototype`.

**Comment by bzbarsky** [comment]
Oh, hmm.   That's a good point.  This might just work.
