### ISSUE TITLE
More meaniful labels

### ISSUE THREAD

**Issue by marcoscaceres** [heycam/webidl#136]
The emoji labels are cute (who doesn't love "☕☕☕") , but don't really help us who don't really know what those mean... I'm just going to assume ☕ means Java because @heycam wants to bring back Java Bindings for WebIDL 🙉

**Comment by tobie** [comment]
☕—not to hard
☕☕—hard
☕☕☕—excruciating

⌛—should be short to fix
⌛⌛—shouldn't be too long
⌛⌛⌛—there goes your week-end

Thus, good first bugs are [short and sweet](https://github.com/heycam/webidl/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%E2%8C%9B%20%20label%3A%E2%98%95).
