### ISSUE TITLE
Overload resolution algorithm: Steps 11.5. and 11.6. are identical

### ISSUE THREAD

**Issue by cdumez** [heycam/webidl#138]
Overload resolution algorithm:
http://heycam.github.io/webidl/#es-overloads

Steps 11.5. and 11.6. are identical:

> 5. Otherwise: if V is a RegExp object and there is an entry in S that has one of the following types at position i of its type list,
> RegExp
> object
> a nullable version of either of the above types
> a union type or nullable union type that has one of the above types in its flattened member types
> then remove from S all other entries.
> 6. Otherwise: if V is a RegExp object and there is an entry in S that has one of the following types at position i of its type list,
> RegExp
> object
> a nullable version of either of the above types
> a union type or nullable union type that has one of the above types in its flattened member types
> then remove from S all other entries.

**Comment by bzbarsky** [comment]
Good catch.  Looks like a copy/paste error in https://github.com/heycam/webidl/commit/50e172ec079db073c3724c9beac1b576fb5dbc47
