### ISSUE TITLE
Step 5.8 of effective overload set construction is a no-op?

### ISSUE THREAD

**Issue by cdumez** [heycam/webidl#139]
While implementing the overload set construction, following:
- http://heycam.github.io/webidl/#dfn-effective-overload-set

I noticed that Step 5.8 is either a no-op after step 5.7 (or there is something I don't understand / missed):

Step 5.8 is:
> If n > 0 and all arguments of X are optional, then add to S the tuple <X, (), ()> (where “()” represents the empty list).

However, I would have thought that step 5.7 would have already taken care of this:

> Initialize i to n−1.
> While i ≥ 0:
> - If argument i of X is not optional, then break this loop.
> - Otherwise, add to S the tuple &lt;X, t_0..i−1, o_0..i−1&gt;.
> - Set i to i−1.

**Comment by bzbarsky** [comment]
Yeah, I guess this depends on what the subscript `0...-1` means.  It looks like steps 5.2 and 5.3 assume it means "empty list", which would indeed make step 5.8 redundant.

@heycam, do you know what's up here?

**Comment by heycam** [comment]
I don't think I explain the notation in the spec (sorry), but the subscripts are meant to be inclusive of endpoints, and yes you can infer that from how they're used in steps 5.2 and 5.3.  So that does mean step 5.7 will have already added a no-arg tuple to the set.

**Comment by cdumez** [comment]
So can we simplify and leave out step 5.8 from the specification?
