### ISSUE TITLE
Have single number type and allow custom ranges

### ISSUE THREAD

**Issue by marcoscaceres** [heycam/webidl#14]
It would be great if WebIDL simply defined a single ES number type and allowed custom ranges. This would greatly simplify the spec by doing away with all the silly types: byte, short, etc. while remaining backwards compatible. 

So, something like:
```
typedef Number[−128..127] Byte;
```

And would allow for new types: 

```
typedef Number[0..360] Angle;
```

**Comment by tobie** [comment]
Closing as dup of #33. Feel free to reopen if you disagree.
