### ISSUE TITLE
is Step 5.5.1. of effective overload set construction really needed?

### ISSUE THREAD

**Issue by cdumez** [heycam/webidl#140]
is Step 5.5.1. of effective overload set construction really needed?

This step is:
> Add to S the tuple &lt;X, t_0..n−2, o_0..n−2&gt;.
> Note: This leaves off the final, variadic argument.

The reason I believe it may not be needed is because I think the loop at step 5.7 will already take care of adding the version without the final variadic argument AFAICT:
> While i ≥ 0:
> - If argument i of X is not optional, then break this loop.
> - Otherwise, add to S the tuple &lt;X, t_0..i−1, o_0..i−1&gt;.
> - Set i to i−1.

'optional' in step 5.7 points to:
[](http://heycam.github.io/webidl/#dfn-optional-argument)

which says that the final variadic parameter is considered to be optional.

**Comment by bzbarsky** [comment]
@heycam?

**Comment by heycam** [comment]
Yes, I believe you are right.

**Comment by cdumez** [comment]
Thanks for fixing!
