### ISSUE TITLE
Defining a ByteString default value using a string literal gives no clear link to the explanation of how the string is converted to ByteString

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#141]
A string literal can contain an arbitrary sequence of Unicode characters.  What's supposed to happen when a ByteString default value is a string literal, exactly?  That is, how is the conversion from a sequence of Unicode characters to bytes performed?

**Comment by bzbarsky** [comment]
Ah, I guess this is covered by http://heycam.github.io/webidl/#string-literal sort of.  It would be nice to link to those rules from the place that says a string literal can be used as the default value....

**Comment by bzbarsky** [comment]
Fixing summary too.

**Comment by domenic** [comment]
This should probably be fixed alongside https://github.com/heycam/webidl/issues/141

**Comment by annevk** [comment]
Did you mean to link #236?
