### ISSUE TITLE
Provide a concise syntax to create IDL dictionaries from prose

### ISSUE THREAD

**Issue by jyasskin** [heycam/webidl#142]
Web Bluetooth would like to create an instance of [BluetoothPermissionDescriptor](https://webbluetoothcg.github.io/web-bluetooth/#dictdef-bluetoothpermissiondescriptor) which is as if initialized from the `{
  name: "bluetooth",
  filters: var-from-prose,
  optionalServices: other-var-from-prose
}` ECMAScript object by the procedure in http://heycam.github.io/webidl/#es-dictionary. It'd be nice not to have to spell out the full initialization inline, but @annevk objected to just writing it as an ES object in https://github.com/whatwg/storage/pull/36#discussion_r71840330.

What do you folks recommend?

**Comment by bzbarsky** [comment]
The main problem with writing things as an ES object and assuming implicit application of http://heycam.github.io/webidl/#es-dictionary is that it causes ambiguity in terms of what the actual behavior is, no?  Specifically, consider the case at hand.  The IDL is:

    dictionary PermissionDescriptor {
      required PermissionName name;
    };
    dictionary BluetoothPermissionDescriptor : PermissionDescriptor {
      DOMString deviceId;
      sequence<BluetoothRequestDeviceFilter> filters;
      sequence<BluetoothServiceUUID> optionalServices = [];
    };

Say you were to initialize this dictionary with the ES object literal `{ name: "bluetooth", deviceId: "", filters: []; optionalServices: [] }` using the rules of <http://heycam.github.io/webidl/#es-dictionary>.  What would the resulting IDL dictionary contain in its `filters` member?  The answer is that it depends on whether `Array.prototype[Symbol.iterator]` or `%ArrayIteratorPrototype%.next` was overridden and what it was overridden to do.  There are other cases like this as well.

That is, initialization with an object literal is NOT, in general, the same as direct setting of the dictionary members to the values you want.  This is really unfortunate, but just part of life with ECMAScript.  I assume in your case you want the "direct setting" operation, not the "initialization with an object literal" operation...

We could try to add some syntax for indicating the "direct setting" operation.  I'm torn on whether it should look enough different from ES literals to at least make people stop and realize there is an issue here.  That is, that the thing we set "filters" to is NOT an ES Array but some other type entirely.

**Comment by jyasskin** [comment]
Mhmm, in the case at hand, I happen not to write out any literal arrays, but if I had, I wouldn't intend the page's `%ArrayIteratorPrototype%.next` to be used to create the `sequence<>` object. In most cases, I'd intend only the initial values of the various ES objects to be used, but there are probably some cases where I'd want member access on a user-provided object to use the user's overrides.

I don't really care what syntax we use for WebIDL literals, as long as it's nearly as concise as the ES syntax.

**Comment by Ms2ger** [comment]
Since 26aa8308, the spec has:

> An ordered map with string keys can be implicitly treated as a dictionary value of a specific dictionary D if all of its entries correspond to dictionary members, in the correct order and with the correct types, and with appropriate entries for any required dictionary members.

which means you can use the following syntax from [Infra](https://infra.spec.whatwg.org/#ordered-map):

> «[ "name" → "bluetooth", "filters" → _var-from-prose_, "optionalServices" → _other-var-from-prose_ ]».

I think that's short enough that we don't need another syntax.

**Comment by jyasskin** [comment]
That works for me. Do you think it'd be worth adding an example of using this notation?
