### ISSUE TITLE
Bikeshed Conversion

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#147]
Hi all,

I'm nearly finished converting the WebIDL spec to Bikeshed.

You can checkout the [current output][spec] as well as the [generated Bikeshed source file][src].

I'm seeking wider-review now before doing the last manual edits and submitting a PR to the main repository.

Conversion pipeline
----------

The conversion is fully automatic.

The [original XML source file][1] is transformed into a tmp file using an [XSLT stylesheet][2] (which is just a modified version of the origin XSLT stylesheet already used to transform the src file into HTML).

It is then turned into the final Bikeshed file by running through [a series of line-by-line JS parsers][3].

This has us 99% covered. The final 1% fixes will be done manually, after this initial review, but as part of the pull request.

The whole conversion pipeline will be discarded after the fact (but retrievable through Git).

Testing
-------

Manual conversion of specs are highly error prone. The pipeline described above avoids a number of issues normally caused by manual transforms, but still needs tests. Especially to ensure that:

### 1) All anchors exposed by the original spec are preserved.

This uses [a small JS script][4].

They are all preserved with the exception of:

* anchors prefixed with `ref-`: those are biblio links.
* anchors prefixed with `proddef-`: those are internal links to the grammar snippets. The `prod-` prefixes have been preserved, however.
* `#appendices`
* `#informative-references`
* `#normative-references`
* `#sections`

This seems good enough.

### 2) The markdownified version of the spec renders the same HTML as the non-markdownified one.

This is achieved by building both versions of the spec. Munging their output [using a dedicated script][5] and diff'ing them.

The results are, here also, good enough. (There are a few negligible difference that do not affect the normative content of the spec.) 

Running the conversion build
----------------------------

Running the conversion is rather painful. You need to manually edit some Bikeshed data files (remove the last line of `/spec-data/link-defaults.infotree`), install a Java XSLT processor (for real), node.js, etc.

If you did all of the above, all you need to do is run:

```
$ make 
```
Of course, as soon as we merge this into the main repo (and @tabatkins and I modify the Bikeshed data file accordingly), the only thing you'll need to do to build the spec is to run Bikeshed.

Outstanding todos and issues
----------------------------

I'm tracking a bunch of issues on [my GitHub fork][6]. Please report things I missed there.

Note the grammar snippets rely on a small JS script for styling and linking until a BNF parser is built into Bikeshed.

Next steps
---------

Planning to collect your comments over the next few days, deal with the remaining issues next week, and hopefully send a pull request by the end of the week.

Looking forward to your feedback and comments.

Best,

--tobie

P.S.: tagging a bunch of you: @heycam @bzbarsky @domenic @tabatkins @annevk @ylafon. Apologies in advance for those I forgot.

[spec]: https://rawgit.com/tobie/webidl/bikeshed/index.html
[src]: https://github.com/tobie/webidl/blob/bikeshed/index.bs
[1]: https://github.com/tobie/webidl/blob/bikeshed/index.xml
[2]: https://github.com/tobie/webidl/blob/bikeshed/WebIDL-bs.xsl
[3]: https://github.com/tobie/webidl/tree/bikeshed/post-process
[4]: https://github.com/tobie/webidl/blob/bikeshed/check-anchors.js
[5]: https://github.com/tobie/webidl/blob/bikeshed/check-structure.js
[6]: https://github.com/tobie/webidl/issues

**Comment by heycam** [comment]
Great work, @tobie!  I will review and file issues.

**Comment by marcoscaceres** [comment]
Once the conversion is done we are ditching the XML version, right?

**Comment by heycam** [comment]
I should hope so. :-)

**Comment by heycam** [comment]
And can I just say that the IDL grammar snippets looks really nice!  I like that they match the ES spec syntax / styling.

**Comment by tobie** [comment]
> And can I just say that the IDL grammar snippets looks really nice! I like that they match the ES spec syntax / styling.

Yeah, that was @domenic's suggestion. I agree, it looks really nice.

**Comment by bzbarsky** [comment]
This all sounds great, but is there any way to preserve the git history/blame in a sane way in the process?  I'm not seeing how, at the moment, but just checking...

**Comment by domenic** [comment]
You mean the history of @tobie's fork, or of the existing repo? The latter you get for free; the former would require doing a merge commit I guess.

**Comment by bzbarsky** [comment]
I mean being able to usefully get blame on a line of the file.  You don't get it for free, because the blame will largely be the "conversion to bikeshed" and finding the actual blame for a line will be a bit of a PITA that involves walking past that commit, _and_ to a different line in a different file somehow (because the current canonical blame is the .xml file, not the .html one; the latter is not even updated in all cases when the former is, though all instances of that are of course mistakes).

Maybe we could do one commit which does the equivalent of `mv index.xml index.html` followed by another commit that then modifies the .html to be the new thing or something... that might make blame a little easier to follow, or it might make it harder.  Hard to tell.

**Comment by bzbarsky** [comment]
@tobie  Should I avoid changing the .xml file until you finish this?

**Comment by tobie** [comment]
@bzbarsky no it's fine, you can go ahead.

**Comment by tobie** [comment]
Re preserving git blame/history: I'm glad you brought that up as I hadn't really thought about it. I'll try a couple of options to see what can be done. I think your "git mv + conversion" strategy is the best one, but I don't know much about how Git's x-file content tracking is implemented. My concern is that the changes are so big (iirc the converted file contains less than half the characters of the original file) that, despite having preserved line breaks, it's going to be super hard for Git to track the content. I guess there's only one way to find out. :)

**Comment by marcoscaceres** [comment]
Looking at the [contributor history](https://github.com/heycam/webidl/graphs/contributors), the number of commits by anyone other than @heycam has been fairly tiny. Seems like there would be limited value in retaining such history. 

At least, tagging the version before this big change lands would easily allow anyone that needs to see who changed a particular line to access that history.

**Comment by bzbarsky** [comment]
The point of history isn't to see who made the change, but to see why the change was made (the relevant issues, etc).  It doen't matter how many commits were made by which contributor...

**Comment by annevk** [comment]
@marcoscaceres there's enormous value in retaining history. E.g., for DOM and HTML it's a pretty regular occurrence to go through the history and find out rationale and past decision making. For something as complex as IDL we absolutely need that too and ideally all standards projects tried to keep good history, detailed commits comments, etc.

**Comment by marcoscaceres** [comment]
I guess I'm just used to using gh's issue interface for looking up changes, etc. But yes, I understand the value.

**Comment by annevk** [comment]
Something not mentioned in OP but seems to be true: data-export, data-dfn-for, and data-lt are preserved.

**Comment by tobie** [comment]
@annevk yes, I think I should mostly have gotten those right. Are they relied upon by the Shepherd parser?

**Comment by annevk** [comment]
Yeah, they are in active use as far as I can tell.

**Comment by tobie** [comment]
I was under the assumption that they were only used by bikeshed internally, so preserved most (and added some) in order to get the desired Bikeshed output. Hadn't thought about them being used externally.

I could write a quick script to compare things here too.

**Comment by tobie** [comment]
Alright, this is mostly ready to merge now minus a few manual edits that are still needed.

please abstain from adding changes to index.xml at this point as merging will be pretty much impossible.
