### ISSUE TITLE
Remove the RegExp type

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#148]
This has no consumers on the platform, at least in Chromium: https://cs.chromium.org/search/?q=RegExp+file:%5C.idl&sq=package:chromium&type=cs

Like the now-dead Date type, if someone actually wanted to use this, they should use `object` plus some prose. But probably nobody should use this.

/cc @nox

**Comment by bzbarsky** [comment]
Fwiw, I agree.  I'm not really sure why we ever added this type, apart from it clearly mapping to one of the "weird" objects in JS; we have not found any use cases for it, and Gecko has no support for it and no uses or prospective uses I'm aware of.

**Comment by cdumez** [comment]
We also have no user or support for RegExp in WebKit bindings.

**Comment by bzbarsky** [comment]
Fwiw, there were web platform tests testing the old spec verbiage.  I'll update them in https://bugzilla.mozilla.org/show_bug.cgi?id=1315135
