### ISSUE TITLE
"get a copy of the bytes held by the buffer source" should not fail for detached buffers

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#151]
Currently it seems that IDL throws for detached buffers. However, as far as I can tell implementations do not follow this and simply end up with the empty byte sequence whenever they encounter a detached buffer.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4414 is my demo for this (note the lack of exceptions/rejections).

(Note that there's also still an ask to clean up this aspect of IDL and make it much easier to work with: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28798 .)

**Comment by bzbarsky** [comment]
Note that I think this may be a more general issue, in that the ES spec requires throwing in many cases when operating on detached stuff, but in practice UAs don't do that...  Worth checking with @jswalden at least; I recall him doing some work on that stuff.

**Comment by annevk** [comment]
Yeah, I raised that two years ago when I last did research into this: https://esdiscuss.org/topic/arraybuffer-neutering. @bterlson is TC39 still hoping implementers will throw more for ArrayBuffer and friends? When are we going to throw in the towel?

**Comment by annevk** [comment]
In any event, IDL doesn't have to follow suit and can just return the empty byte sequence if IsDetached returns true solving at least part of the problem.

**Comment by bterlson** [comment]
I think we hope everyone will align and throw more often, but I admit that I haven't looked into this area for at least a year so things may have changed. There should be test262 collateral for all this (right, @tcare / @leobalter / @jugglinmike?) so I think it's just a matter of priorities. Hopefully the web doesn't depend on non-throwing behavior? (Seems likely given that detached buffers aren't very common, I suppose)

**Comment by littledan** [comment]
test262 does include tests for this (thanks @leobalter) but I'm still concerned about web compatibility. I haven't figured out how to instrument TypedArrays to measure whether detached TypedArrays are ever accessed without decreasing TypedArray performance (we set the length to 0 and bounds checks handle accesses, so we don't need a separate detached check), so I'm not sure how to get the information from telemetry. Does anyone else have an idea for how to get solid data on this question?
