### ISSUE TITLE
[Exposed] doesn't seem to work well with partial interfaces

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#154]
Previously at https://github.com/heycam/webidl/pull/121#discussion_r76247465 and https://github.com/heycam/webidl/pull/121#discussion_r76250672

The spec currently says

> "Any extended attribute specified on a partial interface definition is considered to appear on the interface itself"

Which does not seem to work well with [Exposed] (and possibly not well with [SecureContext] either). Probably that statement needs to be modified, but we also need to think about why it's there in the first place and for what extended attributes it does make sense

We are also missing a potential restriction which seems important, namely "If [Exposed] appears on a partial interface, then the partial interface's exposure set MUST be a subset of the interface's exposure set."

In general it's not clear what putting different [Exposed] values on an interface vs. a partial interface might mean, or on members of an interface or members of a partial interface.

**Comment by bzbarsky** [comment]
Now that you mention the "why it's there" bit, I _think_ that statement was added so you could add a [Constructor] via a partial interface and have it work in the "sane" way: by adding a constructor or constructor overload to the main interface.

**Comment by domenic** [comment]
@tobie this may be fixed with your recent overhaul; can you check?
