### ISSUE TITLE
Contributing to webidl just got a lot harder

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#171]
STEPS TO REPRODUCE:
1. git clone webidl
2. Edit index.bs
3. Type `make`

EXPECTED RESULTS: index.html is updated

ACTUAL RESULTS: "make: bikeshed: No such file or directory"

There is no indication in the error message how to resolve this.  There is no documentation in the .md file for how to resolve this.  

If there is now a dependency on some other utility to regenerate the spec text, that needs to be clearly documented, or better yet the other thing should be pulled in as a submodule so things just work.

// cc @tobie

**Comment by tobie** [comment]
To alleviate your immediate concern: https://github.com/tabatkins/bikeshed/blob/master/docs/install.md

**Comment by bzbarsky** [comment]
Yes, I did find that.  Those instructions don't actually work for me, fwiw.

**Comment by bzbarsky** [comment]
That's ignoring the "let's globally install untrusted code as root" issue, of course, which doesn't make me happy either.  But even given that, it doesn't actually end up putting anything named "bikeshed" in my path.  And the actual bikeshed.py doesn't use the python it says to install html5lib for, so can't find it.

I've managed to run it locally by explicitly invoking the right python version on bikeshed.py and reading the makefile to figure out what arguments to pass to it.  Which is fine as far as I''m concerned, but is a _way_ higher contribution bar than we used to have.

**Comment by tobie** [comment]
@tabatkins think you can help with some of this?

**Comment by tobie** [comment]
Would defaulting to curl'ing the API if bikeshed can't be found help here?

**Comment by bzbarsky** [comment]
> Would defaulting to curl'ing the API if bikeshed can't be found help here?

In the "just make it work" sense yes.  Should probably spit out a warning about how it won't work offline and link to instructions for how to make it work there...

**Comment by bzbarsky** [comment]
OK, so I've gotten bikeshed to run locally...  When I pull webidl master as of right now (rev a3a6aa2) and run bikeshed, index.html gets changed in various ways from what's checked into the tree.  Some references get reordered, a whole bunch of empty `<span></span>` gets inserted.  Is that expected?

**Comment by bzbarsky** [comment]
> OK, so I've gotten bikeshed to run locally...

To be clear, that's via `python-2.7 /path/to/bikeshed/clone/bikeshed.py spec index.bs`.  I did run `python2.7 /path/to/bikeshed/clone/bikeshed.py update` but either there are no updates available or it's going to dev/null; I see no changes to `/path/to/bikeshed/clone/bikeshed/spec-data/`.

**Comment by tobie** [comment]
I just updated Bikeshed and I'm getting the biblio reordering you mentioned but not the empty `<span>`s.

**Comment by domenic** [comment]
Yeah, I've found this to be problematic in the past... curling is often the sure-fire way to get things done, and I'd suggest adding that to the makefile and/or readme.

The empty spans, I think, come from an outdated syntax highlighter dependency? My guess is Bikeshed doesn't have whatever metadata is in place to tell Python the correct syntax highlighter version. We've run into that several times now where different people all have the same supposedly-up-to-date versions of Bikeshed, but some get empty spans and some don't.

**Comment by tobie** [comment]
The other option, of course, would be to work off of the master branch and have a bot that builds the spec and just pushes the html output to gh-pages on commit to master.

**Comment by domenic** [comment]
Yeah, I might be able to set that up. That could also get us the commit snapshots thing that @bzbarsky is a fan of.

**Comment by tobie** [comment]
Also getting the crazy empty spans from curling the API. o_O Will file a bug against Bikeshed later.

**Comment by bzbarsky** [comment]
OK, so in the near term I was going to make some changes to IDL.  Should I manually edit out the empty spans?   Are we OK with the biblio reordering?

**Comment by domenic** [comment]
Biblio reordering should be fine, and I believe the empty spans are harmless.

**Comment by tobie** [comment]
Working on the makefile as we speak.

**Comment by bzbarsky** [comment]
> and I believe the empty spans are harmless.

Well, they're ugly and confusing and I have no guarantee they won't multiply.... ;)

**Comment by tobie** [comment]
"spanitis"

**Comment by annevk** [comment]
The empty spans are some configuration issue I believe. Not entirely sure how to get it fixed though. Seems to be a problem for a number of folks. :-/

**Comment by tabatkins** [comment]
> The empty spans, I think, come from an outdated syntax highlighter dependency? My guess is Bikeshed doesn't have whatever metadata is in place to tell Python the correct syntax highlighter version. We've run into that several times now where different people all have the same supposedly-up-to-date versions of Bikeshed, but some get empty spans and some don't.

I have no idea what these empty spans are and haven't heard of them before. What's up with it?

> Biblio reordering should be fine

Hmm, didn't realize they were reordering. I'll switch to sorting these so they don't reorder.

@bzbarsky Would love some more detail on what parts of the install instructions didn't work for you - they're correct to the best of my knowledge, and have been updated by people running into problems over time.

> That's ignoring the "let's globally install untrusted code as root" issue, of course, which doesn't make me happy either.

Yeah. :/  Several people have complained about wanting me to use one of the virtualization options out there, but I have no familiarity with them whatsoever, and nobody wants to put in sufficient effort to document it for me. Current instructions just install things "the normal way" that you see in the wild, which is unsafe but eh.

> But even given that, it doesn't actually end up putting anything named "bikeshed" in my path. 

That's very strange, as the `pip install` should have done so. No one else has ever reported such a problem; they all get it in their path immediately.

> And the actual bikeshed.py doesn't use the python it says to install html5lib for, so can't find it.

...what?

> I've managed to run it locally by explicitly invoking the right python version on bikeshed.py and reading the makefile to figure out what arguments to pass to it. Which is fine as far as I''m concerned, but is a way higher contribution bar than we used to have.

As currently written, at least, using the makefile at all doesn't do anything - you can just run `bikeshed` (with no arguments) in the folder and it'll figure out what to do.  Some people seem to rely like using that workflow, tho. Shrug.

**Comment by annevk** [comment]
Potential `<span>` noise cause: https://github.com/whatwg/dom/pull/313#issuecomment-242428180.

**Comment by tabatkins** [comment]
Cool. I've got an (up-to-date) Pygments version of 2.1.3.  bz, what's yours? (`pip show pygments` to find out).

If it's different, I wonder how bz even *got* it, given that he apparently recently installed.

**Comment by tabatkins** [comment]
Okay, no clue why some versions of Pygments (including the most up-to-date) spit out an empty span at the beginning of their highlighting. It doesn't even have a highlight class. Anyway, manually removed now.

**Comment by bzbarsky** [comment]
> Would love some more detail on what parts of the install instructions didn't work for you 

1. The instructions say to run `sudo pip install`.  There is no thing named `pip` on my machine.  Given the rest of the instructions, I assumed I should `sudo pip-2.7 install`.
2.  Running `sudo pip-2.7 install --editable /path/to/bikeshed` runs and ends with "Successfully installed Bikeshed-0.0.0".  But there is nothing named "bikeshed" anywhere in my $PATH as far as I can tell, so running `bikeshed update`, or indeed `bikeshed` to generate the spec HTML doesn't work.

Where is the "bikeshed" thing that should be in my $PATH expected to live?

> ...what?

That part was my fault for not having run `port select`, looks like.  After I run that, the right version of python ends up in my PATH at least.  Note that I'm pretty sure I didn't have it set up that way because other things broke with that...  We'll see if I run into them again.

> bz, what's yours? (pip show pygments to find out).

2.1.3 according according to `pip-2.7 show pygments`.

**Comment by domenic** [comment]
I think this can be closed. @tobie's fixes in #173 make this as simple as just using `make` locally. Happy to reopen if people disagree.
