### ISSUE TITLE
Namespace is a misnomer, should we fix it?

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#177]

**Comment by bzbarsky** [comment]
So what would you call it?  Or rather, what makes it a misnomer?

**Comment by tobie** [comment]
My understanding from a quick chat with @domenic is that `namespace` is essentially a "bag of functions". I'm concerned that people will mix it up with a more "traditional" idea of namespacing (notably being able to avoid exposing constructors and interfaces globally).

**Comment by annevk** [comment]
Bikeshed: "function group"

**Comment by tobie** [comment]
Well, granted we'll end-up adding attributes and the like, this will eventually be on feature-parity with interfaces minus the this-bounding, no? Why not call it `unbound_interface` in that case, or add the unbound keyword so you have `unbound interface { ... };`?

**Comment by Ms2ger** [comment]
Let's say this ship has sailed.
