### ISSUE TITLE
Should promise-returning attributes reject in case of wrong this value?

### ISSUE THREAD

**Issue by youennf** [heycam/webidl#186]
When a promise-returning attribute getter is called on a wrong this value, it is expected to throw a type error. Promise-returning operations on the other side will return a rejected promise.

I am wondering why attribute getters are not also rejecting.
Although not WebIDL based, https://streams.spec.whatwg.org/#default-reader-closed is doing so for instance.

**Comment by annevk** [comment]
That does sound like a bug. Promise-returning-members should never throw.

**Comment by bzbarsky** [comment]
I recall some earlier discussion about this and this being purposefully decided on...  @domenic do you recall where that was?

What do UAs actually do in practice right now?  (Though note that UAs may well just be implementing the spec as written even if they were not involved in the earlier discussion.)

**Comment by domenic** [comment]
I guss it was https://www.w3.org/Bugs/Public/show_bug.cgi?id=25048 which is still open. I disagree with your last post there...

**Comment by bzbarsky** [comment]
> I guss it was https://www.w3.org/Bugs/Public/show_bug.cgi?id=25048 which is still open.

Ah, yes, that's it.  I was clearly wrong about anything being decided.

**Comment by youennf** [comment]
Promise attributes are starting to appear, so it would be good to decide what is right
In addition to reader.closed, there is WebIDL-based FontFaceSet.ready.
Rejecting seems indeed more intuitive to me.

**Comment by bzbarsky** [comment]
There are also Animation.ready, Animation.finished, FontFace.loaded, MediaKeySession.closed, ServiceWorkerContainer.ready, RTCPeerConnection.peerIdentity, and PresentationReceiver.connectionList.  Some of these have been shipping for quite a while now.

Again, I'd be curious as to what UAs already do for those attributes.  I don't expect there to be much in the way of compat constraints here, but it would be good to know what they might be.
