### ISSUE TITLE
Do objects support indexed/named properties, or do their interfaces?

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#199]
This is a minor editorial nit.

According to the definitions, these predicates apply to interfaces, not JavaScript objects:

> An interface that defines an indexed property getter is said to support indexed properties.
> 
> An interface that defines a named property getter is said to support named properties.

However, a few  places in the spec use them on objects directly:

> If O supports named properties, O does not implement an interface with the [Global] or [PrimaryGlobal] extended attribute ...

(and many more)

I see two potential fixes:
1. Change them all to "If O implements an interface that supports named properties"
2. In the definitions of those phrases, say "A platform object is said to support named properties if it implements an interface that supports named properties."

**Comment by tobie** [comment]
Option 2 sounds less verbose and just as clear, no?

**Comment by domenic** [comment]
Yeah sounds good to me.
