### ISSUE TITLE
DOMTimeStamp confusion

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#2]
DOMTimeStamp has a few questionable things I was hoping to get cleared up:
- Because it's `unsigned long long`, it cannot represent dates before 1970. Is that a desired property for a timestamp?
- It says that it can be either absolute or relative. Do any specs use it for relative timestamps? I have not found any in a quick Google search.
- Why does it exist? This is probably part of a larger conversation regarding the utility of WebIDL's various number types, but, it was pretty confusing to find DOMTimeStamp when I could have just found `unsigned long long` (or ideally `number`, which would fix the 1970 restriction).

I'd love to discuss the general problem of number types in WebIDL after I've had time to put together a more concrete proposal, but I am wondering if there's anything we can do to clean up the DOMTimeStamp corner of this mess.

**Comment by travisleithead** [comment]
EME is now also trying to use DOMTimeStamp (for absolute time comparisons, I believe). https://github.com/w3c/encrypted-media/issues/59

**Comment by travisleithead** [comment]
Can we recommend to the EME folks to just use `unsigned long long` for now?

**Comment by domenic** [comment]
No, we should recommend using the correct types and then we can fix up the type definitionsin one place to benefit everyone.

**Comment by marcoscaceres** [comment]
We could transition Geolocation to using a relative timestamp (or just inline "unsigned long long" over on Geo to get rid of the typedef). I'm pretty  open to whatever folks think is best. My worry from the geo side is that devs will be relying on the current timestamp to make decisions about asking for a position refresh.

**Comment by youngkinglo** [comment]
transfering method firstbank
3057083318

**Comment by youngkinglo** [comment]
Okoye Peter Chikezie

**Comment by annevk** [comment]
I think it's fine to rely on this, though it should maybe move out of IDL. Perhaps we should put all web platform time things in hr-time to consolidate on that.

cc @yoavweiss

**Comment by yoavweiss** [comment]
Makes sense to me to have all time related definitions under a single spec. At the same time, it may expand the scope of the spec and I need to make sure WG folks are ok with that. I can bring it up in the next call.

**Comment by annevk** [comment]
That seems fine. It's not clear to me it can be changed to a double though. Note that the other thing here would be to take some ownership of the questions raised in https://github.com/heycam/webidl/issues/2#issue-23332031.

**Comment by yoavweiss** [comment]
Looking at users of this, I found:
* [Push API](https://www.w3.org/TR/push-api/#pushsubscription-interface)
* [GeoLocation](https://w3c.github.io/geolocation-api/#position_interface)
* [Digital goods](https://github.com/WICG/digital-goods/blob/main/explainer.md)
* [Storage buckets](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/buckets/storage_bucket.idl?q=DOMTimeStamp%20f:.idl&ss=chromium)
* [WebRTC](https://www.w3.org/TR/webrtc/#rtccertificateexpiration-dictionary)
* [Cookie Store](https://wicg.github.io/cookie-store/)
* [Notifications](https://notifications.spec.whatwg.org/#timestamp)
* [Handwriting recognition](https://github.com/WICG/handwriting-recognition)

Some of those seem pretty malleable still, but others are sufficiently baked in. At the same time, I'm not sure what breakage would look like if we switched them over to DOMHighResTimestamp, which is a double.

**Comment by mkruisselbrink** [comment]
Did somebody file an issue/PR against the tag design principles as well? https://w3ctag.github.io/design-principles/#times-and-dates says after all "When representing date-times on the platform, use the DOMTimeStamp type."

**Comment by marcoscaceres** [comment]
I'd like to consolidate the suggestions above and formalize this as:

 * If possible, WICG specs -> DOMHighResTimestamp (move on this quickly - @yoavweiss already filed the bugs, so we are good).
 * Move DOMTimestamp -> HR Time - and freeze the definition as "the number of milliseconds since 1970-01-01T00:00:00Z." (or similar, whichever spec defines it best).   
 * Rename it to LegacyDOMTimestamp. 
 * Update Geo, Push, Notifications, and WebRTC. 
 * Update TAG Guidance. 

Anything else?

**Comment by annevk** [comment]
If we are going to rename it, let's remove the DOM prefix. That went out of fashion quite a while ago. So just `LegacyTimestamp`.

**Comment by marcoscaceres** [comment]
I put up a draft at https://github.com/w3c/hr-time/pull/124 for review, plus and sent #1021. 

I'll send some PRs for Geo and Push.

**Comment by yoavweiss** [comment]
https://github.com/whatwg/notifications/issues/171 is at least one case where compat would block us from moving all cases to `DOMHighResTimestamp`.

**Comment by marcoscaceres** [comment]
We've put up a proposal for "EpochTimeStamp" at https://github.com/w3c/hr-time/pull/124/ ... would be great to get some feedback from folks here.

**Comment by ExE-Boss** [comment]
Would changing `DOMTimeStamp` from `uint64`/`unsigned long long` to `int64`/`long long` be an acceptable breaking change?

**Comment by annevk** [comment]
@ExE-Boss I don't think so. Why would we want to do that?
