### ISSUE TITLE
State the associated realm when creating objects

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#206]
Currently, and after #205, there is the statement

> This object also must be associated with the ECMAScript global environment associated with the interface object.

I think this should become something like

> The return value must also be created such that its [associated Realm] is _F_.[[Realm]].

When we fix #135, this will be true by default. In the meantime it's just a rephrasing of the legacy "ECMAScript global environment" language in terms of realms.

**Comment by tobie** [comment]
Is there any reason to have a separate algorithm to construct named constructors from regular ones? Else this seems ripe for refactoring.

**Comment by Ms2ger** [comment]
I think this is clear now.

I think we should probably keep the two algorithms; there's just enough difference that it'd be a pain to extract the common parts.
