### ISSUE TITLE
Fix error handling when using Call()

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#207]
Figure out which invocations (ES6 `Call()`) need to be preceded by `?` (can throw) and which by `!` (can never throw)

**Comment by bzbarsky** [comment]
I would expect they can all throw.

**Comment by annevk** [comment]
Note that we also need to do this for ToString, ToUint32, etc. Basically any invocation of an abstract operation or internal method needs to vetted.

**Comment by annevk** [comment]
@bzbarsky https://heycam.github.io/webidl/#es-map-set step 13 expects the invocation to not throw.

**Comment by bzbarsky** [comment]
That is ... incorrect.  But I guess it's only incorrect because step 6 gets some random function, instead of the original Map.prototype.set function.  Why the heck does it do that?  That's certainly not what I recall being decided on, and not what Gecko implements for maplikes!

**Comment by bzbarsky** [comment]
Or maybe the idea was that the `[[BackingMap]]` comes from a clean global?  But nothing says that.

**Comment by bzbarsky** [comment]
Blame suggests things have been in this state for a while, which really confuses me.  Are we really trying to spec this to be calling the page-visible "whatever thing named `'set'` is up the proto chain"?

**Comment by bzbarsky** [comment]
@domenic
