### ISSUE TITLE
Way to mark a method as "async"

### ISSUE THREAD

**Issue by marcoscaceres** [heycam/webidl#214]
It would be nice if WebIDL provided a means to mark a method as async, like:

```Java
interface Foo {
   async returnValue whatever(); 
}
```

I was reading the Web Payments spec and noticed that they are using exceptions and promises incorrectly (they try to throw exceptions before they return the promise). Something like the above would prevent such issues by implicitly returning the promise. Any thrown exceptions in the method's prose will then just be converted to rejections by the promise machinery. 

Furthermore, such methods could then use "await" semantics if they need to wait for other methods or even internal "promises", etc. 

So, like: 

> When `foo()` is called:
>  1.  If some condition, throw a WhatEvesError. 
>  2. If [[slot]] was not set, throw NotAllowedError.
>  3. Let x be there result of awaiting thing that happens in another thread (where "thing" runs in parallel). 
>  4. return x. 

And 4. nicely resolves the promise. Or some such.

**Comment by domenic** [comment]
This is already provided by Web IDL. Returning a promise type implicitly transforms any throws to rejections and returns to fulfillments: https://heycam.github.io/webidl/#dfn-create-operation-function step 2. I think it's bad practice to be implicit in this way though.

I think the awaiting construct you describe is not good. It's mixing up two things: in parallel, and promises. You shouldn't be able to await non-promises. If you want to await promises, use https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled; if you want to wait until things run in parallel, just "Wait, in parallel".

**Comment by marcoscaceres** [comment]
@domenic, thanks for the clarification.
