### ISSUE TITLE
Union types with colliding enum values

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#219]
consider:

```webidl

enum A {
  "foo",
  "bar"
};

enum B {
  "foo",
  "baz"
};

interface C {
  attribute (A or B) prop;
};
```

what happens if we do `someC.prop = "foo"`?

I think probably we should just disallow union types where the flattened member types contain enums with conflicting values.

**Comment by bzbarsky** [comment]
>    attribute (A or B) prop;

Not valid IDL, because two enum types are never considered distinguishable.  Doesn't matter whether they have any overlap in values.

**Comment by domenic** [comment]
Ah, I should have been looking at distinguishability, not union types. Thanks!
