### ISSUE TITLE
Use Type(V) is object instead of if |V| is any kind of object

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#222]
See https://github.com/heycam/webidl/pull/220#discussion_r86388353

**Comment by tobie** [comment]
Do we also want to change things like this:

```
If |V| is <emu-val>null</emu-val> or <emu-val>undefined</emu-val>, then…
```
to 

```
If [=Type=](|V|) is Null of Undefined, then…
```

**Comment by tobie** [comment]
What about:

```
If |V| is a native <emu-val>Error</emu-val> object
(that is, it has an \[[ErrorData]] [=internal slot=]), then:
```

to:

```
If Type(|V|) is Object and |V| has an \[[ErrorData]] [=internal slot=])
(it's a native <emu-val>Error</emu-val> object), then:
```

**Comment by domenic** [comment]
> Do we also want to change things like this:

These are equivalent. The ES spec seems to use both. From some brief skimming, it compares against the literal values most of the time, and does Type comparisons when it's part of a series of type comparisons (e.g. compare step 1 and step 8.a in https://tc39.github.io/ecma262/#sec-ordinarysetprototypeof).

I'd say not worth messing with unless you see something obviously weird as you go by.

> What about:

This seems like a good change for slight clarity improvements. I might omit the parenthetical. Unlike the original change that spurred this issue though, it doesn't move us from using an unspecified concept to a specified one, so it's not as important.

**Comment by annevk** [comment]
Isn't "native Error object" kinda unspecified? That's not a phrase ECMAScript would use I think.

**Comment by domenic** [comment]
Yes, but the parenthetical specifies what is meant precisely.

**Comment by tobie** [comment]
Closed by https://github.com/heycam/webidl/commit/898b8d2cf666b118875e6e344f743643335ea8b9 (#270).
