### ISSUE TITLE
enum local to interface

### ISSUE THREAD

**Issue by AxelNennker** [heycam/webidl#227]
Currently enum are in the global namespace.

Enums should be able to be specified local to interfaces.

This example https://heycam.github.io/webidl/#example-363ff014 would then look like this
interface Meal {
  enum MealType { "rice", "noodles", "other" };
  attribute MealType type;
  attribute double size;     // in grams
  void initialize(MealType type, double size);
};
and the usage would look like 
var ravioli = new Meal();
ravioli.initialize(Meal.MealType.noodles, 200);

window.MealType is undefined

**Comment by annevk** [comment]
I don't really understand this suggestion. Enum values are not exposed to script. The whole idea is that you use strings directly, not constants. It might be better if JavaScript had native enum support, but that doesn't exist.

**Comment by bzbarsky** [comment]
> window.MealType is undefined

That's true no matter what; the name of the enum type is not exposed to anything anywhere outside the IDL parser.

**Comment by AxelNennker** [comment]
Right. I got an error message from the Mozilla parser about two enums with the same name in different webidls. But this issue is not that issue.
