### ISSUE TITLE
Should we x-link base concepts to the Infra Standard?

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#242]
Thinking of things such as sets, lists, etc.

I think that only really makes sense if it helps people understand the standard better, not if it clutters it more.

We could also just have a one liner somewhere that references https://infra.spec.whatwg.org/ and specifically mentions that sets, lists, etc, used in the spec are defined there.

**Comment by domenic** [comment]
I see this as a nice to have, but not a high priority. Cross-linking helps make sure everyone is on the same page about what basic operations and concepts mean, and that everyone is using the same terms.

Stuff in https://infra.spec.whatwg.org/#conventions is also clarifying, although it doesn't require cross-linking.

There's also some work to be done here for strings and IDL's concepts there, but that's not quite ready yet: https://github.com/whatwg/infra/issues/1. https://github.com/heycam/webidl/issues/236 is also related.

**Comment by tobie** [comment]
Oh, string. Yes. I was going to defer asking about this. :D

**Comment by tobie** [comment]
We've started doing this when we write new content or update existing one. No point keeping this issue open.
