### ISSUE TITLE
Should perform security check for constructors

### ISSUE THREAD

**Issue by zcorpan** [heycam/webidl#249]
See https://github.com/w3c/browser-payment-api/issues/361#issuecomment-265719019

It seems to me https://heycam.github.io/webidl/#es-constructible-interfaces should invoke "perform a security check" somewhere before step 6.

Test case for `WebSocket`: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4720

cc @bzbarsky @annevk

**Comment by tobie** [comment]
If we do this, should we invoke the **_perform a security check_** algorithm with `Window` as the platform object on which the operation invocation is done, the name of the constructor as the operation identifier and `"method"` as the Function object type? Or should we modify the algorithm in HTML to deal specifically with constructors?

**Comment by bzbarsky** [comment]
@zcorpan Perform a security check on what?  Why would we want to do that at all?  Note that your testcase never even calls the WebSocket constructor, so I'm not sure why it's relevant to this bug.  A testcase that _does_ call it is http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4721 and that one would be problematic even if the navigation were to a same-origin page: either way the websocket would stay alive forever per spec.  See https://github.com/whatwg/html/issues/2153 that I just filed.

@tobie, the check you describe would always pass, no?

**Comment by zcorpan** [comment]
Oops, thanks for correcting the test case.

> Perform a security check on what?

I don't know. I'm still trying to wrap my head around how these things work. Per your comment above and https://github.com/w3c/browser-payment-api/issues/361#issuecomment-265814366 I take it that the security check wouldn't make sense for constructors, but active document check makes sense. But not for all constructors. `Date` or `Image` are not problematic for example. OK. Let's close this and discuss `PaymentRequest` in the other issue.

**Comment by tobie** [comment]
@bzbarsky after a cursory look at the HTML spec, that was my impression too, but given I'm not sure what this security check is actually supposed to check…
