### ISSUE TITLE
Serialized value should allow any string type

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#259]
https://heycam.github.io/webidl/#dfn-serialized-value is overly restrictive. All string types convert into a JavaScript string after all at the return boundary.

**Comment by tobie** [comment]
Yeah. I'm having a hard time figuring out precisely why we need a distinction between serialized values and [serialized types](https://heycam.github.io/webidl/#dfn-serializable-type).

**Comment by bzbarsky** [comment]
Chances are this just wasn't expanded when new string types were added.  I see no reason to limit it to DOMString.

**Comment by tobie** [comment]
@bzbarsky, the serializable types do contain all string types and convert them all to DOMStrings, so I son't think that's an omission.
