### ISSUE TITLE
Allowing something to be the serializer and stringifier

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#260]
For https://github.com/whatwg/url/issues/137 we want URL's href attribute to also be the value the serializer returns. However, it's already the stringifier and as far as I can tell the IDL grammar does not allow for both. There's the prose escape-hatch of course, but that seems sad?

**Comment by bzbarsky** [comment]
I still think that all serializer options except "serialize all the attributes" should be handled via prose or explicit toJSON functions (which we should allow).  The current serializer complexity is ridiculous and not implemented by anyone; allowing people to define toJSON functions would let them handle all this themselves as desired if they want weird serialization behavior, with the one "serialize all the attributes" simple thing for the common case of objects which basically represent a collection of values.
