### ISSUE TITLE
Should mixins be able to add overloads?

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#261]
Consider this IDL:

    interface A {
      void foo();
    };

    [NoInterfaceObject]
    interface B {
      void foo(long arg);
    };

    A implements B;

Should this be allowed?  I _think_ the current spec more or less allows it, not least because it's pretty vague about when overload sets are actually determined.  But it's not entirely obvious to me whether this is desirable, because this makes the mixin change the behavior of existing methods on the interface, which is something that should really go in the base spec, not a mixin, I would think.

**Comment by domenic** [comment]
Do we know about existing specs doing this? It seems very likely they might, but if nobody does, then yeah, disallowing would be nice...

**Comment by bzbarsky** [comment]
There aren't any that I'm aware of (in that the Gecko IDL parser explicitly errors out in this situation, and that's not being a problem for us so far), but WebGL is trying to add this sort of thing.

**Comment by annevk** [comment]
Hmm, did WebGL not get the memo that overloads in general are a poor API?

**Comment by bzbarsky** [comment]
Not really, no.  They're basically trying to expose the GL APIs, and those are full of overloads or something.

**Comment by bzbarsky** [comment]
However, some of the webgl2 APIs _are_ moving away from overloads more toward unions and optional args.  They just kinda coexist with webgl1 apis that use the old setup.
