### ISSUE TITLE
Add support for attributes on namespaces

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#263]
Needed per https://github.com/w3c/css-houdini-drafts/issues/330#issuecomment-271639727 . I'll take this.

**Comment by bzbarsky** [comment]
Presumably these would behave pretty much like static attributes on interfaces, right?

**Comment by domenic** [comment]
Yep.

**Comment by domenic** [comment]
Let's restrict to readonly for now?

**Comment by zcorpan** [comment]
Sounds reasonable to me. The worklet attributes are readonly.

https://drafts.css-houdini.org/css-layout-api/#layout-worklet
https://drafts.css-houdini.org/css-paint-api/#paint-worklet
(Can't find spec for `animationWorklet` now)

cc @bfgeek

**Comment by domenic** [comment]
Started working on this but realized we will want https://github.com/heycam/webidl/pull/217 to land first.

**Comment by bzbarsky** [comment]
Ugh, sorry; that's still waiting on me, isn't it?  I'm not sure I can get to it today, but I will try to make sure I do it by tomorrow at the latest...

**Comment by domenic** [comment]
I think you were mostly OK with things after I changed to disallow [SameObject] on promises, but another look couldn't hurt.

**Comment by bzbarsky** [comment]
Hmm.  This doesn't seem to have propagated through to https://heycam.github.io/webidl/ as far as I can tell.  @domenic Is that expected?

Apart from that one commented-out attribute which shouldn't be commented out, this looks good to me.

**Comment by bzbarsky** [comment]
Just for my reference, the PR for this is https://github.com/heycam/webidl/pull/264
