### ISSUE TITLE
Are string types and sequence types distinguishable?

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#266]
As discussed in whatwg/url#204, there is some confusion about the distinguishability between string types and sequences. Although currently, the spec maintains that they are [distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable), @domenic and @annevk have express doubts over that.

What I have found is that:

1. ES string primitives are **NOT** valid sequences, and are therefore distinguishable. Even though string primitives have a `@@iterator`, they fail the [`typeof === 'object'` check](https://heycam.github.io/webidl/#es-to-sequence) in conversion to a sequence.
2. ES string wrapper objects **ARE** valid sequences. They pass the aforementioned test, and they likewise have a valid iterator interface.

This is exemplified in Firefox, which implements iterable-to-sequence conversion:

```js
>>  new Headers([ 'ab' ]).get('a')
**  "TypeError: Element of member of HeadersOrByteStringSequenceSequenceOrByteStringMozMap can't be converted to a sequence."
>>  new Headers([ new String('ab') ]).get('a')
<-  "b"
```

How can we resolve this situation?

**Comment by bzbarsky** [comment]
1. String types and sequences are distinguishble.
2. They are very explicitly and purposefully distinguishable, and there are APIs that use `(DOMString or sequence<DOMString>)`.  We purposefully allowed that.
3. ES String objects are in fact valid sequences.  They're also valid dictionaries (something else that is distinguishable from strings), valid callback interfaces, etc.  The fact is, the current design of IDL was more or less predicated on "people don't use explicit String objects and expect any good to come of it".

I don't think there's anything to resolve here; the spec as written is written as intended and reflects reality.

**Comment by annevk** [comment]
I think you misunderstood my comment @TimothyGu. I tried to say that they are distinguishable (plus link to prove it), but that I think your proposal is not the way to go.

**Comment by TimothyGu** [comment]
@annevk, yeah, does seem like I misunderstood. Sorry for the noise.
