### ISSUE TITLE
Require tests for PR/issues?

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#268]
This has been suggested by @annevk and @Ms2ger.

Opening an issue here to come up with a better understanding of how we're testing WebIDL so far, what requires tests would precisely entail, and drafting some text around this to put in the contributing doc.

**Resources:**
* [idlharness src code](https://github.com/w3c/testharness.js/blob/master/idlharness.js)

**Comment by annevk** [comment]
An alternative given the general lack of resources around IDL might be to always file implementation bugs for each change coupled with a request to the implementer to write tests.

**Comment by domenic** [comment]
I would feel more comfortable requiring this if I felt we had a good way to test IDL. If we do, it's not one I understand myself.

Filing implementation bugs makes sense, for sure.

**Comment by annevk** [comment]
We could test specific APIs making use of IDL features. We don't generally stress the bindings for each new feature, somewhat assuming that is taken care of elsewhere. That leads to the IDL parts being without coverage. There's also some IDL testing framework, but I haven't studied that so I'm not sure what it covers.

**Comment by tobie** [comment]
Making sure [idl harness](https://github.com/w3c/testharness.js/blob/master/idlharness.js) is up to date seems a good first step there.

**Comment by tobie** [comment]
See https://github.com/heycam/webidl/pull/217#issuecomment-274201649.

**Comment by tobie** [comment]
Closing in favor of #520 which is more clearly scoped.
