### ISSUE TITLE
hasOwnProperty fails with ClientRect

### ISSUE THREAD

**Issue by davidwparker** [heycam/webidl#27]
Found via debugging some AngularJS:
https://github.com/angular/angular.js/issues/10046

Long story short, `hasOwnProperty` doesn't work with ClientRect on Safari/Firefox, but does with Chrome.... I'm not sure who's right or which one to go with...

forEach:
```javascript
function forEach(obj, iterator, context) {
...
  var key;
  for (key in obj) {
    if (obj.hasOwnProperty(key)) {
      iterator.call(context, obj[key], key);
    }
  }
  return obj;
}
```

In the else statement, the line `if (obj.hasOwnProperty(key)) {` doesn't work against a ClientRect object in Safari/Firefox so it never sets the data as expected.

JSfiddle (view the console):
http://jsfiddle.net/scts6mcs/5/

Chrome: it copies over:
```console
ClientRect {height: 18, width: 447, left: 0, bottom: 18, right: 447…}
447
Object {height: 18, width: 447, left: 0, bottom: 18, right: 447…}
447 
```

Safari/Firefox: it fails to copy over the information.
```console
[Log] ClientRect (show, line 45)
[Log] 424 (show, line 46)
[Log] Object (show, line 51)
[Log] undefined (show, line 52) <-- didn't get copied
```

**Comment by heycam** [comment]
Closing, as there's no issue in the spec.
