### ISSUE TITLE
Require `new` for named constructors

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#275]
At least Gecko and Blink require `new` for them. Edge does not, but Edge also does not require `new` for un-named constructors.

We should test Safari TP to be sure, but it seems like things have moved in this direction, even though to me it would be OK for "named constructors" to not require `new` since they're fancy factory functions in disguise.

**Comment by tobie** [comment]
How does one require new. With a NewTarget that's not undefined?

**Comment by domenic** [comment]
Yep, exactly, like https://heycam.github.io/webidl/#es-constructible-interfaces step 2

**Comment by bzbarsky** [comment]
I can't tell you about Safari TP, but in WebKit nightly requires `new` on both constructors and namedconstructors.  So Edge is the odd engine out here.
