### ISSUE TITLE
Investigate/file bugs on named constructor prototype chain

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#276]
The code `Image.prototype === HTMLImageElement.prototype` returns true in the spec, edge, and Gecko, but false in Chrome. We should test Safari TP.

Personally I'd rather have these things just have Function.prototype as their prototype, and the fact that Chrome doesn't get this right means that we could probably in theory change this. But likely it's not worth the churn and we should just file bugs on the browsers that don't match the spec (Chrome and maybe Safari) to start matching it.

**Comment by domenic** [comment]
@tobie mentioned in IRC that Blink also gets the `name` property wrong.

**Comment by bzbarsky** [comment]
`Image.prototype === HTMLImageElement.prototype` is true in WebKit nightly.

Having Image.prototype be Function.prototype would make the story about subclassing Image pretty confused, no?   How would Image determine the prototype of the things it creates?

For what it's worth, Chrome's answer seems to be that Image.prototype is an object with the following properties:

    Object.getPrototypeOf(Image.prototype) === HTMLImageElement.prototype
    Image.prototype.constructor === Image

and `new Image` creates objects whose proto is in fact `Image.prototype`.   So it's not like it's having Function.prototype here either....  What it _is_ having is that objects created via `new Image` have a slightly different proto chain from other images.  I don't see a really good reason for doing that, honestly, and none of the other browsers do.

**Comment by tobie** [comment]
Amusingly, in Chrome, `Image.name` is "HTMLImageElement".

**Comment by bzbarsky** [comment]
As far as tests go, idlharness should totally be testing this (and isn't).  We have [NamedConstructor] bits in html/dom/interfaces.html in wpt.  So if we just fixed idlharness to test this, we'd have tests.

**Comment by tobie** [comment]
> As far as tests go, idlharness should totally be testing this (and isn't). We have [NamedConstructor] bits in html/dom/interfaces.html in wpt. So if we just fixed idlharness to test this, we'd have tests.

Yeah, I'll do this.

**Comment by Ms2ger** [comment]
Wrote tests in https://github.com/web-platform-tests/wpt/pull/14841.

The bug mentioned in https://github.com/heycam/webidl/issues/276#issue-202564214 was fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=310776.

The results:
* In Chrome, `Object.getOwnPropertyDescriptor(Image, "prototype").writable` is true, while it should be false per spec. (WebKit and Gecko pass.)
* In WebKit, `Object.getPrototypeOf(Image)` is `HTMLElement`, while it should be `Function.prototype` per spec. (Chrome and Gecko pass.)

**Comment by rakuco** [comment]
> * In Chrome, `Object.getOwnPropertyDescriptor(Image, "prototype").writable` is true, while it should be false per spec. (WebKit and Gecko pass.)

I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=921633 and will work on fixing it myself.

**Comment by Ms2ger** [comment]
WebKit fixed in https://bugs.webkit.org/show_bug.cgi?id=190216.
