### ISSUE TITLE
Rename "named constructors"

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#277]
1. They are a legacy feature
2. They are not constructors

Since this is apparently only used by HTML (can someone confirm?) it should be an easy rename.

I'm thinking "LegacyFactoryFunction"? And the whole feature should be renamed "legacy factory functions".

**Comment by bzbarsky** [comment]
> They are not constructors

In what sense are they not constructors?  They're constructors; they just happen to not be named the same as the interface is named...

**Comment by domenic** [comment]
I guess they pass the IsConstructor() check, that's true. But so does `function F() { }`.

I meant it in the sense of them not being "the" constructor for a class. The one returned by `prototype.constructor` and such.

**Comment by tobie** [comment]
This also implies renaming the extended attribute, right?

**Comment by annevk** [comment]
Yeah, "LegacyFactoryFunction" is the suggestion for that.
