### ISSUE TITLE
Should callback interface objects have a "length" property?

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#279]
Callback interface objects already have a "name" property (when exposed due to the presence of constants) . The omission of a "length" prop (with value `0`) in the spec seems more accidental than deliberate. Chrome, Safari and Firefox all implement it, e.g.:

```js
NodeFilter.length;
// => 0
```

**Comment by tobie** [comment]
idlharness excludes callback interfaces (with constants) from testing for the presence and value of length.

**Comment by domenic** [comment]
Edge also supports this.

**Comment by domenic** [comment]
A more interesting question is whether it should be an own property. `NodeFilter.hasOwnProperty("length")` returns true in Gecko and Blink but not Edge. (In Edge, it gets the length from `NodeFilter.__proto__ === Function.prototype`.)

**Comment by domenic** [comment]
So I guess this amounts to changing

> Interface objects for non-callback interfaces

to

> All interface objects

and adding tests I suppose

**Comment by tobie** [comment]
> A more interesting question is whether it should be an own property. NodeFilter.hasOwnProperty("length") returns true in Gecko and Blink but not Edge. (In Edge, it gets the length from NodeFilter.__proto__ === Function.prototype.)

For consistency with other interface objects, own prop seems more judicious.

**Comment by tobie** [comment]
See also https://github.com/whatwg/dom/issues/186 and #83.
