### ISSUE TITLE
Update definition of function objects to latest ES draft

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#280]
See https://heycam.github.io/webidl/#dfn-function-object.

**Comment by tobie** [comment]
If anyone could also enlighten me on the purpose of this definition and how it contrasts with regular ES functions, I'd be very grateful.

**Comment by tobie** [comment]
If anyone could also enlighten me on the purpose of this definition and how it contrasts with regular ES functions, I'd be very grateful. Tagging @domenic, @bzbarsky.

**Comment by bzbarsky** [comment]
The basic intent here is that what is currently called "function object" in IDL should be https://tc39.github.io/ecma262/#sec-built-in-function-objects

**Comment by tobie** [comment]
@bzbarsky OK, so it's a placeholder of sorts. I'll fix this in a later PR, but knowing that helps me solve a bunch of issues in the meantime. Thanks.
