### ISSUE TITLE
Investigate why no [[HasInstance]] is defined for named constructors

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#282]
I'm aware that [[HasInstance]] is deprecated, yet it's defined for interface objects.

The following is the observed behavior in FF and Chrome:

```js
new Image() instanceof HTMLImageElement;
// => true
new Image() instanceof Image;
// => true
```

The latter especially doesn't seem to be explained by what's in the spec.

**Comment by domenic** [comment]
This is explained by setting `.prototype`. The default [[HasInstance]] of all objects just looks at the prototype property, which is set for named constructors. I do not believe this is an issue.

For other issues on HasInstance see https://github.com/heycam/webidl/issues/129. It's unfortunately controversial.

**Comment by tobie** [comment]
Right, but it's set to the [interface prototype object](https://heycam.github.io/webidl/#dfn-interface-prototype-object) of the named constructor's related interface, so how come `new Image() instanceof Image;` is `true`?

**Comment by domenic** [comment]
Because `instanceof X` looks at `X.prototype` by default. https://tc39.github.io/ecma262/#sec-ordinaryhasinstance

**Comment by tobie** [comment]
Duh.
