### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by rainerschuster** [heycam/webidl#29]
I recognized various grammar issues:

1. The production Readonly is used several time but only ReadOnly exists
2. The production ReadonlyMemberRest uses Maplike and Setlike, but only MaplikeRest and SetlikeRest exist
3. The production BufferRelatedType contains the alternative "Int161Array" that should be "Int16Array"

**Comment by heycam** [comment]
> The production Readonly is used several time but only ReadOnly exists
> The production ReadonlyMemberRest uses Maplike and Setlike, but only MaplikeRest and SetlikeRest exist

These two were fixed by #56.

> The production BufferRelatedType contains the alternative "Int161Array" that should be "Int16Array"

And this was fixed by #30.
