### ISSUE TITLE
Environment stuff for exception throwing is nonsense

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#292]
Was just pointed to https://heycam.github.io/webidl/#dfn-current-global-environment today.  Why do we think there is a Function on "the ECMAScript call stack" at all?  What if we're in https://html.spec.whatwg.org/multipage/browsers.html#windowproxy-getownproperty invoked at toplevel like so:

    <script>crossOriginIframe.contentWindow.history</script>

?

Once we get past that, why would this Function be the `this` of anything?  That part doesn't make sense.

I think this whole section should be replaced by a reference to https://html.spec.whatwg.org/multipage/webappapis.html#current-global-object or so.

@domenic

**Comment by domenic** [comment]
I think to preserve the intention of the currently spec, and also to align with #206, we need "the relevant realm of this" in most cases, not "the current realm". Do you have any suggestions for phrasing that would capture that? Maybe we should block this on #206?

**Comment by bzbarsky** [comment]
That's not really viable, in my opinion, because for a number of these exceptions there is no "this" to speak of.

As a simple example, the SecurityErrors thrown by cross-origin windows really shouldn't use the "relevant realm" of the cross-origin target, because then you wouldn't even be able to examine the exceptions, right?

Same thing for Web IDL algorithms of various sorts.  For example, https://heycam.github.io/webidl/#dfn-create-operation-function step 2.1.2.4.  What is "the relevant realm of this" in that case?

The example code you mention is ... unclear to me.  Is it actually calling the computeSquareRoot function (the JS function) and having it throw?  Or is it performing its underlying steps without calling through JS?  It matters in terms of the current global, obviously.

I should also note that IDL does say:

> Any requirements in this document to throw an instance of an ECMAScript built-in Error must use the built-in from the current global environment.

which means it's actually trying to specify different behavior for Error and TypeError, for reasons that are entirely unclear to me....

Anyway, in practical terms, I think that implementations don't necessarily represent exceptions as objects internally, and their internal representations may not admit attaching a global to them (not least for efficiency reasons).  As a result in practice exceptions are given a global in the binding layer.  I did just check, as a simple example, what WebKit, Blink, and Gecko do for querySelector.  WebKit has `ec = SYNTAX_ERR;` where `ec` is an `ExceptionCode&`.  Blink has `exceptionState.throwDOMException(SyntaxError, "'" + selectors + "' is not a valid selector.");` and Gecko has `aRv.ThrowDOMException(NS_ERROR_DOM_SYNTAX_ERR, NS_LITERAL_CSTRING("'") + NS_ConvertUTF16toUTF8(aSelectorString) + NS_LITERAL_CSTRING("' is not a valid selector")` none of which attach a global at the exception throw point.

**Comment by domenic** [comment]
I guess that's fair. I need to check that I didn't give bad advice to the Chrome bindings team then, on the understanding that we'd be moving everything in the direction of #135...
