### ISSUE TITLE
Where does it say that a nullable record<> cannot be the type of a dictionary member?

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#295]
There is a note in https://heycam.github.io/webidl/#idl-nullable-type that says:

> Note: Although dictionary and record types can in general be nullable, they cannot when used as the type of an operation argument or a dictionary member.

but I see nothing in the spec supporting the claim that a nullable record type cannot be the type of a dictionary member.  The nullable-dictionary case is covered by this language in <https://heycam.github.io/webidl/#idl-dictionaries>:

> If the Type is an identifier followed by ?, then the identifier must identify an interface, enumeration, callback function or typedef.

(But even that doesn't handle a typedef of a dictionary!)  But nothing there says anything about records.

/cc @jyasskin @domenic @tobie @annevk

**Comment by jyasskin** [comment]
I think we have the opposite bug: records are simply not allowed as dictionary members:

> Each dictionary member (matching DictionaryMember) is specified as a type (matching Type) followed by an identifier (given by an identifier token following the type). The identifier is the key name of the key–value pair. If the Type is an identifier followed by ?, then the identifier must identify an interface, enumeration, callback function or typedef. If the dictionary member type is an identifier not followed by ?, then the identifier must identify any one of those definitions or a dictionary. -- https://heycam.github.io/webidl/#idl-dictionaries

"the identifier must identify an interface, enumeration, callback function or typedef" doesn't allow records (except via typedefs, of course), and neither does "any one of those definitions or a dictionary".

We should add "or a record" to the end of the last sentence?

**Comment by bzbarsky** [comment]
> doesn't allow records

That's OK, because for the case of records the `Type` is not an identifier at all; it's a `RecordType` production.  So this whole clause doesn't apply at all.

**Comment by jyasskin** [comment]
Aha! Yep, I agree now.

Separately, it'd be nice if these restrictions were semantic instead of syntactic.

**Comment by bzbarsky** [comment]
> Separately, it'd be nice if these restrictions were semantic instead of syntactic.

Yes.  That would fix the "nullable typedef of dictionary" thing
