### ISSUE TITLE
`any` type conversion does not take into account of symbols

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#301]
https://heycam.github.io/webidl/#es-any uses [Type(<var>x</var>)](https://tc39.github.io/ecma262/#sec-ecmascript-language-types), but does not define a case for when Type(<var>V</var>) is Symbol, as is possible under the current ES spec.

**Comment by bzbarsky** [comment]
Yeah, we probably need to define an IDL type for Symbols and map to that...

**Comment by TimothyGu** [comment]
@bzbarsky, do we really need a symbol type for IDL though? What applications for it can you foresee?

**Comment by bzbarsky** [comment]
None offhand, but the way IDL works in general is that ES types get mapped to IDL types, so we need a way to represent Symbol on the IDL side.  The Symbol type would work much like "object": it would just be an opaque reference to the ES Symbol.

There would be no syntactic way to express the Symbol type other than "any".
