### ISSUE TITLE
Code-points, code-units, characters, oh my!

### ISSUE THREAD

**Issue by marcoscaceres** [heycam/webidl#312]
As per, https://github.com/w3c/browser-payment-api/issues/322 and also in HTML, it seems that spec editors want to talk about "characters", as those things <del>logically</del> editorially make most sense. 

It would be nice if WebIDL allowed talking about "characters" in the context of DOMString.

**Comment by annevk** [comment]
I think it's actually better to not talk about characters. We're slowly changing things around. Especially in the context of DOMString that would be extremely ambiguous.

**Comment by marcoscaceres** [comment]
That's fine - but need guidance. I tried the other two and got laughed at for using the wrong 👍

**Comment by annevk** [comment]
Yeah, that's https://github.com/whatwg/infra/issues/1 basically. I have plan, but haven't made the time thus far.

**Comment by marcoscaceres** [comment]
Ok, don't feel so bad now - and that's great to see! Thanks @annevk!

**Comment by tobie** [comment]
Seems this is in infra's realm. Closing here.
