### ISSUE TITLE
Scroll script causes jank

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#314]
Reported by @marcoscaceres.

**Comment by marcoscaceres** [comment]
It was really cool at first... but now it's getting painful to use when you have to spend a lot of time in the spec :(

**Comment by tobie** [comment]
I have an obvious workaround for you given your last comment. :trollface:

**Comment by tobie** [comment]
@marcoscaceres: [preview](https://s3.amazonaws.com/pr-preview/tobie/webidl/fix-scroll.html). Better?

**Comment by marcoscaceres** [comment]
Much, specially in Firefox and Safari! Poor Chrome tho.
