### ISSUE TITLE
Why can't an inherited dictionary override something as required?

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#321]
Context: in https://github.com/w3c/browser-payment-api/pull/425 we are trying to define

```webld
dictionary PaymentDetailsBase {
  PaymentItem total;
  // ... a bunch of other stuff
}

dictionary PaymentDetailsInit : PaymentDetailsBase {
  required PaymentItem total;
}
```

so that some APIs can require the `total` member. But, this appears to be disallowed by Web IDL:

> The identifier of a dictionary member must not be the same as that of another dictionary member defined on the dictionary or on that dictionary’s inherited dictionaries.

Is there any disadvantage to lifting this restriction for the specific case of being required in the derived dictionary?

**Comment by bzbarsky** [comment]
The conceptual model is that a dictionary has a bunch of slots named whatever they're named.  If you look at the es-to-dictionary algorithm, you basically just invoke your ancestor dictionary's version to fill its slots, then fill your own.

So the syntax, if it were allowed and with no other changes to anything, would create two slots named "total"; one in PaymentDetailsBase and one in PaymentDetailsInit.  And they would both be initialized by calling Get() (twice; once for each slot) on the given object.

So we _could_ allow this, but it would either want different syntax or having the same syntax mean pretty different things depending on non-local state.  And it would require some changes to the way es-to-dictionary conversion works.

Fwiw, this seems like it would address the web payments use case:

    dictionary PaymentDetailsBase {
      // ... a bunch of other stuff
    };

    dictionary PaymentDetailsMaybeNoTotal : PaymentDetailsBase {
      PaymentItem total;
    };

    dictionary PaymentDetailsInit : PaymentDetailsBase {
      required PaymentItem total;
    };

**Comment by domenic** [comment]
Hmm, I guess in this particular case there is indeed a pretty simple workaround. Let's mark this as wontfix for now, but keep an eye out for recurrences...
