### ISSUE TITLE
extended attributes symbol/form count typo

### ISSUE THREAD

**Issue by avrljk** [heycam/webidl#330]
There are five grammar symbols / forms listed in the table near the top of the Extended Attributes section.
The two paragraphs either side of the table refer to six grammar symbols / forms.

https://www.w3.org/TR/WebIDL-1/#dfn-extended-attribute
https://heycam.github.io/webidl/#idl-extended-attributes

**Comment by tobie** [comment]
Thanks for the report.

I see you seem to be a new GitHub user. Creating a pull request for this change can be done rather easily using the online editor. You can follow this link: https://github.com/heycam/webidl/edit/master/index.bs which will automatically fork the repository to your own account, open the online editor to fix the spec source code, and allow you to send a pull request with your changes in a single click.

Happy to help if you have any issues.

It's also fine if you don't want to do it or don't have the time. Just let me know below, I'll happily fix it myself.

Either way: Thanks again!

**Comment by avrljk** [comment]
> It's also fine if you don't want to do it or don't have the time. Just let me know below, I'll happily fix it myself.

  Sorry, it's lack of time that's the problem.

Regards,
--
Jonathan Knispel
VR, AR, HCI and Visualisation Consultant; AVRL Chair
jonathan.knispel@uwa.edu.au  |  +61 8 6488 7876  |   avrl.org.au
________________________________________
