### ISSUE TITLE
Allow [TreatNullAs=EmptyString] for USVString?

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#340]
This is used in https://w3c.github.io/webrtc-pc/#peer-to-peer-data-api

```WebIDL
partial interface RTCPeerConnection {
    readonly attribute RTCSctpTransport? sctp;
    RTCDataChannel createDataChannel([TreatNullAs=EmptyString] USVString label,
                                     optional RTCDataChannelInit dataChannelDict);
    attribute EventHandler ondatachannel;
};
```

However, it's not allowed per Web IDL:
https://heycam.github.io/webidl/#TreatNullAs

> The `[TreatNullAs]` extended attribute must not be associated with a type that is not DOMString.

Is there a reason for this restriction?

**Comment by domenic** [comment]
The only reason I can think of is that this is a legacy extended attribute that creates un-idiomatic APIs, and so it was desired to stop its spread to newer APIs that use newer technology like USVString.

We're planning to rename it to [LegacyTreatNullAsEmptyString] BTW.

**Comment by foolip** [comment]
FWIW, there's a decent change it's not really needed, [Gecko's IDL](https://github.com/mozilla/gecko-dev/blob/3abfe370ac37d2ae03f9ec169a384975c60c175f/dom/webidl/RTCPeerConnection.webidl#L138) has this argument as simply `DOMString label`. I'll ask on https://github.com/w3c/webrtc-pc/issues/1118 if it's there for known compat reasons or not.

**Comment by tobie** [comment]
Closing as that's now been fixed in webrtc ["tip of tree"](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html) (which is somehow ahead of the ED).

**Comment by foolip** [comment]
@tobie, that's https://github.com/w3c/webrtc-pc/issues/942, please comment there if it caused you confusion or time wasted.
