### ISSUE TITLE
"array index property name" doesn't guard against failure

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#346]
In particular, ToUint32 can throw and the various callers we have of this check don't expect that. (At least not those in HTML.)

**Comment by bzbarsky** [comment]
I must be missing something.

https://heycam.github.io/webidl/#dfn-array-index-property-name says:

> which is a property name P such that Type(P) is String and for which the following algorithm returns true

So we land in https://tc39.github.io/ecma262/#sec-touint32 which can only throw via ToNumber, and our argument is guaranteed to be a String.  https://tc39.github.io/ecma262/#sec-tonumber in the string case says:

> ToNumber applied to Strings applies the following grammar to the input String interpreted as a sequence of UTF-16 encoded code points (6.1.4). If the grammar cannot interpret the String as an expansion of StringNumericLiteral, then the result of ToNumber is NaN.

so how can this throw?

**Comment by annevk** [comment]
Is the Type(P) is String an assertion that the input must meet or a check on input that makes it return false if you pass a Symbol?

**Comment by bzbarsky** [comment]
The latter.  Any property name for which Type(P) is not string or the algorithm returns false is not an array index property name.

If there's a clearer way of phrasing this, happy to do that.

**Comment by annevk** [comment]
Making the type check the first step of the algorithm and confidently asserting that ToUint32 and ToString cannot throw with the ! convention from JavaScript would do the trick.

**Comment by annevk** [comment]
I tried to find out if we could reuse a definition from JavaScript directly, but https://tc39.github.io/ecma262/#sec-array-exotic-objects seems to have the bug that IDL does not and it's defined somewhat informatively.

**Comment by annevk** [comment]
Filed https://github.com/tc39/ecma262/issues/900.
