### ISSUE TITLE
Do specs need to handle the special value “missing” for dictionaries?

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#349]
In https://github.com/w3c/webrtc-pc/pull/1137, @taylor-b wrote "Let init be the second (dictionary) argument if present, or a default RTCDataChannelInit otherwise."

This is atypical, but I can't figure out why specs *don't* need to do this. https://heycam.github.io/webidl/#dfn-overload-resolution-algorithm is what converts ES arguments to IDL values, and uses the special value "missing" for arguments that have no default value. For trailing optional dictionaries, this is in step 14, "While i < argcount".

If the condition "If optionality is “optional” and V is undefined, then" were tweaked to exclude dictionaries then it would work as *I* assume it should.

**Comment by bzbarsky** [comment]
Trailing optional dictionaries always have a default value.  Under https://heycam.github.io/webidl/#idl-operations (not directly linkable, you have to  search for it), there's this text:

> If the type of an argument is a dictionary type or a union type that has a dictionary as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional. Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified.

**Comment by foolip** [comment]
I see, so it was addressed in there somewhere :) Thanks!
