### ISSUE TITLE
Consider renaming all legacy extended attributes

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#350]
I'm not sure this is worth the churn, but if we wanted to, let's do it all at once.

- LenientSetter -> LegacyLenientSetter
  - Used by fullscreen
- LenientThis -> LegacyLenientThis
   - Used by HTML
- NamedConstructor -> LegacyFactoryFunction https://github.com/heycam/webidl/issues/277
  - Used by HTML
- OverrideBuiltins -> LegacyOverrideBuiltins??
  - Used by HTML
- Replaceable -> LegacyReplaceable?
- TreatNonObjectAsNull -> LegacyTreatNonObjectAsNull
  - Used by HTML
- TreatNullAs=EmptyString -> LegacyNullToEmptyString (different naming scheme than LegacyTreatNonObjectAsNull since it operates on types, not callback functions)
  - Used by CSSOM, DOM Parsing, HTML, DOM
- Unforgeable -> LegacyUnforgeable???
  - Used by HTML, DOM

I have attached varying degrees of ?s for the ones I am unsure on.

**Comment by annevk** [comment]
In general I'm very much in favor of this and I think they all make sense. I'm a little worried where we have something we recommend, EventHandler, depend on something that we don't, [TreatNonObjectAsNull], as I wouldn't want folks to start ignoring EventHandler. I think that'll probably be okay in practice though.

**Comment by bzbarsky** [comment]
`Replaceable` is not legacy.  It's basically required for any new attribute we add on globals.  And even then it may not be enough; see https://bugzilla.mozilla.org/show_bug.cgi?id=1359022 for example.

**Comment by annevk** [comment]
If [Replaceable] is limited to globals it seems reasonable to keep it with the existing name.

**Comment by bzbarsky** [comment]
Hmm.  In Gecko, the only non-global use of Replaceable is `.stack` on `DOMException`.  Which is exciting for all sorts of reasons, not least because there is no mention of `.stack` in https://heycam.github.io/webidl/#es-exceptions

Of course there's no mention of it in ES either, for ES exceptions, but in practice browsers implement it (with non-identical semantics) and websites rely on it....

**Comment by annevk** [comment]
It sounds like we could limit it to globals in standards then and deal with stack once someone figures out what to do there (which likely will need to be defined in JavaScript-prose anyway given how we define DOMException today).

**Comment by TimothyGu** [comment]
Is this describing the same issue as #100? If so we should close one of them out.

**Comment by tobie** [comment]
> Is this describing the same issue as #100? If so we should close one of them out.

This issue seems specific to extended attributes.

**Comment by annevk** [comment]
Updated the title of #100.

**Comment by annevk** [comment]
I don't think we have any legitimate use cases for [Unforgeable] left. See also discussion over at https://github.com/w3c/webappsec-secure-contexts/issues/46 and https://github.com/whatwg/html/pull/2294.

**Comment by annevk** [comment]
I think we should rename OverrideBuiltins to LegacyOverrideBuiltIns (note the uppercase I). That makes us more consistent with JavaScript and HTML, which mostly say "built-in", not "builtin".
