### ISSUE TITLE
Throwing when converting detached ArrayBuffers is not what browsers do

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#352]
Test: https://jsbin.com/qusumat/edit?html,console

I will remove this in my upcoming [AllowShared] PR. I was already finding it weird that we threw for detached buffers, but not for detached typed arrays surrounding detached buffers.

**Comment by annevk** [comment]
Is JavaScript now aligned with implementations on ArrayBuffer around this? I believe some folks still tried to make them throw for more things.

**Comment by annevk** [comment]
Also note that for the APIs you tested browsers might not use IDL's copying infrastructure since that's not the option that yields the best performance.

**Comment by domenic** [comment]
> Is JavaScript now aligned with implementations on ArrayBuffer around this? I believe some folks still tried to make them throw for more things.

No. I thought we'd best remove any aspirational stuff at least for now, especially given the inconsistency.

> Also note that for the APIs you tested browsers might not use IDL's copying infrastructure since that's not the option that yields the best performance.

It's independent of the copy/reference; it should occur whenever converting a buffer source type to IDL, which happens before any algorithm steps.

**Comment by annevk** [comment]
So what happens instead, we'll just treat it as an empty buffer?

I guess what I'm wondering about is whether we should leave some kind of issue marker in for the aspirational stuff or whether everyone is down with just giving up.

**Comment by domenic** [comment]
Fixed by https://github.com/heycam/webidl/commit/c59bdcbcf2039c89eb7ea9a35e1e2dba621519ec
