### ISSUE TITLE
"::" is used in comments but is not formally a part of webidl ?

### ISSUE THREAD

**Issue by equalsJeffH** [heycam/webidl#354]
@mikewest used the "::" notation in some material he contributed to the [webuathn spec](https://w3c.github.io/webauthn/), but in webidl, "::" is used in comments but is not formally a part of webidl ?  

AFAICT, the webidl "::" notation was for [scopedName](https://www.w3.org/TR/2011/WD-WebIDL-20110712/#prod-ScopedName) which disappeared in the webidl WD following the [webidl Working Draft 12 July 2011](https://www.w3.org/TR/2011/WD-WebIDL-20110712/).

**Comment by domenic** [comment]
In Web IDL :: is used to define grammars. Is the webuathn spec defining grammars?

**Comment by mikewest** [comment]
I think this was just me accidentally being a C++ programmer, where `::` is part of the language. For programmers with my exact background, `InterfaceName::methodName()` is a pretty clear way of referring to `InterfaceName`'s `methodName()` method, but it's probably not at all clear to a JavaScript programmer.

Is this something for which it's worth defining a spelling? Or should we just type it out?

**Comment by annevk** [comment]
"ScopedCredential::[[DiscoverFromExternalSource]](options) method" so this is an internal slot that's an algorithm? I don't think there's much precedent for that (and certainly not with that notation). Usually we just define an operation of sorts that takes the instance as argument.

**Comment by tobie** [comment]
Coming from Ruby, I use `InterfaceName#methodName` to mean regular operations and  `InterfaceName.methodName` to mean static ones all the time. E.g.: `Array#forEach` vs. `Array.isArray`.

Would it be useful to formalize this?

**Comment by annevk** [comment]
I don't think so, since we rarely want to formally reference either of those. Specification algorithms need to use private endpoints, not public endpoints.

**Comment by tobie** [comment]
Alright, closing.

**Comment by tobie** [comment]
Thanks for bringing that up, though.
