### ISSUE TITLE
[EnforceRange] should normatively specify RangeError

### ISSUE THREAD

**Issue by rwaldron** [heycam/webidl#359]
`[EnforceRange]` includes the following: 

> If the [EnforceRange] extended attribute appears on one of the integer types, it creates a new IDL type such that that when an ECMAScript Number is converted to the IDL type, out-of-range values will cause an exception to be thrown

Ecma-262 defines [RangeError](https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard-rangeerror): 

> 19.5.5.2 RangeError
> Indicates a value that is not in the set or range of allowable values.

Presumably, that's what `[EnforceRange]` wants to do, but the examples shown say "TypeError", which is wrong because that's defined as:

> 19.5.5.5 TypeError
> TypeError is used to indicate an unsuccessful operation when none of the other NativeError objects are an appropriate indication of the failure cause.

This will have the added benefit of making specifications more testable (presently an implementation could throw any kind of error object it wanted).

**Comment by domenic** [comment]
I don't understand this, especially the claim that EnforceRange is not testable or can throw any error. Its behavior is normatively specified: 

> See the rules for converting ECMAScript values to the various IDL integer types in §3.2 ECMAScript type mapping for the specific requirements that the use of [EnforceRange] entails.

leads to https://heycam.github.io/webidl/#abstract-opdef-converttoint

> If the conversion is to an IDL type associated with the [EnforceRange] extended attribute, then:

which throws a TypeError.

Is this a change request to change it to RangeError? If so we can see if any implementers are interested in changing, but going from 4 interoperable implementations of the spec to 0 is not generally a popular move.

**Comment by rwaldron** [comment]
> especially the claim that EnforceRange is not testable or can throw any error. 
...
> which throws a TypeError.

When reading the spec and encountering ConvertToInt in the octet definition, I incorrectly assumed it would be semantically the same as `ToInteger` (which can only throw TypeError exception when ToNumber encounters a Symbol or ToPrimitive encounters an @@toPrimitive return value that's an object). Based on that incorrect assumption, it appeared that `[EnforceRange]` was under-specified, however it's clear now that it's just poorly specified—but specified nonetheless, and as such is not likely to be changed (I'm sure that doing so would break the web)


> Is this a change request to change it to RangeError?

The request would've been to specify that `[EnforceRange]` would throw a `RangeError`, because that's what RangeError is for, but I'm going to drop the issue in favor of the web.

**Comment by annevk** [comment]
Changing an exception is often doable, for what it's worth, but it has a fixed cost of updating all the tests and implementations.
