### ISSUE TITLE
Investigate removing [PrimaryGlobal] and requiring [Exposed]

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#365]
According to @annevk, it should be a relatively easy cleanup in the spec, but require lots of (easy) downstream changes.

[PrimaryGlobal] is a marker on the Window object that IDL fallbacks to when an interface is missing [Exposed].

Requiring [Exposed] on all interfaces would allow us to get rid of [PrimaryGlobal] and replace it with [Global].

**Comment by tobie** [comment]
See also: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26425

**Comment by tobie** [comment]
Seems from https://github.com/heycam/webidl/issues/420 that it would be worth flipping [SecureContext] over (e.g. to [AllowInNonSecureContext]) at the same time.

**Comment by annevk** [comment]
I think AllowInNonSecureContext would be nice, but I'm not sure about tightly coupling it with this. Is there agreement that we'd like to get rid of [PrimaryGlobal]? If so I'd be happy to start working on this at some point (adding annotations to various downstream specifications that is).

**Comment by tobie** [comment]
> I think AllowInNonSecureContext would be nice, but I'm not sure about tightly coupling it with this.

I think it makes sense to tie it to [Exposed], not sure how it relates to [PrimaryGlobal], tbh.

**Comment by annevk** [comment]
I mean I don't see a point in changing that at the same time.

**Comment by tobie** [comment]
Whereby "that" you mean you do **not** see a point of changing [PrimaryGlobal] together with either of [SecureContext] or [Exposed] at the same time, right?

So [SecureContext] and [Exposed] together makes sense and [PrimaryGlobal] by itself also does. Correct?

**Comment by annevk** [comment]
I created PRs for HTML and also for a thing I missed in DOM. DOM and other specifications I edit are already mostly accounted for since I've thought for a long time this is the way to go.

Also filed https://github.com/plinss/widlparser/issues/27 to start with displaying warnings to those not using [Exposed].

**Comment by tobie** [comment]
Started working on a WebIDL PR for this. Should be able to push it later tonight or tomorrow.

**Comment by dontcallmedom** [comment]
in case this helps, I ran a custom report on the [WebIDL crawl](https://github.com/tidoust/reffy-reports/blob/master/whatwg/crawl.json) made by our [Reffy tool](https://github.com/tidoust/reffy/), and found the following specs / interfaces that are neither `Exposed` nor `NoInterfaceObject`:
## Specifications that defined WebIDL interfaces that are neither Exposed nor NoInterfaceObject

- [Accelerometer](https://w3c.github.io/accelerometer/): Accelerometer, LinearAccelerationSensor, GravitySensor
- [Ambient Light Sensor](https://w3c.github.io/ambient-light/): AmbientLightSensor
- [Battery Status API](https://w3c.github.io/battery/): BatteryManager
- [Clipboard API and events](https://w3c.github.io/clipboard-apis/): ClipboardEvent, Clipboard
- [Content Security Policy Level 3](https://w3c.github.io/webappsec-csp/): SecurityPolicyViolationEvent
- [Cooperative Scheduling of Background Tasks](https://w3c.github.io/requestidlecallback/): IdleDeadline
- [CSS Object Model (CSSOM)](https://drafts.csswg.org/cssom/): MediaList, StyleSheet, CSSStyleSheet, StyleSheetList, CSSRuleList, CSSRule, CSSStyleRule, CSSImportRule, CSSGroupingRule, CSSPageRule, CSSMarginRule, CSSNamespaceRule, CSSStyleDeclaration, CSS
- [CSS Pseudo-Elements Module Level 4](https://drafts.csswg.org/css-pseudo-4/): CSSPseudoElement, CSSPseudoElementList
- [CSS Typed OM Level 1](https://drafts.css-houdini.org/css-typed-om-1/): CSSStyleValue, StylePropertyMapReadOnly, StylePropertyMap, CSSUnparsedValue, CSSVariableReferenceValue, CSSKeywordValue, CSSNumericValue, CSSUnitValue, CSSMathValue, CSSMathSum, CSSMathProduct, CSSMathNegate, CSSMathInvert, CSSMathMin, CSSMathMax, CSSNumericArray, CSSTransformValue, CSSTransformComponent, CSSTranslation, CSSRotation, CSSScale, CSSSkew, CSSPerspective, CSSMatrixComponent, CSSPositionValue, CSSResourceValue, CSSImageValue, CSSURLImageValue, CSSFontFaceValue
- [CSSOM View Module](https://drafts.csswg.org/cssom-view/): MediaQueryList, MediaQueryListEvent, Screen, CaretPosition
- [DeviceOrientation Event Specification](https://w3c.github.io/deviceorientation/spec-source-orientation.html): DeviceOrientationEvent, DeviceMotionEvent
- [DOM Parsing and Serialization](https://w3c.github.io/DOM-Parsing/): DOMParser, XMLSerializer
- [DOM Standard](https://dom.spec.whatwg.org/): MutationObserver
- [Element Traversal Specification](http://www.w3.org/TR/2008/REC-ElementTraversal-20081222/): ElementTraversal
- [Encrypted Media Extensions](https://w3c.github.io/encrypted-media/): MediaKeySystemAccess, MediaKeys, MediaKeySession, MediaKeyStatusMap, MediaKeyMessageEvent, MediaEncryptedEvent
- [Gamepad](https://w3c.github.io/gamepad/): Gamepad, GamepadButton, GamepadEvent
- [Generic Sensor API](https://w3c.github.io/sensors/): Sensor, SensorErrorEvent
- [Gyroscope](https://w3c.github.io/gyroscope/): Gyroscope
- [HTML Standard](https://html.spec.whatwg.org/): RadioNodeList, HTMLUnknownElement, AudioTrack, VideoTrackList, VideoTrack, CanvasRenderingContext2D, Window
- [Magnetometer](https://w3c.github.io/magnetometer/): Magnetometer, UncalibratedMagnetometer
- [Media Capture and Streams](https://w3c.github.io/mediacapture-main/): InputDeviceInfo
- [Media Capture from DOM Elements](https://w3c.github.io/mediacapture-fromelement/): CanvasCaptureMediaStreamTrack
- [Media Source Extensions™](https://w3c.github.io/media-source/): MediaSource, SourceBuffer, SourceBufferList
- [MediaStream Image Capture](https://w3c.github.io/mediacapture-image/): ImageCapture, PhotoCapabilities, MediaSettingsRange
- [MediaStream Recording](https://w3c.github.io/mediacapture-record/): MediaRecorder, BlobEvent
- [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/): PerformanceNavigationTiming
- [Orientation Sensor](https://w3c.github.io/orientation-sensor/): OrientationSensor, AbsoluteOrientationSensor, RelativeOrientationSensor
- [Payment Handler API](https://w3c.github.io/payment-handler/): PaymentInstruments
- [Payment Request API](https://w3c.github.io/payment-request/): PaymentRequest, PaymentAddress, PaymentResponse, PaymentRequestUpdateEvent
- [Pointer Events - Level 2](https://w3c.github.io/pointerevents/): PointerEvent
- [Presentation API](https://w3c.github.io/presentation-api/): Presentation, PresentationRequest, PresentationAvailability, PresentationConnectionAvailableEvent, PresentationConnection, PresentationConnectionCloseEvent, PresentationReceiver, PresentationConnectionList
- [Proximity Sensor](https://w3c.github.io/proximity/): ProximitySensor
- [Remote Playback API](https://w3c.github.io/remote-playback/): RemotePlayback
- [Scalable Vector Graphics (SVG) 2](https://svgwg.org/svg2-draft/): SVGElement, SVGGraphicsElement, SVGGeometryElement, SVGNumber, SVGLength, SVGAngle, SVGNameList, SVGNumberList, SVGLengthList, SVGAnimatedBoolean, SVGAnimatedEnumeration, SVGAnimatedInteger, SVGAnimatedNumber, SVGAnimatedLength, SVGAnimatedAngle, SVGAnimatedString, SVGAnimatedRect, SVGAnimatedNumberList, SVGAnimatedLengthList, SVGStringList, SVGUnitTypes, SVGSVGElement, SVGGElement, SVGUnknownElement, SVGDefsElement, SVGDescElement, SVGMetadataElement, SVGTitleElement, SVGSymbolElement, SVGUseElement, SVGUseElementShadowRoot, ShadowAnimation, SVGSwitchElement, SVGStyleElement, SVGTransform, SVGTransformList, SVGAnimatedTransformList, SVGPreserveAspectRatio, SVGAnimatedPreserveAspectRatio, SVGPathElement, SVGRectElement, SVGCircleElement, SVGEllipseElement, SVGLineElement, SVGMeshElement, SVGPointList, SVGPolylineElement, SVGPolygonElement, SVGTextContentElement, SVGTextPositioningElement, SVGTextElement, SVGTSpanElement, SVGTextPathElement, SVGImageElement, SVGForeignObjectElement, SVGMarkerElement, SVGSolidcolorElement, SVGGradientElement, SVGLinearGradientElement, SVGRadialGradientElement, SVGMeshGradientElement, SVGMeshrowElement, SVGMeshpatchElement, SVGStopElement, SVGPatternElement, SVGHatchElement, SVGHatchpathElement, SVGCursorElement, SVGScriptElement, SVGAElement, SVGViewElement
- [Selection API](https://w3c.github.io/selection-api/): Selection
- [Static Range](https://w3c.github.io/staticrange/): StaticRange
- [The Screen Orientation API](https://w3c.github.io/screen-orientation/): ScreenOrientation
- [Touch Events - Level 2](http://dvcs.w3.org/hg/webevents/raw-file/v1/touchevents.html): Touch, TouchList, TouchEvent
- [UI Events](https://www.w3.org/TR/uievents): UIEvent, FocusEvent, MouseEvent, WheelEvent, InputEvent, KeyboardEvent, CompositionEvent
- [Wake Lock API](https://w3c.github.io/wake-lock/): WakeLock, WakeLockRequest
- [Web App Manifest](https://www.w3.org/TR/2017/WD-appmanifest-20170905/): BeforeInstallPromptEvent
- [Web Authentication: An API for accessing Public Key Credentials - Level 1](https://w3c.github.io/webauthn/): PublicKeyCredential, AuthenticatorResponse, AuthenticatorAttestationResponse, AuthenticatorAssertionResponse
- [WebGL 2.0 Specification](https://www.khronos.org/registry/webgl/specs/latest/2.0/): WebGLQuery, WebGLSampler, WebGLSync, WebGLTransformFeedback, WebGLVertexArrayObject, WebGL2RenderingContext
- [WebGL Specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/): WebGLObject, WebGLBuffer, WebGLFramebuffer, WebGLProgram, WebGLRenderbuffer, WebGLShader, WebGLTexture, WebGLUniformLocation, WebGLActiveInfo, WebGLShaderPrecisionFormat, WebGLRenderingContext, WebGLContextEvent
- [WebRTC 1.0: Real-time Communication Between Browsers](https://w3c.github.io/webrtc-pc/): RTCPeerConnection, RTCSessionDescription, RTCIceCandidate, RTCPeerConnectionIceEvent, RTCPeerConnectionIceErrorEvent, RTCCertificate, RTCRtpSender, RTCRtpReceiver, RTCRtpContributingSource, RTCRtpSynchronizationSource, RTCRtpTransceiver, RTCDtlsTransport, RTCIceTransport, RTCTrackEvent, RTCSctpTransport, RTCDataChannel, RTCDataChannelEvent, RTCDTMFSender, RTCDTMFToneChangeEvent, RTCStatsReport, RTCIdentityAssertion
- [Worklets Level 1](https://drafts.css-houdini.org/worklets/): Worklet

**Comment by annevk** [comment]
That's amazing, thanks!

**Comment by annevk** [comment]
@dontcallmedom https://www.w3.org/TR/ElementTraversal/ should be marked obsolete somehow.

**Comment by SaschaNaz** [comment]
Web Speech API also need a fix, but it hasn't been updated for years :/ https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html#speechreco-event

**Comment by annevk** [comment]
@SaschaNaz I filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=30178.

**Comment by snuggs** [comment]
@annevk @dontcallmedom should this treatment also be done to `MediaRecorder`? Or does `MediaCapture` take care of this. I noticed `mediacapture-image` and `mediacapture-fromelement` were addressed but not the recorder _(fairly important)_.

**Comment by annevk** [comment]
@snuggs everything in the form `interface X { }` needs this. I recommend filing bugs when you see it's not there.

**Comment by dontcallmedom** [comment]
@snuggs I thought I had file a pull request for it, but apparently not; now done https://github.com/w3c/mediacapture-record/pull/136

**Comment by marcoscaceres** [comment]
Payment Request is done, but can't tick the box.

**Comment by annevk** [comment]
All boxes ticked.

**Comment by garykac** [comment]
For Constructors, I usually see is as:
`[Constructor(...), Exposed=Window]`

But sometimes (eg: in [webvr](https://github.com/dontcallmedom/webvr/commit/d57be524c1b6c8acc6f71afcc3e923f50d388f13)) it is:
`[Exposed=Window, Constructor(...)]`

Do we want to be consistent with placing this annotation at the end, or does it not matter?

**Comment by bzbarsky** [comment]
It doesn't really matter; extended attributes form an unordered set.

**Comment by SaschaNaz** [comment]
Dictionaries also need Exposed, right? https://encoding.spec.whatwg.org/#interface-textdecoder

```WebIDL
dictionary TextDecoderOptions {
  boolean fatal = false;
  boolean ignoreBOM = false;
};

dictionary TextDecodeOptions {
  boolean stream = false;
};
```
