### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [heycam/webidl#369]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by domenic** [comment]
@tobie, @bzbarsky, any thoughts? It seems to me we're still working through a backlog of things from last TPAC; @tobie and I have been working through a pretty well-defined list of large/medium/small tasks. I'm not sure we'd need more dedicated time this year.

**Comment by tobie** [comment]
Yeah, we still have a lot of material from last year's breakout session. I don't think doing one this year would be super useful.

I'm not sure whether I'll be at TPAC this year, but I'm happy to give the WG a quick update if I am. Unfortunately, I won't be able to confirm my presence for a while.

**Comment by bzbarsky** [comment]
I'm pretty sure I will _not_ be able to make TPAC this year.  I've also not been very actively involved in the editing activity, so don't know that I'd have much to contribute.

I agree we have enough work items that a breakout session is not likely to be useful, though if people have issues they should raise them.  One issue I know is outstanding is Tab's concerns about typed arraylikes, though I'd hope we decide something there before TPAC.

**Comment by LJWatson** [comment]
Thanks domenic, @tobie, and @bzbarsky. A quick update would be welcome if you're there @tobie, I'll throw 15 mins into the schedule as a placeholder for now.
