### ISSUE TITLE
Serializable types should include unrestricted double and unrestricted float

### ISSUE THREAD

**Issue by samweinig** [heycam/webidl#370]
Currently, the list of serializable types (https://heycam.github.io/webidl/#dfn-serializable-type) does not include **unrestricted double** and **unrestricted float**.  Specs are relying on them being serializable (see https://drafts.fxtf.org/geometry-1/#dompointreadonly for an example), so it would probably make sense to add.

**Comment by domenic** [comment]
This appears to be fixed by #323:

https://s3.amazonaws.com/pr-preview/tobie/webidl/tojson.html#dfn-json-types
