### ISSUE TITLE
Improvements to downstream tracking

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#379]
We experimented with being much more thorough and organized at filing bugs downstream, notifying browser vendors, WebIDL parsers, idlharness, wpt and affected specs.

Overall, I'm super pleased with the outcome of the outreach. It's great to see changes in the spec being adopted so quickly downstream. It's also really nice to get feedback and questions from editors on how they're handling the changes. Ultimately, I hope this also makes WebIDL more approachable and helps build a tighter community around spec editing.

Unfortunately, this increased velocity has also caused some casualties, notably within the perf WG, which saw a number of its EDs stop rendering when ReSpec was updated (see the thread here: https://github.com/w3c/resource-timing/issues/112).

Although this is essentially a ReSpec issue, it would be nice to see how we can avoid that in the future and if there are other improvements that can be made here.

**Comment by marcoscaceres** [comment]
I don't have a strong opinion. How did BikeShed handle it? Did @tabatkins also just yank support? 

I know it's not a very popular solution, but forcing breakage does light fires and swings the community into action (e.g., I sent a PR to fix w3c/resource-timing#112).

**Comment by tobie** [comment]
Im not sure about Bikeshed. It's less of an issue, though, as it can't really break EDs the way a change to ReSpec does.

**Comment by marcoscaceres** [comment]
why is that? Doesn't the IDL parser throw?

**Comment by tobie** [comment]
Sorry, I meant it can't break *published* EDs (by virtue of requiring a server-side build step).

**Comment by marcoscaceres** [comment]
note that ReSpec doesn't break either - it just surfaces the IDL parser error, but the content remains accessible to end-users (but I can't generate the hyperlinks, etc.).

ok, so it's the same as ReSpec with that regard.

**Comment by tabatkins** [comment]
Yeah, Bikeshed just yanked support, via widlparser updating.  It shows up as a fatal error in your IDL now, and prevents that IDL block from getting parsed/hyperlinked/dfn'd.

**Comment by tobie** [comment]
Alright, so it seems is issue was breaking _published_ spec using ReSpec. Seems like this is something for @marcoscaceres and team to handle. Closing here. Feel free to reopen or file a new issue if something comes up.
