### ISSUE TITLE
Dictionary members' "present" definition seems circular

### ISSUE THREAD

**Issue by jan-ivar** [heycam/webidl#381]
[2.4 Dictionaries](https://heycam.github.io/webidl/#dfn-inherited-dictionaries) sets up a *dictionary* internally as an [ordered map](https://infra.spec.whatwg.org/#ordered-map) of [entries](https://infra.spec.whatwg.org/#map-entry).

So shouldn't the definition of [present](https://heycam.github.io/webidl/#dfn-present) be based on [exists](https://infra.spec.whatwg.org/#map-exists)?

The current definition seems circular: *"A dictionary value of type D can have key–value pairs corresponding to the dictionary members defined on D and on any of D’s inherited dictionaries. On a given dictionary value, the presence of each dictionary member is optional, unless that member is specified as required. When specified in the dictionary value, a dictionary member is said to be* ***present***, *otherwise it is* ***not present***."

It uses *"presence"* ahead of defining **present**, and the word *"specified"* sounds like we're trying to avoid saying "present" again, but I think it's the wrong word, as presence doesn't seem to rely on specification. Chicken and egg.

The **present** definition seems used both on input and output:

1. "In the ECMAScript binding, a value of undefined is treated as not present,"
2. "If the dictionary member named key is present in V, then:"

**Comment by bzbarsky** [comment]
I think the current language might predate the definition in terms of ordered map.  I agree that defining "present" in terms of https://infra.spec.whatwg.org/#map-exists makes sense.
