### ISSUE TITLE
Does the "required" dictionary member keyword affect output?

### ISSUE THREAD

**Issue by jan-ivar** [heycam/webidl#382]
I'm trying to figure out the scope of `required` and `=` default values and whether they apply only to input "values" or to (internally created values and thus) output "values" as well.

At first glance both would seem to only affect input, not output, as they're only referenced in the [ECMAScript value to IDL dictionary](https://heycam.github.io/webidl/#es-dictionary) algorithm, but not in the [IDL dictionary to ECMAScript Object](https://heycam.github.io/webidl/#es-dictionary) algorithm (scroll down in link).

But I learned [a while ago](https://github.com/w3c/mediacapture-main/issues/293#issuecomment-169040860) that at least default values impact output, at least in our webidl compiler, and that the spec at least [implies it](https://github.com/w3c/mediacapture-main/issues/293#issuecomment-169603863) through: *"Dictionary members with default values are always considered to be present."*

Similarly, it says about the `required` keyword: *"If the type of the dictionary member is preceded by the required keyword, the member is considered a required dictionary member and must be present on the dictionary."*

Both hinge on the definition of "present". Present only on input, or internal invariant? I've filed https://github.com/heycam/webidl/issues/381 for clarification.

AFAICT our WebIDL compiler does not do anything to enforce presence of "required" internal values when output, but I wanted some spec clarification. This came up in https://github.com/w3c/webrtc-pc/issues/1476 where people are considering using `required` on output-only dictionaries as a form of normative implementation implication. That may be a good or bad idea on its own, and I have opinions on such an overload, but it comes down to how WebIDL views `required`, what the intent was, and what we might expect WebIDL compilers to enforce in the future.

**Comment by annevk** [comment]
Dictionaries as return values haven't been comprehensively considered thus far I think. Ultimately the requirement for what to return comes from the prose (except I guess for default values, if clarified as such), but I guess using required as well can serve as a useful reminder.

**Comment by domenic** [comment]
required and default values only apply to the input side of dictionaries. That is the only place where they have normative impact in the Web IDL specifications. Remember "present" is not some kind of requirement on the IDL compiler; it's just something specs can use to write spec-code like "If "key" is present in dictionary, then...".

In general, IDL return values are always documentation, and the prose that does the returning is what governs what is actually returned.

**Comment by bzbarsky** [comment]
Here's the way I think of it.  `required` is a restriction on the data model of the dictionary.  A dictionary with a `required` member cannot be instantiated, conceptually, without that member being present.

This has implications for the ES-to-dictionary conversion, of course.  But it also has implications for the dictionary-to-ES conversion, in that you know that property will exist on the resulting object.

I don't know whether we need to explicitly describe "valid" vs "invalid" dictionaries or something...  The only "invalid" ones would be dictionaries with `required` members that are in the middle of being created via <https://heycam.github.io/webidl/#es-to-dictionary> or dictionaries with `required` members that spec prose creates without defining values for those members.  Converting an "invalid" dictionary to ES would not be possible.

Similarly, a dictionary that has a member with a default value will always have that member present, conceptually. 

> Both hinge on the definition of "present".

I think the right thing here is to have the "present" in the spec bits you quoted mean "internal invariant".

How this internal invariant is maintained is a bit less clear.  Nothing at the moment really prevents a specification from creating an "invalid" dictionary in the sense described above.  In terms of implementation, at least Gecko handles it as follows: the internal representation assumes there is a value for every required or defaulted property, on from-ES conversion the bindings enforce the existence of a value, on to-ES conversion the bindings assume the relevant member of the C++ struct has been properly initialized.  It's possible for this last to fail if the C++ programmer messes up...

> AFAICT our WebIDL compiler does not do anything to enforce presence of "required" internal values when output

Right, this is the "C++ programmer messes up" case.  What it will do is try to convert uninitialized memory to an ES value and chances are hilarity of the "random output, crashes, etc" sort will ensue.  But that's an implementation detail.  We could just as easily have made the concept of "valid" vs "invalid" explicit in Gecko's C++ dictionary implementation and made to-ES conversion fail for dictionaries with uninitialized required members....  This isn't really an IDL spec issue.

> where people are considering using required on output-only dictionaries as a form of normative implementation implication.

This seems pretty reasonable to me, fwiw.

> and what we might expect WebIDL compilers to enforce in the future.

That's an implementation detail that shouldn't be relevant here, imo.

> Ultimately the requirement for what to return comes from the prose

Well, a combination of the dictionary definition and the prose, right?  The prose says what things are present in the map; the dictionary definition defines how to convert that map to ES.

> required and default values only apply to the input side of dictionaries. 

In terms of normative steps in IDL, yes, but in terms of conceptual model I believe they apply to the dictionary type itself, per above.

**Comment by tobie** [comment]
Closed. Feel free to reopen if you need further clarifications on something.
