### ISSUE TITLE
Strict type checking in WebIDL

### ISSUE THREAD

**Issue by soareschen** [heycam/webidl#383]
Due to legacy behaviors of JavaScript, WebIDL has a lot of conversion rules processing its arguments, e.g. any object with `toString()` can be passed as argument to methods accepting `DOMString`.

While I understand the rationale of existing implementation having this behavior, wouldn't it make sense for new specs being developed to have stricter type checking on their methods? e.g. methods accepting `DOMString` should throw `TypeError` if `typeof obj !== 'string'`.

This could be defined as extended attribute at the interface or method level so that it doesn't affect existing specs.

**Comment by annevk** [comment]
Can you justify the request via some kind of use case or goal? JavaScript's "standard library" has the same kind of conversion behavior for string arguments. It's not entirely clear why we'd diverse.

**Comment by bzbarsky** [comment]
> e.g. methods accepting DOMString should throw TypeError if typeof obj !== 'string'

I think people would be pretty surprised if they can't pass an ES `String` for a `DOMString` argument.

But also, as annevk points out, this is normal behavior for ES, including the ES spec builtins.

**Comment by domenic** [comment]
Is the proposal here that all APIs designed after 2017-07 start throwing for various inputs, and all APIs designed before then behave like the rest of JavaScript?

Let's not do that.

**Comment by soareschen** [comment]
String is just one of the examples, and the exact approach and rules can be up for discussion. I just want to see if there is any interest in similar stricter type checking improvement. 

I think passing arguments of the wrong type to APIs is often unintentional and is a source of bugs, so it is better to throw error instead of silently coercing it. The rationale is similar to `[EnforceRange]`, where it allows modern APIs to throw certain class of errors that are originally ignored.

If augmenting the behavior of existing types through extended attribute is undesirable, then perhaps an approach similar to #33 can be used to introduce new types that have simpler type checking / coercion rules?

**Comment by domenic** [comment]
I don't think there is interest in this, no.

If you personally are interested in this for your code, I suggest using something like TypeScript.

**Comment by soareschen** [comment]
Got it then. At least it is good to know. Closing this issue.
