### ISSUE TITLE
Define a [[OwnPropertyKeys]] for legacy platform objects

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#400]
Consider the following JS snippet:

```js
(() => {
  const element = document.createElement("div");
  element.setAttribute("length", "len_val");
  element.setAttribute("unrestricted", "unr_val");
  element.attributes.ownProp = 'own prop';
  console.log(Reflect.ownKeys(element.attributes));
  console.log(Object.keys(element.attributes));
  console.log(element.attributes.hasOwnProperty("unrestricted"));
  console.log(element.attributes.unrestricted);
})();
```

On Chrome this emits:

```js
["0", "1", "ownProp"]
["0", "1", "ownProp"]
true
unrestricted=​"unr_val"
```

while on Firefox it shows:

```js
[ "0", "1", "unrestricted", "ownProp" ]
[ "0", "1", "ownProp" ]
true 
unrestricted="unr_val"
```

Though it is not defined as an [invariant](https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods) in ECMAScript, it would still seem a good idea to bring Firefox's behavior into the standard, as one would expect an own property according to `hasOwnProperty` to be in the `ownKeys` of that object.

Web IDL does already define [property enumeration](https://heycam.github.io/webidl/#legacy-platform-object-property-enumeration) orders for enumerable properties, but this specific issue concerns *all* keys, not only those that are enumerable. And the way to specify that is by imperatively defining an [[OwnPropertyKeys]] internal method, like ES's built-in [OrdinaryOwnPropertyKeys](https://tc39.github.io/ecma262/#sec-ordinaryownpropertykeys) abstract op.

FWIW, both Chrome and Firefox's `Object.keys` return the correct properties according to the spec. `element.attributes`'s type `NamedNodeMap` is defined with [`LegacyUnenumerableNamedProperties`], so none of those named properties are enumerable.

**Comment by annevk** [comment]
Note that as per https://github.com/tc39/ecma262/pull/833 we should also call it out as a specification error if we end up with duplicate entries somehow. (Maybe an Assert?)

**Comment by TimothyGu** [comment]
Sure, or we can just make it a named set (in Infra terminology).

**Comment by annevk** [comment]
By the way, how does this relate to #79?

**Comment by TimothyGu** [comment]
@annevk They are same issue as far as I can tell, but this one asks for a normative change while that one is more of an editorial nature.
