### ISSUE TITLE
Use ES Completion records consistently

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#403]
Abstract operations defined in ECMAScript return a Completion record. But as far as I can tell, abstract ops in the platform don't have this mechanism, simply relying on common sense for any abrupt completions. This spec does not use the ES `?` and `!` shorthands consistently when calling into ES-defined abstract ops, nor does it return Completion records for hooks into ES like internal methods for legacy platform objects. We should probably fix both of them, the latter perhaps by linking "Return" in those abstract ops to the corresponding definition in ES ("Return *value*. -> "Return NormalCompletion(*value*).")

**Comment by domenic** [comment]
> ("Return value. -> "Return NormalCompletion(value).")

This is actually a no-op in ES, because in ES you are allowed to interpret implicit "return _x_" as returning a normal completion for _x_.

In general, see https://heycam.github.io/webidl/#conventions bottom three paragraphs. I'm not sure if there's actually a problem here.

**Comment by TimothyGu** [comment]
Now that I've read the Conventions chapter I don't think this is as big of an issue. Still good to be consistent though.
