### ISSUE TITLE
Decide whether to use emu-val for ES types

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#404]
In ES spec, "Object" "Function" "Symbol" etc. are never wrapped in emu-val (which is reserved for special constants like **undefined**, **true** and **false**). In Web IDL though it's common to see them bolded through emu-val, but also unbolded in other places. Example of a section that uses both styles simultaneously: https://heycam.github.io/webidl/#es-object

We should decide which style to use and then apply it to the entire document.

**Comment by annevk** [comment]
I'd be happy to align with ES. The alternative is aligning with HTML, although I'm not sure if that's entirely consistent with itself either...

**Comment by TimothyGu** [comment]
FWIW HTML doesn't use bold type for ES types either. E.g. https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal.
