### ISSUE TITLE
[[Construct]] for legacy platform objects?

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#407]
On a page with `#title`:

```js
new document.all('title')
```

In Chrome the snippet returns the same result as `document.all('title')`, while on Firefox the following error is thrown:

```
TypeError: document.all is not a constructor
```

[[Construct]] is technically undefined by this spec right now, so either behavior is strictly speaking acceptable. However, the Chrome behavior doesn't make much sense to me, so I'd like to propose a dedicated section for [[Construct]] saying that it does not exist for legacy platform objects.

**Comment by domenic** [comment]
I'm not sure document.all() is your best test case for "legacy platform objects" in general, given how weird it is. That said, you have indeed discovered an interop problem we should fix, one way or another.

I think implicitly legacy platform objects are "based on" normal non-exotic objects and "inherit" their internal methods (or lack thereof), so there should be no [[Call]]/[[Construct]]. But I guess that is not stated anywhere? Cf. the last sentence in the intro to https://tc39.github.io/ecma262/#sec-bound-function-exotic-objects

**Comment by annevk** [comment]
This seems like a good thing to make sure https://github.com/tc39/ecma262/pull/673 covers and gets tested somewhere (probably HTML test suite?).

**Comment by tobie** [comment]
> I think implicitly legacy platform objects are "based on" normal non-exotic objects and "inherit" their internal methods (or lack thereof), so there should be no [[Call]]/[[Construct]].

Agreed. Unless specifically defined, [[Construct]] shouldn't be there.
