### ISSUE TITLE
[[Call]] for objects w/o legacycaller

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#408]
For legacy platform objects w/o any legacy callers, the [[Call]] internal method [immediately](https://heycam.github.io/webidl/#legacy-platform-object-call) throws a TypeError. Unfortunately, the mere fact that [[Call]] is defined can cause certain issues, like the object being treated as [callable](https://tc39.github.io/ecma262/#sec-iscallable) by ES, and [`typeof` operator](https://tc39.github.io/ecma262/#sec-typeof-operator) returning "function".

**Comment by domenic** [comment]
Wow, great catch.

I think a short-term fix is to add a prelude stating that it only exists for objects with legacy callers.

Longer-term we may want to consider creating a new type of object, "callable legacy platform objects", which have the same internal methods as legacy platform objects + [[Call]]. I remember we discussed that back in https://github.com/heycam/webidl/issues/202 but didn't go with it...

**Comment by annevk** [comment]
In discussing this with @tobie we realized that HTMLAllCollection is the only place that uses this. We might just want to move the `[[Call]]` algorithm to HTML and get rid of `legacycaller` in IDL.

**Comment by tobie** [comment]
And here's the PR for HTML: https://github.com/whatwg/html/pull/2932
