### ISSUE TITLE
Explain why array index property names cannot be 2^32 - 1

### ISSUE THREAD

**Issue by ayg** [heycam/webidl#409]
https://github.com/heycam/webidl/blob/d76a9c24901a9734374e8fd9fe790307c3f3989f/index.bs#L12047

It seems pretty mysterious.  A note in the spec would be helpful.  I tried tracing it via blame, but got back to b7e3bf2b and gave up.

**Comment by TimothyGu** [comment]
Because it's defined in this way in ECMAScript is what I'm guessing:

> An *integer index* is a String-valued property key that is a canonical numeric String (see [7.1.16](https://tc39.github.io/ecma262/#sec-canonicalnumericindexstring)) and whose numeric value is either **+0** or a positive integer ≤ 2<sup>53</sup> − 1. An array index is an integer index whose numeric value *i* is in the range +0 ≤ *i* < 2<sup>32</sup> − 1.
>
> Per https://tc39.github.io/ecma262/#sec-object-type

And the reason why it's defined this way is probably because of this clause:

> Every Array object has a `length` property whose value is always a nonnegative integer less than 2<sup>32</sup>. 
>
> Per https://tc39.github.io/ecma262/#sec-array-exotic-objects

If the index of the last element of an array is 2<sup>32</sup> − 1, then the length of that array would be exactly 2<sup>32</sup>.

**Comment by annevk** [comment]
See also https://github.com/tc39/ecma262/issues/900. Ideally we'd have this only defined in ECMAScript and IDL would just reference that.

**Comment by tobie** [comment]
I guess we should just send a PR to the ES spec to add a dfn + id to _array index_ as defined in  https://tc39.github.io/ecma262/#sec-object-type and then link to it from a note here.

**Comment by tobie** [comment]
https://tc39.github.io/ecma262/#array-index is now a thing.
