### ISSUE TITLE
"Handling exceptions" section in ES contains outdated information

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#414]
https://heycam.github.io/webidl/#es-handling-exceptions says:

> None of the algorithms or processing requirements in the ECMAScript language binding catch ECMAScript exceptions.

But it is not so in [attribute getter](https://heycam.github.io/webidl/#dfn-attribute-getter)'s definition:

> ...
> And then, if an exception was thrown:
>
> 1. If op has a return type that is a promise type, then:
>     ...
> 2. Otherwise, end these steps and allow the exception to propagate.

**Comment by domenic** [comment]
What a weird section. I'm unsure whether it should even exist. I guess maybe the examples are helpful...

In any case, it should probably defer to https://infra.spec.whatwg.org/#algorithm-control-flow and maybe talk a bit about the stuff in the conventions section about abrupt completions/throwing.
