### ISSUE TITLE
explicitly invoke [[HasOwnProperty]], [[GetProperyOf]], etc. more often

### ISSUE THREAD

**Issue by heycam** [heycam/webidl#42]
There are many instances in the spec where it says something like "If _O_ has an own property with name _P_, then ...".  Given proxies, we really should be invoking [[HasOwnProperty]] here explicitly, because we'll want to be clear that the proxy handler is invoked.  (And it's not really clear whether a proxy has "real" own properties anyway.)

**Comment by annevk** [comment]
As discussed in #601 this is not the behavior we want.
