### ISSUE TITLE
Dictionaries and [Constructor], [Exposed], [SecureContext]

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#422]
I hope "The following extended attributes are applicable to dictionaries: [Constructor], [Exposed], [SecureContext]," is a bug for something that was considered at some point and abandoned. Either we should confirm that or just remove it and ensure implementations don't accept it.

**Comment by tobie** [comment]
[Exposed] was added to dictionaries when [Exposed] [was introduced](https://github.com/heycam/webidl/commit/b38006ce3682fc07c1be52a49130bea5e42e7c78#diff-7323624b83e1dea8ba3cdf1fdfeb8d5cL4193), which makes sense as Dictionaries had a constructor back then. Pretty sure the same can be said of [SecureContext].

**Comment by annevk** [comment]
Ah okay so constructor functionality was explicitly removed at some point? If so then I think you can go ahead and merge this.

**Comment by tobie** [comment]
> Ah okay so constructor functionality was explicitly removed at some point? If so then I think you can go ahead and merge this.

Well, I haven't seen any bindings for dictionary constructors, nor an mention of dictionary constructors anywhere in the spec, so I _assume_ they're gone.
