### ISSUE TITLE
A "duplicate Id" DOM Exception? 

### ISSUE THREAD

**Issue by marcoscaceres** [heycam/webidl#428]
In the Payment Request spec, I have a situation where I need to check if an id exists and throw a DOMException of some sort. 

I noticed that IDB is using "ConstraintError": 

> A mutation operation in a transaction failed because a constraint was not satisfied.

But the above description is overly specific for my case. I wonder if we should reword the above to be less databasey?

Same applies to "VersionError":  

> An attempt was made to open a database using a lower version than the existing version. 

should probably drop the word database, because it could, in theory apply to a any kind of versioned data store.

Anyway, I'm happy to use "ConstraintError" but I'm wonder if maybe we could have a "NotUniqueError" or "DuplicateId" error? It feels like a common thing.

**Comment by annevk** [comment]
Would you expect the caller to branch on the exception?

**Comment by marcoscaceres** [comment]
Depends on the API I guess... if you have an UI to create a database, or to input a field, then yes (because you could ask the user to correct the error)... In my case, it's a fatal error - the developer provided two options that were the same, and the browser can't honor that whatever reason.

**Comment by marcoscaceres** [comment]
I went with ConstraintError, but can change it to TypeError - but I'd like to understand what the heuristic is for deciding to use TypeError. Above you seemed to use some kind of logic: if "x" then use TypeError. 

What is "x" that I missed? Was it about being able to recover?

**Comment by annevk** [comment]
ECMAScript itself almost always uses TypeError. The rough rationale being that callers don't branch on exception type but rather avoid making things throw.

**Comment by domenic** [comment]
Yes, TypeError sounds much better in this case, if you believe it's a fatal error.

**Comment by domenic** [comment]
Also, in general TypeError is correct for "the argument is not valid" even if the validity check is "something with that ID already exists".

**Comment by marcoscaceres** [comment]
Thanks you both for clarifying. Will switch to TypeError.
