### ISSUE TITLE
We may want to suport constants on namespaces

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#440]
I don't see an obvious reason to not support them, and they can be useful in some cases, I'd think.

**Comment by domenic** [comment]
Well, in general constants are somewhat legacy, as mostly they're replaced by enums. I agree that if we have a concrete use case for numerical constants constrained to a namespace (like ES's Math.PI) then we should add them, but it seems better to wait until we have such a concrete use case. Did you have one in mind?

**Comment by bzbarsky** [comment]
Gecko has one (to detect whether window.console is a built-in Console object), but it's not exposed to the web.  At the moment we're just extending the namespace syntax to allow constants in a namespace; the problem is that we won't obviously notice if some spec starts using them even though webidl itself doesn't support them, because our parser will parse them.

It's not a huge deal either way for me, obviously.  Just thought I'd bring it up.

**Comment by tobie** [comment]
> the problem is that we won't obviously notice if some spec starts using them even though webidl itself doesn't support them, because our parser will parse them.

FYI, both Bikeshed and ReSpec will errors if a namespace contains a constant (I just checked), so this shouldn't arrive all the way up to the Gecko parser without raising flags beforehand.

**Comment by tobie** [comment]
I'll close this. We can reopen if we end-up needing it for Web-facing API.

**Comment by bzbarsky** [comment]
It looks like Web GPU may want this.  See https://github.com/gpuweb/gpuweb/issues/304#issuecomment-494955870

**Comment by Ms2ger** [comment]
It seems fine to add constants on namespaces if this is what we want the API to look like. Is that actually the case, though? I'd be interested to hear what the TAG thinks of the API.
