### ISSUE TITLE
Does `TreatNullAs` apply to `DOMString` inside a union type?

### ISSUE THREAD

**Issue by mikewest** [heycam/webidl#441]
Assume something like:

```
attribute [TreatNullAs=EmptyString] (DOMString or SomeObjectType) thing;
```

Does the `TreatNullAs` annotation mean that `obj.thing = null` results in the assignment of `""`? Or does the normal behavior of stringifying `null` to `"null"` kick in?

On IRC, @annevk noted that https://heycam.github.io/webidl/#es-union has "[includes a nullable type](https://heycam.github.io/webidl/#dfn-includes-a-nullable-type)", which talks about [annotated types](https://heycam.github.io/webidl/#annotated-types), which suggests that a nullable inner type would make the union type nullable. But `TreatNullAs` doesn't say one way or the other whether it makes the underlying `DOMString` nullable.

For https://github.com/mikewest/trusted-types, I think I'd like the `""` behavior rather than the `"null"` behavior, as it would make the whole thing simpler to layer on top of the existing web.

**Comment by tobie** [comment]
As per the [relevant section](https://heycam.github.io/webidl/#TreatNullAs) in the spec:

> The [TreatNullAs] extended attribute must not be associated with a type that is not DOMString.

What you want instead is to use [annotated types](https://heycam.github.io/webidl/#idl-annotated-types) like so:

```webidl
attribute ([TreatNullAs=EmptyString] DOMString or SomeObjectType) thing;
```
which will give you the desired behavior as long as `SomeObjectType` is not a nullable type.

Annotated types were introduced in https://github.com/heycam/webidl/pull/286. Implementation progress can be tracked from https://github.com/heycam/webidl/issues/336.

**Comment by TimothyGu** [comment]
Basically what @tobie said. One additional point:

> But `TreatNullAs` doesn't say one way or the other whether it makes the underlying DOMString nullable.

No, it does not. In fact, everything will fall back to the `DOMString` member type, which is what we want here.

But you did raise an interesting question: the union conversion algorithm only really talks about annotated types in the [flattened member types](https://heycam.github.io/webidl/#dfn-flattened-union-member-types) algorithm, which just throws away any annotations on the member types of a union type. This means that, technically as of now, `([TreatNullAs=EmptyString] DOMString or SomeObjectType)` is equivalent to `(DOMString or SomeObjectType)` as far as ES-to-IDL conversion is concerned. This does not seem right.

**Comment by tobie** [comment]
@TimothyGu, I'm not sure I follow your reasoning.

**Comment by tobie** [comment]
@TimothyGu, never mind, now I do. This is indeed broken. The annotated type needs to be kept around.

**Comment by tobie** [comment]
Ugh. And the whole union conversion algorithm needs to account for this also. :-/

**Comment by tobie** [comment]
Hopefully, the above answered your question. Not sure how we can help further at present. Feel free to reopen this issue and/or create another one if you want to discuss this further.
