### ISSUE TITLE
ES-to-IDL conversion broken for annotated types

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#443]
As raised by @TimothyGu in https://github.com/heycam/webidl/issues/441#issuecomment-330483591:

> the union conversion algorithm only really talks about annotated types in the [flattened member types](https://heycam.github.io/webidl/#dfn-flattened-union-member-types) algorithm, which just throws away any annotations on the member types of a union type. This means that, technically as of now, `([TreatNullAs=EmptyString] DOMString or SomeObjectType)` is equivalent to `(DOMString or SomeObjectType)` as far as ES-to-IDL conversion is concerned. This does not seem right.

**Comment by tobie** [comment]
Re-reading this now, it looks like the [ES to DOMString](file:///Users/tobie/Repos/webidl/index.html#es-DOMString) and [ES to Int](file:///Users/tobie/Repos/webidl/index.html#abstract-opdef-converttoint) algorithms are already handling this by looking at the extended attributes [associated with](file:///Users/tobie/Repos/webidl/index.html#idl-type-extended-attribute-associated-with) the types.

Closing this as wontfix.

**Comment by TimothyGu** [comment]
Ah okay, thanks!
