### ISSUE TITLE
ReadableStream IDL type

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#445]
I suspect most, if not all, of https://fetch.spec.whatwg.org/#streams needs to be in IDL.

cc @yutakahirano @domenic

**Comment by domenic** [comment]
I think we just need a type definition. The rest is better in Streams. See also previous discussion at https://github.com/whatwg/streams/issues/372 .

I can work on a type definition. I wonder if even that would make sense in Streams though, instead of Web IDL... we don't have a lot of precedent for this situation.

**Comment by annevk** [comment]
`ArrayBuffer` is precedent in a way. It seems somewhat nice if all non-platform objects are covered by IDL, but I don't care strongly. And the main reason for the algorithms to be in IDL is because we'd technically operate on the IDL type most of the time...

**Comment by TimothyGu** [comment]
What needs to be done here? Adding a new wrapper-style definition for `ReadableStream` (à la `ArrayBuffer`) as a type to Web IDL? Or redefine `ReadableStream` with an IDL fragment in Streams (which has its own problems, such as method enumerability differences)?

Or would it be sufficient to simply have something like the following in the Streams Standard:

> ### Web IDL Integration
> ```webidl
> [NoInterfaceObject, Exposed=(Window,Worker)]
> interface ReadableStream {};
>
> [NoInterfaceObject, Exposed=(Window,Worker)]
> interface WritableStream {};
>
> [NoInterfaceObject, Exposed=(Window,Worker)]
> interface TransformStream {};
> ```
>
> A [platform object](https://heycam.github.io/webidl/#dfn-platform-object) *V* **implements `ReadableStream`** if [IsReadableStream](https://streams.spec.whatwg.org/#is-readable-stream)(*V*) returns true.
>
> A [platform object](https://heycam.github.io/webidl/#dfn-platform-object) *V* **implements `WritableStream`** if [IsWritableStream](https://streams.spec.whatwg.org/#is-writable-stream)(*V*) returns true.
>
> A [platform object](https://heycam.github.io/webidl/#dfn-platform-object) *V* **implements `TransformStream`** if [IsTransformStream](https://streams.spec.whatwg.org/#is-transform-stream)(*V*) returns true.

**Comment by domenic** [comment]
The first option. You can't create empty interfaces and redefine "implements" in that latter way.

**Comment by annevk** [comment]
Note that I'm now ambivalent as to whether it should be in IDL or Streams. If @domenic would like to define the new IDL type directly in Streams that would be okay with me.

**Comment by jan-ivar** [comment]
The [WebTransport spec](https://w3c.github.io/webtransport/#idl-index) is full of WebIDL with comments like this one (third line):
```webidl
interface mixin UnidirectionalStreamsTransport {
  Promise<SendStream> createUnidirectionalStream(optional SendStreamParameters parameters = {});
  /* a ReadableStream of ReceiveStream objects */
  readonly attribute ReadableStream incomingUnidirectionalStreams;
};
```
Without this comment, it'd be hard to reason about what `incomingUnidirectionalStreams` gives you.

I think `ReadableStream` and `WritableStream` deserve the same treatment as `Promise` here:
```webidl
interface mixin UnidirectionalStreamsTransport {
  Promise<SendStream> createUnidirectionalStream(optional SendStreamParameters parameters = {});
  readonly attribute ReadableStream<ReceiveStream> incomingUnidirectionalStreams;
};
```

This would follow a tradition of making I/O types part of an API's code signature, helping readers reason about call sites.

**Comment by annevk** [comment]
@jan-ivar would you mind copy-and-pasting that into a new issue? I'll close this one as this was about streams not being defined in terms of IDL at all (they are now).

**Comment by jan-ivar** [comment]
Sure thing, filed as https://github.com/heycam/webidl/issues/951.
