### ISSUE TITLE
Why is a constant type nullable?

### ISSUE THREAD

**Issue by SaschaNaz** [heycam/webidl#446]
https://heycam.github.io/webidl/#prod-ConstType

```
ConstType ::
    PrimitiveType Null
    identifier Null
```

https://heycam.github.io/webidl/#idl-nullable-type

```webidl
interface MyConstants {
  const boolean? ARE_WE_THERE_YET = false;
};
```

I couldn't find a real world example that uses nullable constant types. Why is it nullable? How is `const boolean?` different from `const boolean`?

**Comment by TimothyGu** [comment]
I'm guessing because we need a way to express null.

```webidl
interface MyConstants {
  const whatShouldIPutHere NULL_VALUE = null;
};
```

If the constant value is actually a boolean, then I don't see any reason why a nullable type is used.

But if no IDL fragments in the web platform actually have null-valued constants, then I guess we can remove it.

**Comment by tobie** [comment]
> I'm guessing because we need a way to express null.

Indeed.

> But if no IDL fragments in the web platform actually have null-valued constants, then I guess we can remove it.

Well, we might end-up needing to support that in the future, so I don't think there's a point in removing it. Closing.

**Comment by annevk** [comment]
Cautiously reopening as we don't actually want new constants to be introduced (unless they're of the variety `Math.PI` which would be rather rare). Having said that, if this doesn't simplify things much it might not be worth the effort.

**Comment by tobie** [comment]
> Cautiously reopening as we don't actually want new constants to be introduced.

Sure. That's already specified in the spec, and sort of orthogonal, no?

**Comment by annevk** [comment]
Yeah, but given that I don't think the rationale that we might need it in the future is valid.

**Comment by SaschaNaz** [comment]
I think at least the `MyConstants` example should not have "nullable constant false", as we probably don't want authors to add unnecessary `?`.

**Comment by tobie** [comment]
> Yeah, but given that I don't think the rationale that we might need it in the future is valid.

Well, I wouldn't be surprised if either WebAssembly or WebGL would end up needing null as a constant.

**Comment by tobie** [comment]
> I think at least the MyConstants example should not have "nullable constant false", as we probably don't want authors to add unnecessary ?.

That's a fair point.

**Comment by tobie** [comment]
I've opened a follow-up issue to see if we can remove nullable types for constants altogether.
