### ISSUE TITLE
It shouldn't be possible for objects that implement non-exposed interfaces to appear in the environment

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#449]
This should be formally disallowed.

See https://github.com/heycam/webidl/issues/118#issuecomment-332932171.

**Comment by annevk** [comment]
Maybe for the dynamic case we could just add an assert? Since that's just a bug in the specification.

**Comment by bzbarsky** [comment]
That seems reasonable.

**Comment by Ms2ger** [comment]
Fixed in  #635.
