### ISSUE TITLE
Dot notation for dictionary members is not spec'ed.

### ISSUE THREAD

**Issue by kenchris** [heycam/webidl#453]
We would like to use this in the Web App Manifest spec

**Comment by annevk** [comment]
What exactly do you mean?

**Comment by kenchris** [comment]
From @marcoscaceres :
> Nit: please use for each, IDL sequences are just arrays, so it's nice to keep the language that maps to things in JS. Also, please don't use the bracket syntax, just use:

> ```For each <var>relatedApp</var> in <var>manifest</var>.<a>related_applications</a>.```

But @tobie said that we cannot use dot notation for these that is not defined for WebIDL and asked that I file an issue here.

**Comment by tobie** [comment]
Dot notation for dictionary members. @marcoscaceres doesn't links square brackets.

**Comment by kenchris** [comment]
This apparently affects Web Payment spec as well where they are already using dot notation according to @marcoscaceres

**Comment by annevk** [comment]
Is square brackets event documented? The convention to date was "dictionary's member".

**Comment by tobie** [comment]
Sort of: through a loophole with infra maps.

**Comment by annevk** [comment]
I guess we could define this in Infra as a syntax for maps whose strings are keys.

**Comment by domenic** [comment]
It seems better to me for everyone to use Infra maps (i.e. brackets)...

**Comment by kenchris** [comment]
I am fine with that, but @marcoscaceres isn't apparently. Maybe Marcos you could list your arguments?

**Comment by marcoscaceres** [comment]
I’ve not read what the rationale for this in WebIDL - so my reaction is mostly on ideomatic aesthetics and consistency with existing specs that use dot notation. 

I’m happy to listen to reason, as I’m sure there is good justification for the bracket syntax.

**Comment by tobie** [comment]
> I’ve not read what the rationale for this in WebIDL 

WebIDL doesn't say anything about it. It just piggy-back on the infra map notation because of the relation between maps and dictionaries. That's all there is to it.

**Comment by marcoscaceres** [comment]
Then I’m a bit 🤷‍♂️. This is used in prose, so I’d rather use dot notation if it’s not harmful (as it makes some things a little more compact). Otherwise, I’m happy to just use “dictionary’s member”.

**Comment by marcoscaceres** [comment]
I can definitely live with dict["foo"], but hear me out: my concerns are the same as the ones @annevk mentioned: We have specs already using `dict.foo` (e.g., payment request) and I'm worried that `dict["foo"]` will be confused with internal slots. I can see `dict["foo"]` making sense if member names could contain spaces, that's also not allowed. 

If you are all ok with the above, I'm also ok with it and we will use `dict["foo"]` for manifest.

@domenic, will we need to update Payment Request?

**Comment by annevk** [comment]
@marcoscaceres internal slots (which aren't really formalized yet other than in ECMAScript) would have two brackets on both sides, actually use a dot, not use quotation marks, and start with an uppercase character. I.e., foo["bar"] vs foo.[[Bar]].

Furthermore, dictionaries reuse the syntax we have for maps and maps can have keys with spaces (or non-string keys), that's why we went with foo[...].

**Comment by marcoscaceres** [comment]
I concur. Feel free to close.

**Comment by annevk** [comment]
Great! Please do continue to raise these kind of issues when you run across them. I think it's very valuable we work these through together and come to a common understanding as to how we want to approach things.

**Comment by anssiko** [comment]
@annevk, so do we use lower camel case as `[[foo]]` or upper camel case `[[Foo]]`? E.g. https://streams.spec.whatwg.org/#default-reader-internal-slots uses the former whereas ECMScript uses the latter notation.

**Comment by tobie** [comment]
@anssiko: internal slots outside of ES aren't formalized yet. ES's internal slots are UpperCamelCase. It might be that we adopt this convention, it might also be that we don't (e.g. to mirror the internal slot that correspond to attributes).

**Comment by annevk** [comment]
@anssiko might be worth filing a bug against Streams for that. I suspect they mean to align with ECMAScript since it's an ECMAScript-like standard.

**Comment by anssiko** [comment]
Filed https://github.com/whatwg/streams/issues/825

**Comment by tobie** [comment]
Note that a counter argument would be to limit UpoerCamelCase usage to ES internal slots and use regular camel casing for the WebIDL layer.

**Comment by annevk** [comment]
Yeah, but that doesn't apply to Streams.

**Comment by tobie** [comment]
I guess it depends where precisely you draw the border.
