### ISSUE TITLE
Status of this document section mistakenly links to public-webapps@

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#455]
Figure out how to remove the following from SOTD:

> Feedback and comments on this specification are welcome, please send them to public-webapps@w3.org (subscribe, archives) with %5Bwebidl%5D at the start of your email’s subject.

Pinging @tabatkins as there might be a trivial way to do this.

**Comment by tabatkins** [comment]
This is from the <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/webplatform/status-ED.include> boilerplate file.

You can replace the whole thing with a `<div boilerplate=status>` element containing what you want instead, or by putting a `status.include` file in the same folder as the spec source.

**Comment by tabatkins** [comment]
(Unrelated: I have no clue why the person who wrote this status file thought that URL-escaping the square brackets was appropriate for plain text.)

**Comment by tobie** [comment]
Sort of disappointing, but not unexpected coming from @W3C, to see the lightweight and tweakable original SOTD be replaced by massive, mistake-laden boilerplate. :(
