### ISSUE TITLE
Missing argument handling

### ISSUE THREAD

**Issue by timruffles** [heycam/webidl#461]
Browsers throw exceptions if DOM APIs are invoked with missing arguments, and it's been this way for a while.

This behaviour doesn't seem clearly specified here, however. The algorithm for resolving overloaded function calls will indeed cause `TypeError` to be thrown if the arguments don't match any overload. However, from the definition of overloaded operations above:

> If a regular operation or static operation defined on an interface has an identifier that is the same as the identifier of another operation on that interface of the same kind (regular or static), then the operation is said to be overloaded. 

this algorithm doesn't seem to apply to non-overloaded calls.

It seems sensible to have this mentioned somewhere - I'm happy to PR it in.

**Comment by TimothyGu** [comment]
The overload resolution algorithm applies to all operations, even if they are not overloaded. See [create an operation function](https://heycam.github.io/webidl/#dfn-create-operation-function) steps 3-4. "Overloaded operations" is different from the "overload" used here in the algorithm, which refers to an element in an [effective overload set](https://heycam.github.io/webidl/#dfn-effective-overload-set). In fact, a single, non-overloaded operation `void a(optional DOMString arg);` in fact will produce two entries in the effective overload set.

The other potential point of confusion is that the exact exception message thrown by browsers can be different and confusing. In Chrome for example, while

```js
document.createElement('canvas').getContext('2d').drawImage()
```

throws `TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': 3 arguments required, but only 0 present.`,

```js
document.createElement('canvas').getContext('2d').drawImage(new Image(), 0, 0, 0)
```

throws `TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': Valid arities are: [3, 5, 9], but 4 arguments provided.`. Spec-wise, they are thrown from the same step ([overload resolution algorithm](https://heycam.github.io/webidl/#dfn-overload-resolution-algorithm) step 4).

**Comment by timruffles** [comment]
Okay - I've made a PR which updates the wording to make that explicit.
