### ISSUE TITLE
Fix ambiguity within the [SecureContext] section

### ISSUE THREAD

**Issue by anssiko** [heycam/webidl#465]
It would be clearer if the generic term "exposed" and the "exposed" [formal definition][1] would be easier to distinguish from each other, optimally not share the same name.

To fix this ambiguity within the [[SecureContext]][2] section, how about rename:

>it indicates that the construct is exposed only within a secure context.

Into:

>it is [available only in secure contexts][3].

There are many occurrences of "exposed" using both the meanings in WebIDL (and elsewhere), but that refactor is out of scope for this particular issue.

[1]: https://heycam.github.io/webidl/#dfn-exposed
[2]: https://heycam.github.io/webidl/#SecureContext
[3]: https://heycam.github.io/webidl/#dfn-available-only-in-secure-contexts

**Comment by annevk** [comment]
The formal meaning of exposed is intended here and does now appear to be linked, see https://heycam.github.io/webidl/#SecureContext. Does that make it less confusing?

**Comment by anssiko** [comment]
Thanks for the fix, clear now.
