### ISSUE TITLE
ECMAScript global environment -> realm, as appropriate

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#466]
I thought we had an issue for this, but we didn't.

The term "ECMAScript global environment" is used throughout IDL, basically to refer to the same thing as "realm", but it was invented before that concept existed in the JS spec.

We should get rid of it and replace it with appropriate references to realms. This is probably mostly mechanical; there are 11 uses left that I can see.

The "exposes" stuff might also be formalized better by making things imperative; I will file another issue for that.

**Comment by Ms2ger** [comment]
Fixed in #681.
