### ISSUE TITLE
Add a frozen record type?

### ISSUE THREAD

**Issue by littledan** [heycam/webidl#469]
WebAssembly module instantiation creates an exports object which is frozen. This is not a frozenarray, it's more like a frozen record, since the keys are arbitrary strings. It seems like if I declare the WebIDL type to be a record, I can't just call  SetIntegrityLevel(array, "frozen") in my own spec, since I don't have access to the object after it is converted by WebIDL. Would it make sense to define a new type here?

**Comment by domenic** [comment]
This is a return type, right? In that case I'd just use `object` personally. Others don't always agree with me, but I find worrying about Web IDL return types a bit silly, since they don't have JS-observable impacts (like how argument types cause coercion algorithms to run).

**Comment by bzbarsky** [comment]
For now, I agree: use `object` and manual definition of things on it.  If we end up with multiple consumers that want this, we can think about specifying something.

**Comment by littledan** [comment]
OK, sounds good, thanks!

**Comment by annevk** [comment]
@domenic one thing that we rely on in places is that returning a byte sequence to something that returns a ByteString in IDL does the right thing. There's also things like that for things that return a sequence (which turns whatever into an Array). Return values definitely have some impact, if only converting from IDL to JavaScript, but as I've shown also more.
