### ISSUE TITLE
Can SpecialOperation be more simplified?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#470]
Currently [SpecialOperation](https://heycam.github.io/webidl/#prod-SpecialOperation) allows multiple keywords before RegularOperation:

```
SpecialOperation ::
    Special Specials RegularOperation
Specials ::
    Special Specials
    ε
Special ::
    getter
    setter
    deleter
```

This was required before #44 to allow `setter creator void set(DOMString name, any value);` but now it seems no IDL uses `getter setter`, `setter deleter`, etc.

So I think SpecialOperation can just be `Special RegularOperation`, what do you think?

**Comment by bzbarsky** [comment]
Should probably also clean up the language in https://heycam.github.io/webidl/#idl-special-operations accordingly.  And replace "five" with "four" while we're there.

But yes, this cleanup would make sense to me.

Also, it's not immediately obvious why stringifier and getter/setter/deleter are handled differently in grammar terms...

**Comment by tobie** [comment]
So now that we have CI that verifies the grammar stays LL(1), I'm much more confident to do a syntax overhaul/cleanup.
