### ISSUE TITLE
Prototype of @@unscopable object

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#496]
The @@unscopable property on interface prototype objects (if it exists) currently has the prototype of %ObjectPrototype%, whereas the only such object in ECMAScript [`Array.prototype[@@unscopables]`](https://tc39.github.io/ecma262/#sec-array.prototype-@@unscopables) has null as prototype.

Because of the fact that @@unscopables is [used](https://tc39.github.io/ecma262/#sec-object-environment-records-hasbinding-n) with `ToBoolean(Get())` rather than something more specific like `HasOwnProperty()`, we are blocking more properties than we intended to (the %ObjectPrototype% properties).

If this wasn't intentional, we should change this. If it was, we should clarify this with a note.

**Comment by tobie** [comment]
Good point.

**Comment by bzbarsky** [comment]
Just as data points, `Object.getPrototypeOf(Element.prototype[Symbol.unscopables])` is null in Safari, non-null in Chrome and Firefox.  Edge seems to not have unscopables there at all.

I think having a null prototype and we should change the spec to match Safari.

@domenic

**Comment by tobie** [comment]
> I think having a null prototype makes a lot of sense and we should change the spec to match Safari.

WFM. I'll bake it into #494.

**Comment by bzbarsky** [comment]
Sounds good.  We should add some wpts.

**Comment by bzbarsky** [comment]
I am adding wpts in https://bugzilla.mozilla.org/show_bug.cgi?id=1437255

**Comment by tobie** [comment]
Merged WPT tests: https://github.com/w3c/web-platform-tests/pull/9490.
