### ISSUE TITLE
Distinguishability of buffers source types needs to be defined better

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#50]
Right now the spec says that "buffer source types" are not distinguishable from each other.  But this is clearly wrong, since if that were the case the `BufferSource` typedef would not be valid.

I believe the right behavior here is that `ArrayBuffer` is distinguishable from everything that's not `ArrayBuffer`, `ArrayBufferView` is distinguishable from everything that's not `ArrayBufferView` or a typed array type, and a typed array type is distinguishable from everything except `ArrayBufferView` and itself.

I'm not sure how best to put this in the form of this table, because it would make the table huge...

Perhaps the simplest thing to do is to define that distinguishability works as if these were all interface types with the typed array interfaces considered as inheriting the `ArrayBufferView` interface.

**Comment by jyasskin** [comment]
If we treat each buffer source type as its own interface, then because [`ArrayBufferView`](https://heycam.github.io/webidl/#ArrayBufferView) is:
```idl
typedef (Int8Array or Int16Array or Int32Array or
         Uint8Array or Uint16Array or Uint32Array or Uint8ClampedArray or
         Float32Array or Float64Array or DataView) ArrayBufferView;
```

I think the union distinguishability rules already give us the behavior you think is right.

**Comment by bzbarsky** [comment]
Ah, I'm not sure ArrayBufferView was defined that way before.  But given that it is, I agree: if we just treat each typed array type, and `ArrayBuffer`, as a distinct interface, things will Just Work.
