### ISSUE TITLE
record with arbitrary value types as keys?

### ISSUE THREAD

**Issue by henbos** [heycam/webidl#509]
The definition for `record<K, V>` says:

> K must be one of DOMString, USVString, or ByteString

It would be useful to be able to use `enum` for key types, which are essentially strings.
I hit the problem that this is not possible in https://github.com/w3c/webrtc-stats/issues/281.

In https://github.com/w3c/webrtc-stats/issues/133 it would also be useful if the key could be integers.

Why is `K` restricted this way? If not any `K`, how about any `K` that is by-value?

**Comment by henbos** [comment]
I'm guessing the restriction is because it should be ordered, but both enum and integers are ordered.

**Comment by annevk** [comment]
K is effectively a property in a JavaScript object so has to be a string. Using an enum there would be possible, though at that point why would you not use a dictionary?

I followed your links, but they don't provide much context here either.

**Comment by henbos** [comment]
Thanks for the quick response.
Dictionary instead of record in the case of enum would works, but if we use a dictionary then we have to define every name in two places instead of just saying it's a mapping.

Dictionary in the case of integers doesn't work with this restriction. And Maplike is an interface (copy-by-reference), not a dictionary (copy-by-value). We want copy-by-value.

As for _"K is effectively a property in a JavaScript object so has to be a string"_. If we allow other Ks then it would be possible to have records that are not JavaScript objects, sure, but you can still say that any JavaScript object is a record, so it would be perfectly sensible for a spec to say something is a record, and to have the implementation of that spec implement it as a JavaScript object.

**Comment by annevk** [comment]
I'm not sure I follow. What does maplike have to do with this?

As IDL maps between JavaScript and an internal representation, you cannot really say that K can be something else if that cannot be represented in JavaScript...

More context would help.

**Comment by henbos** [comment]
More context:

We have a dictionary and we want it to contain a member that is a key-value mapping. We don't want the key-value mapping to be another dictionary type, because then we have to define a new dictionary type. Meaning we have do list all _possible_ keys as members - in the case of enum: list all the enum values as members in the dictionary, in the case of integers: list every possible integer as a string?

For key-value mappings, it seems to me the alternatives at our disposal are `record<K,V>` and `Maplike<K,V>`. I mentioned `Maplike<K,V>` to discuss why we don't want to use the alternative. My assumption was that a dictionary must only contain value types (because they are copied by value), so anything that is an interface like `Maplike<K,V>` is not allowed (because they are copied by reference). Is this correct, or can a dictionary contain a reference type?

> As IDL maps between JavaScript and an internal representation, you cannot really say that K can be something else if that cannot be represented in JavaScript...

Sorry for being unclear. I was thinking the record's getters/setters could be defined with methods in addition to plain ol' properties. So a `record<K,V>` could be "JavaScript object _or_ native backed up object with get(K), set(K,V) methods", allowing any K or V.

But that is confusing...
On second thought I don't think we have to go there.

**Proposal**

Number properties in JavaScript are automatically converted to strings, e.g. `let obj = { 123: 'hello' }` is equivalent to `let obj = { '123': 'hello' }`. Accessed as `obj['123']` or `obj[123]` interchangeably.
`K` should be extended to include numerical values and enums. This does not break the assumption about JavaScript objects.

**Comment by annevk** [comment]
So are you trying to return a `record<>`? In that case you'd have to define exactly the kind of thing you want to return. In case you're accepting a `record<>` incoming numbers will already be stringified as per your example...

**Comment by henbos** [comment]
Specific use case:

I have a method that returns a bunch of stats defined with different dictionaries. They're all a snapshot in time, so return-by-value makes perfect sense. One of the stats describe how much time a stream has spent in quality limited scenarios described by an enum:
```
enum RTCQualityLimitationReason {
    "none",
    "cpu",
    "bandwidth",
    "other",
};

dictionary RTCOutboundRTPStreamStats : RTCSentRTPStreamStats {
    ...
    record<RTCQualityLimitationReason, double> qualityLimitationDurations;
}
```

This is not allowed, so I changed it to
`record<DOMString, double> qualityLimitationDurations;`
and added a comment saying the only `DOMString`s used are values of `RTCQualityLimitationReason`. I think this is less elegant.

> The values of dictionary members can be references.

Okay, in that case I could also change it to
`Maplike<RTCQualityLimitationReason, double> qualityLimitationDurations;`
and return a new object every time we create the dictionary. (But doesn't `record<RTCQualityLimitationReason, double>` make more sense, as it is intended to be passed by value?)

**Comment by henbos** [comment]
The second use-case is the same, except for mapping `RTCQualityLimitationReason -> duration` it's mapping "DSCP codepoints", which are integers, with packets received counters, also integers.

**Comment by bzbarsky** [comment]
> Okay, in that case I could also change it to Maplike<RTCQualityLimitationReason, double>

No, you couldn't.  `maplike` declarations are a thing that goes on interfaces, not a type.  You _could_ define an interface that's maplike, of course, depending on what the rest of your API looks like.

In practice, the only reason to use the enum type instead of DOMString in the "return to JS" case is for documentation purposes.  The spec prose still has to specify exactly what keys are stored in the record.  In the integer case, theoretically the only reason is documentation, but in practice it may be more efficient to create the JS object if it's known that the keys are integers.

Apart from implementation complexity, the other drawback of adding these things is that in the _other_ direction (coming from JS) there are various questions about how these key types should work...

**Comment by henbos** [comment]
What's your take, @alvestrand ?

**Comment by alvestrand** [comment]
I think that saying we pass DOMString is losing clarity in the interface when we have enums or (limited-range - my particular use case has 4-bit) integers as the underlying objects. So I think restricting to DOMString doesn't benefit us any.
When we pass stuff from JS to an interface, we should behave like dictionaries do and ignore undefined members.

**Comment by domenic** [comment]
It sounds like what you want here is a dictionary. The fact that you'll have to synchronize between the enum and dictionary definition is a bit unfortunate, but that's the short of tradeoff you often have to make in declarative languages that don't have full Turing-completeness, and Web IDL is no different.

**Comment by alvestrand** [comment]
A dictionary has predefined keys specified in WebIDL.
A colleague of mine in a similar discussion very long ago:

"Late binding is good. <other specification language> binds before compile time".

We can stick to DOMString and have the linkage in prose. No tool can check that we're doing it right, since there's no formal linkage.
We'll just have to trust the implementors.

**Comment by domenic** [comment]
Yes, from what I understand, predefined keys specified in Web IDL is exactly what you need, so dictionary is a good tool for the job.

**Comment by inexorabletash** [comment]
> We'll just have to trust the implementors.

That sounds like asking for interop issues. :(
```webidl
enum RTCQualityLimitationReason {
    "none",
    "cpu",
    "bandwidth",
    "other",
};
dictionary QualityLimitationDurations {
    double none;
    double cpu;
    double bandwidth;
    double other;
}
```
Slightly more work on the spec side (modulo tooling per @domenic), but now implementers can copy/paste.

**Comment by alvestrand** [comment]
but if we could define record<RTCQualityLimitationReason, double>, we would have done it in one line, with no tooling.

**Comment by domenic** [comment]
But that's twisting the concept of record to mean something it isn't; it's specifically meant for open-ended property bags, not ones with predefined sets of keys.

**Comment by inexorabletash** [comment]
IMHO, the feature request for a WebIDL construct to support this case is totally valid. It's just not a common enough use case at this time to merit the overhead of dedicated syntax when there is an alternative.

**Comment by tobie** [comment]
All in all, I see how this could be valuable. That said, I also agree with @domenic. The semantics of this proposal would be surprising. Record is basically an open-ended bag of properties. Limiting the keys to enum values (either by throwing or dropping them) would effectively turn it into a close-ended one, aka a dictionary.

I think we should close this for now and revisit if other similar uses cases pop up. Would that work for you?
