### ISSUE TITLE
typo in the definition of an unrestricted double?

### ISSUE THREAD

**Issue by littledan** [heycam/webidl#51]
3.10.14 "The unrestricted double type is a floating point numeric type that corresponds to the set of all possible double-precision 32 bit IEEE 754 floating point numbers, finite and non-finite. [IEEE-754]"

Surely this should read "double-precision 64-bit floating point numbers", matching the normal double definition, right?

**Comment by heycam** [comment]
Thanks, yes.  This has already been fixed in the Editor's Draft.
