### ISSUE TITLE
typeof operator and platform objects

### ISSUE THREAD

**Issue by TimothyGu** [heycam/webidl#512]
The [`typeof` operator](https://tc39.github.io/ecma262/#table-35) is defined for "Object (non-standard exotic and does not implement [[Call]])" to return "Implementation-defined. Must not be "undefined", "boolean",  "function", "number", "symbol", or "string"."

From

> The semantics of the essential internal methods for ordinary objects and standard exotic objects are specified in clause 9.

it seems that "non-standard" means "non-ECMA-262". Then named property objects, legacy platform objects, etc. are all non-standard. We should say in Web IDL that they should all return "object"

**Comment by bzbarsky** [comment]
> We should say in Web IDL that they should all return "object"

Sort of.  HTMLAllCollection needs to return "undefined".  Which the ES spec doesn't allow, of course.

**Comment by bzbarsky** [comment]
But yes, for the rest we should spec that they return "object"

**Comment by TimothyGu** [comment]
> Which the ES spec doesn't allow, of course.

Now it does :)

See https://tc39.github.io/ecma262/#sec-IsHTMLDDA-internal-slot-typeof and https://github.com/whatwg/html/pull/3087.

**Comment by bzbarsky** [comment]
> Now it does :)

Oh, a COMEFROM spec.  Lovely.  ;)

**Comment by annevk** [comment]
I actually think ES shouldn't say this is implementation-defined. It should be host-defined and there should be a hook for hosts to make it work more automatically. And perhaps given that `document.all` is fixed there need not be host exceptions?

**Comment by littledan** [comment]
Good point; I filed https://github.com/tc39/ecma262/issues/1440 to discuss a simplification here.
