### ISSUE TITLE
[Exposed] section unnecessarily restrictive about partial interface + members

### ISSUE THREAD

**Issue by tabatkins** [heycam/webidl#515]
Per the spec:

> The [Exposed] extended attribute must not be specified both on an interface, mixin, or namespace member, and on the partial interface, partial interface mixin, or partial namespace definition the member is declared on.
>
> Note: This is because adding an [Exposed] extended attribute on a partial interface, partial interface mixin, or partial namespace is shorthand for annotating each of its members.

But the algorithm for retrieving the exposure set of an interface member works just fine if it both has an [Exposed] and is in a partial interface with an [Exposed] - it'll grab the member's [Exposed] if it exists, otherwise it walks up to the partial and grabs its [Exposed].  This makes sense - it's the same defaulting behavior that [Exposed] has for members of non-partial interfaces.  So what's the point of the restriction?

**Comment by bzbarsky** [comment]
Does it walk up to the partial?  Back when that text written, it would walk up to its _interface_ which was not the same thing at all.  That is, the [Exposed] on the partial was literally a macro that set it on all the members, not something that got consulted in some order.

What is the expected behavior of this IDL:

    [Exposed=(Foo, Bar)] inteface X {};

    [Exposed=Foo]
    partial interface X {
      [Exposed=Bar] readonly attribute long foo;
    };

Avoiding having to define all the weird edge cases like this (much less having to get everyone to agree on their desired behavior!) was the other motivation for the current restriction.

**Comment by tabatkins** [comment]
It walks up to the partial <https://heycam.github.io/webidl/#dfn-exposure-set>:

> 3. If C is an interface member, interface mixin member, or namespace member, then:
> [...]
> Otherwise, set C to be the interface, partial interface, interface mixin, partial interface mixin, namespace, or partial namespace C is declared on.

Then the algo retrieves the exposure set of the partial interface and returns it (or walks up to the original non-partial version of the interface and returns the exposure set of *that*).

Per the current algorithm, in your example, `X` is exposed to both `Foo` and `Bar`, while `X.foo` is only exposed to `Bar`.

**Comment by bzbarsky** [comment]
The problem is that applying the algorithm as-is to this situation this gives very different semantics to [Exposed] on interfaces and on partials: the exposure set of a member must be a subset of the exposure set of an interface, but you're proposing that this not hold for a partial.

Let me ask a different question: What is the use case where you want to specify an exposure set on both a partial and on its members separately?

**Comment by tabatkins** [comment]
[Exposed] on an interface serves two completely independent (tho usually linked in practice) purposes: it sets the exposure of the constructor functions, and it sets the default exposure for all the members of the interface.  It generally makes sense that the latter must be a subset of the former; you shouldn't have members that are only visible in realms where you're not allowed to construct the objects that the members are on.

On a partial interface, you only have the latter use (since the constructor functions' visibility is defined by the original interface definition already).  It's perfectly fine for the "default" exposure from the partial to not be a superset of an individual member's exposure, as long as both of them are subsets of the original interface's exposure; it's the same as the partial in your example *not* defining an [Exposed], then having two members, one of which is [Exposed=Foo] and the other which is [Exposed=Bar].

(I don't have a use-case for this, I was just confused by the section for an unrelated reason before figuring things out, then realized this restriction was unnecessary.)

**Comment by bzbarsky** [comment]
I think the point is that removing the restriction makes it a lot more complicated to reason about exposure sets around partials.  If there's no use case, then I would personally prefer to keep the restriction, so we don't have people writing confusing IDL...

**Comment by tabatkins** [comment]
That's fine with me, it just means that sometimes people will want to write two separate `partial interface`s, if they have two subsets of members they want to expose in different globals. (Rather than explicitly writing [Exposed] on every member...).

**Comment by tobie** [comment]
> That's fine with me, it just means that sometimes people will want to write two separate partial interfaces, if they have two subsets of members they want to expose in different globals. (Rather than explicitly writing [Exposed] on every member...).

I think that's a feature. Overall, we should aim to be explicit and clear as possible when we write IDL. As Boris mentioned above, not having those restrictions creates lots of corner case where the results, while unambiguous when applying the algorithm, aren't obvious when looking at the IDL.

**Comment by tabatkins** [comment]
Kk!
