### ISSUE TITLE
Is an interface named I exposed in realm R

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#518]
This is a check that [StructuredDeserialize](https://html.spec.whatwg.org/#structureddeserialize) makes in prose, but it would be nice to have it grounded somehow so you can actually lookup what it means:

> If the interface identified by _interfaceName_ is not exposed in _targetRealm_, then ...

**Comment by TimothyGu** [comment]
https://heycam.github.io/webidl/#dfn-exposed is probably what you are looking for.

**Comment by annevk** [comment]
Oh great, I didn't realize we had that already. I did search through the document, but somehow didn't arrive there. I guess the only question is then how to go from a name to an interface and back, but maybe it's okay to remain hand-wavy about that for now.
