### ISSUE TITLE
[[MapData]] is not a thing

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#521]
https://heycam.github.io/webidl/#es-maplike says:

> This Map object’s [[MapData]] internal slot is the object’s map entries.

but everything else calls that slot [[BackingMap]].

**Comment by tabatkins** [comment]
No, the ES spec definitely use [[MapData]] for the abstract data source of a Map <https://tc39.github.io/ecma262/#sec-map-objects>

**Comment by TimothyGu** [comment]
This sentence refers to the [[BackingMap]] (“This Map object”)’s [[MapData]].

**Comment by bzbarsky** [comment]
Oh, I see.  Reading fail on my part.
