### ISSUE TITLE
"call a user object’s operation" should not have an optional argument in the middle

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#534]
That makes callers ambiguous unless they use rather elaborate wording to get around it.

This is about _opName_.

Now, having said that, do we actually need _opName_? We don't want folks to use callback interfaces. Those in DOM only have a single operation (although they both do list _opName_, maybe it wasn't always optional). Are there any that have more than one operation?

**Comment by bzbarsky** [comment]
> Now, having said that, do we actually need opName?

In general, yes.  Your real question is whether we can derive it from the interface definition or something, right?

> Are there any that have more than one operation?

Not in specs as far as I can see.  Gecko has a MozIdleObserver thing (not web-exposed) which has two operations.

**Comment by annevk** [comment]
>  Your real question is whether we can derive it from the interface definition or something, right?

No, step 9.1 of https://heycam.github.io/webidl/#call-a-user-objects-operation already does that. Ideally I'd like to remove the branching there so we only support one variant. I guess another way to remove the branching is to simply require _opName_ and not make it a sometimes-optional argument.

**Comment by bzbarsky** [comment]
So the current language allows omitting _opName_ if the interface is "single operation" **and** _O_ is callable.

Which means in practice, unless you know something about _O_ already it's required right now, right?

**Comment by annevk** [comment]
Hmm, yeah. Though "single operation callback interface" does do an awful lot of peeking at the interface including looking at the names of operations, it doesn't actually retrieve it.

**Comment by Ms2ger** [comment]
Looking at the callback interfaces that Gecko implements, only the ones in DOM seem to be specified in enough detail to use this algorithm, and DOM always passes the argument, so let's just make it required.
