### ISSUE TITLE
@@toStringTag property attributes + general semantics

### ISSUE THREAD

**Issue by caitp** [heycam/webidl#54]
> **Editorial note**
> Should define whether @@toStringTag is writable, enumerable and configurable. All @@toStringTag properties in the ES6 spec are non-writable and non-enumerable, and configurable.

I think we really need to define these. Matching the values on the builtin properties is probably good, because fewer inconsistencies between DOM & JS is good.

The other issue with these properties, is making `InterfacePrototype.@@toStringTag === "InterfacePrototype"` while `Interface.@@toStringTag === "Interface"` --- I don't believe we want to give `Interface` an instance property `@@toStringTag`, so the alternative is making `@@toStringTag` a getter which returns a distinct value depending on the receiver --- but this kind of sucks?

So yeah, I don't think we have a good answer for these semantics right now. It's probably worth discussing it a bit

**Comment by bzbarsky** [comment]
The interface vs interface prototype issue is covered by https://www.w3.org/Bugs/Public/show_bug.cgi?id=28244l

**Comment by caitp** [comment]
I guess we'll try Erik's idea and see if it breaks anything

**Comment by caitp** [comment]
Tangentially related to this thread:

@bzbarsky given what you're saying in https://lists.w3.org/Archives/Public/public-script-coord/2015JulSep/0022.html --- Maybe `Window` (or just `WindowProxy`, but I don't think that works well for Blink atm) needs an `[Unforgeable] readonly` toStringTag/isConcatSpreadable, with a primitive value.

Does that seem sensible, or too restrictive on same-origin objects?

**Comment by bzbarsky** [comment]
I don't see why we need anything unforgeable on Window at all.  You do need something on cross-origin WindowProxy instances, of course.

I think making same-origin access not do the right thing here would be quite confusing to consumers....

**Comment by annevk** [comment]
This got fixed in #357.
