### ISSUE TITLE
Disallow [LegacyArrayClass] on globals

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#545]
This allows removing step 3 of the [create a named properties object algorithm](https://pr-preview.s3.amazonaws.com/tobie/webidl/pull/494.html#create-a-named-properties-object).

There are no such cases of globals which also have the [LegacyArrayClass] extended attribute, so that shouldn't be an issue.

**Comment by annevk** [comment]
I suggest we duplicate this against #291.

**Comment by tobie** [comment]
Fixed in https://github.com/heycam/webidl/commit/ec3531b8fbde1a66236753188d26e8f075a9fca5.
