### ISSUE TITLE
Poorly worded normative requirement could be improved

### ISSUE THREAD

**Issue by travisleithead** [heycam/webidl#548]
Filing this only because we implemented this incorrectly, and had to re-read it 10 more times before it [sort of] made sense :)

> The [Exposed] extended attribute must not be specified both on an interface, mixin, or namespace member, and on the partial interface, partial interface mixin, or partial namespace definition the member is declared on.

Two things: 

Clarify that its the member being described--this is revealed only via inspection of the hyperlink: e.g.,:

> The [Exposed] extended attribute must not be specified both on an interface **member**, mixin **member**, or namespace member, and on the partial interface, partial interface mixin, or partial namespace definition the member is declared on.

This makes it sound like its possible to have the same member defined both in a partial interface and non-partial interface. This obviously can't happen. A better phasing might be:

> The [Exposed] extended attribute must not be specified both on the members and on the member's host interface, where the host interface is a partial interface, partial mixin interface, or partial namespace.

That makes much more sense to me.

**Comment by tobie** [comment]
That section is indeed poorly worded. My bad.

I'm curious as to what you mean when you say that it was implemented incorrectly on your side. These are really instructions to spec editors.

Do you have extra code that enforces it in your bindings? Does that somehow throw at compile time?

**Comment by bzbarsky** [comment]
Gecko's binding generator certainly has code to enforce that the IDL we have in our tree follows the IDL spec.  That catches errors in standards all the time, because standard authors don't necessarily actually check their IDL against the spec....

**Comment by tobie** [comment]
That's good to know.

**Comment by tobie** [comment]
Wouldn't it make sense to collaborate on this validation tool somewhere upstream? Maybe in Bikeshed/ReSpec land, or in idlharness?

**Comment by bzbarsky** [comment]
That wouldn't solve the problem of browser developers writing bogus IDL.  So we would want build-time validation anyway.

**Comment by bzbarsky** [comment]
It's possible, sure.  I think spec authors could certainly use something like this.

**Comment by travisleithead** [comment]
Thanks!
