### ISSUE TITLE
Is a dictionary which has an inherited dictionary with a non-JSON-type member a JSON type?

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#555]
Consider this IDL:

    dictionary A {
      Node node;
    };

    dictionary B : A {
      DOMString str;
    };

Is `B` a JSON type?  The spec says "dictionaries where all of their members are JSON types" are JSON types, and all the members of B itself are JSON types...

I suspect this should be clarified to include the members of all the inherited dictionaries.

**Comment by tabatkins** [comment]
Definitely, this seems like a straightforward accidental omission.
