### ISSUE TITLE
How to tell the type of "construct a callback function"?

### ISSUE THREAD

**Issue by yuki3** [heycam/webidl#557]
I'm wondering if there is a way to describe a signature of [IDL callback function as a constructor](https://heycam.github.io/webidl/#construct-a-callback-function).

We can tell the types of the arguments list for [invoke](https://heycam.github.io/webidl/#invoke-a-callback-function) from the declaration in IDL.
```
callback Foo = void(DOMString arg1);
```
But how can we tell the types of the arguments list for [construct](https://heycam.github.io/webidl/#construct-a-callback-function)?

If there is no way, then I'd like to apply [Constructor] extended attribute to IDL callback functions.
```
[Constructor(DOMString ctor_arg1)]
callback Foo = void(DOMString arg1);
```

FYI, [CustomElementRegistry.define](https://html.spec.whatwg.org/multipage/custom-elements.html#customelementregistry) takes |constructor| of type |Function|, where there is no type information about the constructor arguments.

Explicit type information in IDL is helpful for user agent implementor, I think.

**Comment by bzbarsky** [comment]
> Yeah, but already-typed argument list is provided runtime only.

That's fair.  I think saying that the types are the same as the types used for invoke would make sense, fwiw.

Again, for the one use case we have so far there are no arguments and the return type used in practice is either "any" or "Element" depending on how you want to interpret the `SameValue` sleight of hand that uses an ES value on one side and an IDL value on the other...  Which one is used will affect what sort of exception (TypeError vs an InvalidStateError DOMException) is thrown, of course.

**Comment by domenic** [comment]
Using the same types for construct and invoke seems reasonable to me as well. We could define a specific callback type in HTML instead of using Function if it would help implementers.

@yuki3 would you be willing to work on spec PRs for these things?

**Comment by yuki3** [comment]
> @yuki3 would you be willing to work on spec PRs for these things?

I'm a totally newbie about spec work, but let me give it a try.


By the way, IIUC, [CSS Painting API](https://www.w3.org/TR/css-paint-api-1/#invoke-a-paint-callback) and [Animation Worklet](https://wicg.github.io/animation-worklet/#create-a-new-animator-instance) are willing to follow the same (or similar at least) way to custom elements, and will use the 'construct' algorithm of IDL callback function.

Animation Worklet passes a list of (options, state) as the arguments in the constructor.

**Comment by bzbarsky** [comment]
> Animation Worklet passes a list of (options, state) as the arguments in the constructor.

Right, but it's working with ES values already, not IDL values...  That said, there may be value in passing them in as `any` and doing the IDL construct thing, because that will do the various bookkeeping that needs to be done.

**Comment by yuki3** [comment]
I've made a patch at https://github.com/whatwg/html/pull/3703 .

As I rarely work on github repositories, probably I'm missing some points or wrong.  Please let me anything you notice.

**Comment by yuki3** [comment]
Thank you all.  @domenic merged the patch, so I close this issue.
