### ISSUE TITLE
identifier needs to allow a leading hyphen

### ISSUE THREAD

**Issue by peria** [heycam/webidl#564]
[CSSOM spec](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_dashed_attribute) describes about identifiers with leading dashs, but they conflict with current WebIDL spec, because now we allow `/_?[A-Za-z][0-9A-Z_a-z-]*/` in identifiers.

So I'd suggest to update the pattern to allow a hypen as a leading character to make both specs consistent with each other. Specifically, I suggest following two candidates.
- `[_-]?[A-Za-z][0-9A-Z_a-z-]*`
- `_?[A-Za-z-][0-9A-Z_a-z-]*`

**Comment by bzbarsky** [comment]
> CSSOM spec describes about identifiers with leading dashs

No, it does not.  That's why that leading '_' is there.

**Comment by bzbarsky** [comment]
Or put another way, what CSSOM specs is that if you have a CSS property named "-foo-bar" you would create this webidl:

    [CEReactions] attribute [TreatNullAs=EmptyString] CSSOMString _-foo-bar;

which is perfectly valid webidl syntax and leads to an identifier with the value "-foo-bar", per this bit in <https://heycam.github.io/webidl/#idl-names>:

> For all of these constructs, the identifier is the value of the identifier token with any leading U+005F LOW LINE ("_") character (underscore) removed.

**Comment by csnardi** [comment]
But the regex for identifiers is:

```
/_?[A-Za-z][0-9A-Z_a-z-]*/
```

and `_-foo-bar` wouldn't be matched by that regex.

**Comment by peria** [comment]
I got it. I misunderstood the description of CSSOM spec.

It says, we have to convert names between CSS property name and IDL attribute identifier.
So if we want to handle a CSS property `-webkit-transform`, we need to define a corresponding IDL attribute `webkitTransform`. And algorithms of conversion are [CSS property to IDL attribute](https://drafts.csswg.org/cssom/#css-property-to-idl-attribute) and [IDL attribute to CSS property](https://drafts.csswg.org/cssom/#idl-attribute-to-css-property).

Thus I think CSSOM does not mismatch with current Web IDL spec. So let me close this issue.

@csnardi I agree `_-foo-bar` isn't matched by the regex.

**Comment by bzbarsky** [comment]
No, @csnardi is right.  The CSSOM spec for something like `-webkit-transform` says we should have both a `webkitTransform` property and a `-webkit-transform` property.  I had missed that we disallow `_-...`, so we do have a problem here.

@heycam do you recall why the grammar disallows leading '-' in identifiers?  Was that basically to match other IDLs, C, etc, where it would introduce ambiguities with negation?  That doesn't seem like a problem webidl should have, since we don't really do negation of named things syntax-wise...

**Comment by bzbarsky** [comment]
Fwiw, the regexp Gecko's IDL parser uses for identifiers is:

    [A-Z_a-z][0-9A-Z_a-z-]*

which does match `_-foo-bar`.  It looks like when we fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1048437 the change to the IDL spec didn't match the change we made to our parser...

**Comment by peria** [comment]
Ah, I got it. It follows the rule for _dashed attribute_. Thank you for pointing it.

**Comment by peria** [comment]
friendly ping.
Can we discuss how we should update the regular expression?  i.e. Is this issue accepted?
I think the reasonable regex is `_?[A-Za-z-][0-9A-Z_a-z-]*`.
A concern for this expression is that it can accept identifiers with no alphabets, like `--`, `_-`, `_-_`, `-012-345_678`.
