### ISSUE TITLE
Can [Replaceable] be used on namespace members?

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#572]
https://heycam.github.io/webidl/#Replaceable

It isn't explicitly disallowed to use [Replaceable] on namespace members, but it's definition mentions [platform object](https://heycam.github.io/webidl/#dfn-platform-object) which only a non-callback interface has.

The definition of https://heycam.github.io/webidl/#dfn-attribute-setter looks like it'd work, but if it's intended to work then the earlier description should probably not mention platform objects.

**Comment by foolip** [comment]
Hmm, https://heycam.github.io/webidl/#dfn-attribute-setter also says "given an attribute *attribute*, an **interface** *target*", which makes sense given that namespace members "are the regular operations and read only regular attributes", so attribute members on namespaces will never have setters. Seems like [Replaceable] just doesn't make any sense then.

**Comment by bzbarsky** [comment]
Hmm.  So namespaces only allow readonly attributes.  But `[Replaceable]` could in theory still make sense.

That said, in practice it doesn't make sense to me; `[Replaceable]` is basically a backwards-compat hack, and there's no need for that on namespaces....

There is definitely a  spec bug here, though.  https://heycam.github.io/webidl/#define-the-attributes can have a namespace as _definition_ and in step 3 does https://heycam.github.io/webidl/#dfn-attribute-setter with that namespace as _target_ if that happens, but https://heycam.github.io/webidl/#dfn-attribute-setter assumes that _target_ is not a namespace.  We need to fix that.  Probably by just having step 1 of https://heycam.github.io/webidl/#dfn-attribute-setter return **undefined** if _target_ is a namespace.
