### ISSUE TITLE
Should "perform some steps once a promise is settled" use %PromiseProto_then%?

### ISSUE THREAD

**Issue by Ms2ger** [heycam/webidl#583]
https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled

The current spec has

> 1. Let *then* be ? GetMethod(*promise*, "then").

which seems to imply that weird things may happen if you mess with a promise object or the prototype. That seems non-obvious and not particularly useful.

**Comment by bzbarsky** [comment]
Paging @domenic

**Comment by littledan** [comment]
Note, the change here would be analogous to the change in https://github.com/tc39/ecma262/pull/1250 .
