### ISSUE TITLE
Is it true that dictionaries can't have a default value specified?

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#585]
There's informative text in https://heycam.github.io/webidl/#idl-operations that says:

> Dictionary types cannot have a default value specified explicitly

however it seems to me that `null` would be a valid default value for a dictionary (meaning empty dictionary, once you go through the es-to-dictionary steps).

@tobie @domenic @marcoscaceres @annevk

**Comment by annevk** [comment]
I think we decided not to have a default value (e.g., `{}`) since it always has a default value.

**Comment by bzbarsky** [comment]
For example, `DOMQuadInit` at https://drafts.fxtf.org/geometry/#dictdef-domquadinit sure seems to assume that its `DOMPointInit` members get default values.  It has no provisions for those members being missing.

@zcorpan

**Comment by zcorpan** [comment]
Good catch. Yeah, I think I assumed that they would act like `{}`. 

The other option is to default with prose in the algorithm, though that seems less nice.
