### ISSUE TITLE
What about i64?

### ISSUE THREAD

**Issue by lorenzleutgeb** [heycam/webidl#586]
I am writing JavaScript code that interfaces with WebAssembly. The WebAssembly memory is exposed as an `ArrayBuffer` which I wrap in a `Uint8Array` and a `DataView` for access.

WebAssembly values are typed as `i32`, `i64`, `f32`, `f64`. Three of them are nicely mirrored in WebIDL. However, `i64` is missing the `Int64Array`, `Uint64Array` and `DataView.setInt64`, `DataView.setUint64` counterparts.

I tried to find out why they are not standardized, but was not successful. In my opinion that would be a reasonable addition.

I see that JavaScript's `Number.MAX_SAFE_INTEGER` is less than 2^64, is that the "reason"?

**Comment by bzbarsky** [comment]
> However, i64 is missing the Int64Array, Uint64Array and DataView.setInt64, DataView.setUint64 counterparts

This isn't really directly related to Web IDL.   Those object types and methods are missing from the ES spec, and WebIDL just refers to the ES spec for typed array bits.

> I see that JavaScript's Number.MAX_SAFE_INTEGER is less than 2^64, is that the "reason"?

For the features not being in ES, I believe that is correct.  In any case, this is a question for TC39, not Web IDL.

**Comment by bzbarsky** [comment]
And in particular, Web IDL does have 64-bit integer types (`long long` and `unsigned long long`) that APIs defined via Web IDL can use.  But `DataView` and typed arrays are not defined via Web IDL.

**Comment by lorenzleutgeb** [comment]
OK, sorry then, I did not know whether TC39 depends on Web IDL or the other way round.
