### ISSUE TITLE
Check Grammar bison format?

### ISSUE THREAD

**Issue by AlexMouton** [heycam/webidl#591]
https://github.com/heycam/webidl/blob/c2f8e96836ce6fa1638320240002162ab013f658/check-grammar.js#L12

Hi @tobie
Digging this up from the vaults but wondering.  This seems to produce rules with one colon on the first line of the rule, and one leading the second line.  The bison format seems to expect only one.
I get this result with this version,  adding a colon to the first regex term and the second test predicate:

function processRules(rules) {
    const REGEXP = /(\s*::\n\s*)|\b(integer|float|identifier|string|whitespace|comment|other)\b|(\s*\n\s*)|(ε)/g;
    return rules.map(rule => {
        return rule.trim().replace(REGEXP, m => {
            if (/^(integer|float|identifier|string|whitespace|comment|other)$/.test(m)) {
              return m.toUpperCase();
            }
            if (/::\n/.test(m)) { return "\n  : "; }
            if (/\n/.test(m)) { return "\n  | "; }
            if (/ε/.test(m)) { return "/* epsilon */"; }
        }) + "\n  ;";
    });
}

HTH!
Alex

**Comment by tobie** [comment]
Yeah, the only idea here was to mach the EcmaScript style. It’s totally possible to do something else instead.

**Comment by AlexMouton** [comment]
Thanks. Can you give me a link to this EcmaScript style?
I havn't been able to find it.

**Comment by tobie** [comment]
So looking at the [ES spec](https://tc39.github.io/ecma262/#sec-syntactic-and-lexical-grammars) more closely, it turns out that `::` is reserved for the RegExp grammar and `:::` for the Numeric Grammar, so WebIDL should really use a single colon instead.

**Comment by jmdyck** [comment]
> `::` is reserved for the RegExp grammar

and the lexical grammar.

**Comment by littledan** [comment]
Note, many people seem to get confused by the colon count thing in the JS spec (including long-time TC39 participants); I don't think this is a very intuitive convention that we should be exporting to the world.
