### ISSUE TITLE
Is step 4 of the effective overload set construction unnecessary?

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [heycam/webidl#600]
Can you clarify the difference between N, max, and maxarg from step 4 in the algorithm for the [effective overload set](https://heycam.github.io/webidl/#dfn-effective-overload-set). 

It seems like N is something that describes one of the entries in F: the number of arguments.  I think line 4 is meant to determine the max arguments for any element in F, but that also seems to be what step 3 has calculated as maxarg.  So can step 4 just be omitted?

From the spec:
>3. Let maxarg be the maximum number of arguments the operations, constructor extended attributes or callback functions in F are declared to take. For variadic operations and constructor extended attributes, the argument on which the ellipsis appears counts as a single argument.
>
>4. Let max be max(maxarg, N).

**Comment by bzbarsky** [comment]
_maxarg_ is the maximum number of arguments declared across all of the overloads; it describes something about the entries in _F_.  _N_ is the number of arguments that were actually passed for the particular function invocation being considered; it describes the way the function is being called.  See how the effective overload set algorithm is invoked in https://heycam.github.io/webidl/#dfn-create-operation-function step 2.1.4.

So as an example, if your IDL has:

    void foo(long x);
    void foo(long x, long y, long z, long w);

then _maxarg_ is `4`.  If you do `foo(1, 2)` then _max_ will be `2`.  If you do `foo(1, 2, 3, 4, 5)` then _max_ will be `4`.

Step 4 is determining a cap on the number of arguments we can actually work with; this can be smaller than _maxarg_ if fewer than _maxarg_ arguments were passed.

**Comment by bzbarsky** [comment]
> So in your examples I think you get a max of 4 and 5, not 2 and 4.

Er, yes.  That is correct.  Sorry, it's been a while and this stuff is not as simple as I wish it were.

> Additionally, I don't think there's a reason to restrict the entries of S by N when computing the effective overloads

It's not restricting.  As you note, it's a `max`, not a `min`, so it's expanding `S`.  And the reason it's expanding is because of variadic arguments.  That's the only place _max_ is used: to handle variadic arguments.

**Comment by bzbarsky** [comment]
So specifically, this is to handle IDL like:

    void foo(int... arg);

when called as `foo(1, 2)`.  In this case, _N_ is 2, _maxarg_ is 1.  But we do in fact want `S` to end up containing a signature with two arguments, because we want to pass both arguments to the underlying implementation.

**Comment by BoCupp-Microsoft** [comment]
I see how it fits together now.  Thanks for the quick responses.
