### ISSUE TITLE
Consider requiring optional dictionary defaulting explicitly

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#602]
Instead of
```webidl
foo(optional dictionaryType arg);
```
perhaps we should require writing
```webidl
foo(optional dictionaryType arg = {});
```
for consistency with other optional arguments and for clarity for the reader. At least anecdotally this seems to be one of the most confusing things about IDL that's not a legacy feature.

**Comment by bzbarsky** [comment]
Or `optional dictionaryType arg = null`, though either one is probably ok... We just need to introduce new syntax to do `= {}`, last I checked, while `= null` should just work.

**Comment by annevk** [comment]
I suspect that `= null` might have the same problem and could even lead to prose that branches on `null`.

**Comment by bzbarsky** [comment]
OK.  As long as people are clear on `= {}` meaning "empty dictionary", not "dictionary initialized from a `{}` JS object literal", since those are not the same thing...

**Comment by bzbarsky** [comment]
@annevk One question: would we still require the `= {}` on trailing (or all?) dictionary args to be present for the IDL to be valid?  That seems generally desirable to me...

**Comment by annevk** [comment]
Yeah, I was thinking it would be a syntax error without it. I suspect we should require it always, to make it clear it's what happens when you pass undefined and you cannot branch on "_dict_ not given" or some such.
