### ISSUE TITLE
CheckIterable(V) is not defined in ECMAScript 2015

### ISSUE THREAD

**Issue by travisleithead** [heycam/webidl#61]
So, this leaves [at least] the conversion from an ECMAScript value V to a sequence<T> undefined--not sure exactly what CheckIterable() was supposed to do.

My main question: are array-like objects supported (e.g., NodeLists, or Objects with a length and indexed properties), or must they only have a Symbol.iterator? (Or some other thing.)

http://heycam.github.io/webidl/#es-sequence

I checked with Brian Terlson, and he wasn't sure what CheckIterable() was supposed to do either.

**Comment by bzbarsky** [comment]
CheckIterable got refactored into GetMethod with P === Symbol.iterator, I believe.

> My main question: are array-like objects supported (e.g., NodeLists, or Objects with a length and indexed properties), or must they only have a Symbol.iterator?

The latter, but node that `NodeList` has a `Symbol.iterator`.
