### ISSUE TITLE
Better regular expression for identifiers

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#632]
See https://github.com/heycam/webidl/pull/612#pullrequestreview-197260832. Perhaps we need something that disallows `--`, but still meets the other criteria.

(This seems fairly minor since I'd expect those writing standards to keep to relatively good practice.)

**Comment by saschanaz** [comment]
What was reason not to choose `[_-]?[A-Za-z][0-9A-Z_a-z-]*`?

**Comment by peria** [comment]
I agree with @saschanaz . We need to discuss which is better before merging the patch.
Obviously, `_?[A-Za-z-][0-9A-Z_a-z-]*` allows `_-` and `--`, while `[_-]?[A-Za-z][0-9A-Z_a-z-]*` doesn't.

**Comment by annevk** [comment]
This was proposed in https://github.com/heycam/webidl/issues/564#issuecomment-402591724 and nobody suggested a different take, so I'm not sure. Is there a reason to prefer that one? So CSS doesn't need `_` all over I guess?

**Comment by peria** [comment]
As I said in the comment, that regexp has a concern to accept strange strings as identifiers. From this point of view, "`[_-]?[A-Za-z][0-9A-Z_a-z-]*`" is better, and now I prefer this.

In addition, leading `_` has an important roll in WebIDL spec.

>  the identifier is the value of the identifier token with any leading U+005F LOW LINE ("_") character (underscore) removed.

> If one of these keywords is used, it need not be escaped with a leading underscore.

So if we accept "`__`", should it be treated as "`_`"?

**Comment by saschanaz** [comment]
>So if we accept "__", should it be treated as "_"?

The answer is probably yes, but I think that would be meaningless because [currently identifiers cannot start with `_`](https://heycam.github.io/webidl/#idl-names):
   >The identifier of any of the abovementioned IDL constructs must not be "constructor", "toString", or begin with a U+005F LOW LINE ("_") character. These are known as reserved identifiers.

**Comment by saschanaz** [comment]
Looks like this can be closed now.

**Comment by annevk** [comment]
Fixed by 81dc0403a56e8b3a66eaab869704d635b39c0fe2.
