### ISSUE TITLE
Rename Date to LegacyDateDoNotUse, or at least add a big warning

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#66]
Per https://groups.google.com/forum/#!topic/mozilla.dev.platform/TiE00xh6Ihg and https://github.com/w3c/webrtc-pc/issues/324. We can update HTML's valueAsDate easily enough.

**Comment by ylafon** [comment]
Date was removed per https://github.com/heycam/webidl/pull/69
So this one should be closed.
