### ISSUE TITLE
Should callback interfaces with more than one operation be supported?

### ISSUE THREAD

**Issue by Ms2ger** [heycam/webidl#661]
Looking at Gecko, there's `EventListener`, `NodeFilter` and `XPathNSResolver`, all with one operation; `ObserverCallback`, also with one operation, but shouldn't even exist (<https://bugzilla.mozilla.org/show_bug.cgi?id=1530702>); and `MozIdleObserver`, which isn't exposed to script. WebKit doesn't seem to have any others either.

There's already a note that suggests using dictionaries instead of callback interfaces, so I think we should bite the bullet and mark the entire thing as legacy, and reduce the spec to only support what's actually used.

**Comment by annevk** [comment]
See also #100 for some additional context.

**Comment by Ms2ger** [comment]
We should probably also remove support for attributes, and the "get a user object's attribute value" and "set a user object's attribute value" algorithms.

**Comment by domenic** [comment]
> the "get a user object's attribute value" and "set a user object's attribute value" algorithms.

Those are generally useful, not just for callback interfaces. Although perhaps people aren't using them, instead preferring to declare dictionary types and convert, or use ES's Get() directly, or similar.

**Comment by Ms2ger** [comment]
The algorithms explicitly only work "given a callback interface type value object", so at the very least, we'd need to clarify that.
