### ISSUE TITLE
Everything is a module

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#676]
#675 reminded me of an idea by @lukewagner that everything should be a module, somehow, so it'd be easier to use from WebAssembly. If that came to pass we'd probably need more granular `[SecureContext]` and `[Exposed]` annotations.

It might also make sens that inside a module we'd use `[AvailableIn]` rather than `[Exposed]` so that the latter can be reserved for truly exposing something on a global, whereas `[AvailableIn]` (bikeshedding welcome) would indicate where it's functional. E.g.,
```webidl
[AvailableIn=Window]
module dom {
  [Exposed=Window]
  interface Node { ... };

  ...
};
```

**Comment by littledan** [comment]
One interesting thing about this is that it would make it easy to access the original `Node` constructor, modulo import maps. Going further in this direction, some people have suggested that everything from a built-in module be deeply immutable, so you'd be able to access the original version of everything in a reliable way (c.f., @domenic 's [get-originals](https://github.com/domenic/get-originals/ proposal which also works in this space and [previous TC39 discussion on frozen modules](https://github.com/tc39/proposal-javascript-standard-library/issues/15)). #675 doesn't do this, though; I'm a bit skeptical on the frozen modules idea. cc @mattijs

**Comment by annevk** [comment]
Closing per https://github.com/heycam/webidl/pull/675#issuecomment-561702200.
