### ISSUE TITLE
Is [AllowShared] an applicable-to-types attribute?

### ISSUE THREAD

**Issue by peria** [heycam/webidl#687]
The section of [annotated types](https://heycam.github.io/webidl/#idl-annotated-types) has an explicit list of applicable-to-types, as `[Clamp]`,` [EnforceRange]`, and `[TreatNullAs]`.

Beside it, in the section of [`[AllowShared]`](https://heycam.github.io/webidl/#AllowShared), it says

> If the [AllowShared] extended attribute appears on one of the buffer source types, it creates a new IDL type 

it seems to say [AllowShared] is an applicable-to-types.  Is it correct? And do we need the explicit list of applicable-to-type ones?

**Comment by annevk** [comment]
The link "annotated types" in OP should probably go to https://heycam.github.io/webidl/#idl-annotated-types. In case, I think you've found an error and `[AllowShared]` should be in that list.

**Comment by peria** [comment]
Oops. Yes. I fixed the link.

If the list of applicable to types has [AllowShared], it answers my questions,
But I still wonder if it needs the explict list.

**Comment by annevk** [comment]
I haven't really done a deep dive, but it seems you need this list for step 4 and 5 of https://heycam.github.io/webidl/#idl-type-extended-attribute-associated-with as well as the requirement directly after this algorithm. Do see a way to address that in some other way?

**Comment by peria** [comment]
IMO, it's enough if the section of each applicable-to-types extended attribute mentions that the attribute is applicable to types.
Unless any specific attribute is required in the algorith description, we don't need a whitelist.
