### ISSUE TITLE
Define serialization and deserialization steps for DOMException

### ISSUE THREAD

**Issue by yutakahirano** [heycam/webidl#729]
See https://github.com/whatwg/html/issues/4268 for context.

cc: @domenic

**Comment by yutakahirano** [comment]
@domenic, I filed this issue here because DOMException is [defined here](https://heycam.github.io/webidl/#idl-DOMException). Is here the right place to define the [de]serialization steps? I'm asking because "Serializable" extended attribute is [defined in HTML](https://html.spec.whatwg.org/multipage/structured-data.html#serializable-objects).

**Comment by annevk** [comment]
Yeah, this would be the correct place.

**Comment by yutakahirano** [comment]
Thanks!

**Comment by Ms2ger** [comment]
I'm not sure I agree; it would add another dependency from IDL to HTML that I'd prefer to avoid. Alternatively, we could consider moving the whole section to IDL – based on a quick skip, it doesn't appear to depend on anything defined in HTML.

**Comment by domenic** [comment]
I don't think avoiding dependencies from IDL to HTML overall is worthwhile. There may be some sections where that could be valuable, e.g. the base binding layers that might be used by WebAssembly eventually, but having DOMException's serialization behavior depend on HTML seems fine. I also don't think that shuffling text between documents to preserve some notion of directional dependence is a good use of time.

**Comment by yutakahirano** [comment]
Thank you. I created a minimal change (i.e., using HTML terms from WebIDL) as #732.
