### ISSUE TITLE
IDL/dfn of terms with underscores not autolinking as expected.

### ISSUE THREAD

**Issue by inexorabletash** [heycam/webidl#734]
When needing to use underscores to escape IDL keywords, the docs seemingly indicate this should work:

```xml
<xmp class=idl>
interface Foo {
  void _bar(any x);
};
</xmp>

The <dfn method for=Foo>bar(|x|)</dfn> method...
```

... but [I'm seeing](https://w3c.github.io/IndexedDB/#keyrange) the IDL fragment define a `#dom-foo-_bar id` rather than autolinking to the `#dom-idbkeyrange-includes` id defined by the prose.

**Comment by TimothyGu** [comment]
Did you mean to instead file a ticket at https://github.com/tabatkins/bikeshed/issues/?

**Comment by inexorabletash** [comment]
Ugh, sorry, too many windows.
