### ISSUE TITLE
Looking for some clarity on Promise<void>

### ISSUE THREAD

**Issue by bathos** [heycam/webidl#737]
In the [description of void](https://heycam.github.io/webidl/#es-void), it’s stated that

> The only place that the void type may appear in IDL is as the return type of an operation.

However when describing the ES binding rules for Promise types, in the algorithm [perform some steps once a promise is settled](https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled), it says:

> If T [of `Promise<T>`] is void, then [...]

Is `Promise<void>` is permitted, but only as a return type? If so, should the first text be amended to clarify that, or am I misunderstanding what ‘return type’ is inclusive of?

**Comment by TimothyGu** [comment]
The first piece of text seems to predate the introduction of <code>Promise&lt;<var>T</var>&gt;</code>. Technically `void` may indeed only appear in return types (as defined by the [_ReturnType_](https://heycam.github.io/webidl/#prod-ReturnType) production), but the _T_ in <code>Promise&lt;<var>T</var>&gt;</code> also matches _ReturnType_ per the grammar.

So yes, `Promise<void>` is permitted, not only as a return type of an operation but also of an attribute. (For example, a [`document.ready`](https://github.com/whatwg/html/issues/127) promise would probably be a `Promise<void>` if spec'd.) The first sentence should indeed be updated to account for promises. It should probably also be updated to account for things like callback function's return type, considering callback functions are not operations _per se_.

**Comment by bathos** [comment]
Thanks! Makes sense. I think I was reading ‘as the return type’ without realizing that it was referring to the `ReturnType` production, and yes, ‘of an operation’ seems incorrect even without Promise in the mix.

**Comment by annevk** [comment]
I suspect we'd not want `Promise<void>` for an attribute that's not readonly.

And yeah, callbacks definitely need to be able to return `void`.

**Comment by bzbarsky** [comment]
Honestly, there aren't any use cases I've seen so far for a Promise-typed writable attribute at all.  

I just checked and there aren't any such attributes in Gecko's IDL, at least.

**Comment by Ms2ger** [comment]
That's good, because the spec already says:

> Attributes whose type is a promise type must be read only.

since #217.

**Comment by bzbarsky** [comment]
Aha!  Turns out, Gecko's IDL parser enforces that too, so no wonder there are no writable promise attributes there.  ;)
