### ISSUE TITLE
NonAnyType vs SingleType as home of PromiseType ε alternative

### ISSUE THREAD

**Issue by bathos** [heycam/webidl#740]
- The `NonAnyType` production is only used within [`UnionMemberType`][1] and [`SingleType`][2].
- `NonAnyType` [includes the alternative `PromiseType ε`][3].
- A Union type comprises [‘two or more other types’][4].
- Promise types are [not distinguishable from any other type][5].
- [Each pair of flattened member types in a union type, T and U, must be distinguishable.][6]

I may be missing or misunderstanding something (perhaps in the last item?), but it seems like, if all of the above statements are true, that a Promise type is never a valid union member. If that’s true, then the `PromiseType ε` alternative should probably be moved from `NonAnyType` to `SingleType` so that this constraint gets enforced syntactically.

[1]: https://heycam.github.io/webidl/#prod-UnionMemberType
[2]: https://heycam.github.io/webidl/#index-prod-SingleType
[3]: https://heycam.github.io/webidl/#prod-NonAnyType
[4]: https://heycam.github.io/webidl/#dfn-union-type
[5]: https://heycam.github.io/webidl/#example-distinguishability-promises
[6]: https://heycam.github.io/webidl/#ref-for-dfn-flattened-union-member-types%E2%91%A8

**Comment by Ms2ger** [comment]
https://heycam.github.io/webidl/#es-union also doesn't handle promises at all, so I think your conclusion is correct. I imagine we'd welcome a PR to implement your suggestion, but let's wait a few days in case people have other thoughts.

**Comment by annevk** [comment]
Yeah, everything can get coerced to a promise, so if you want overloading it needs to be on the type the promise takes. If the grammar does not line up with that making it so would be good I think.

**Comment by bzbarsky** [comment]
My gut feeling is that we should rename `NonAnyType` to `MaybeDistinguishableType` or `DistinguishableType` or something like that to make it clear what it's really about, and move the `Promise` bit into `SingleType`, as @bathos proposes.

(In addition to being theoretically fine, I just tried making that change in Gecko, and it's fine in practice too, as far as any of our tests are concerned.)

**Comment by bzbarsky** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1562008
