### ISSUE TITLE
ReadWriteMapLike/ReadWriteSetLike in ReadOnlyMemberRest

### ISSUE THREAD

**Issue by bathos** [heycam/webidl#752]
The productions `ReadWriteMaplike` and `ReadWriteSetlike` effectively alias `MaplikeRest` and `SetlikeRest`. Usually when this is done it’s to associate evaluation rules (or just human meaning) with a subset of occurences. But `MaplikeRest` and `SetlikeRest` aren’t used elsewhere, so there’s no unique subset to speak of. I suspect there was _supposed_ to be though. I think this:

```
ReadOnlyMemberRest ::
    AttributeRest
    ReadWriteMaplike
    ReadWriteSetlike
ReadWriteMaplike ::
    MaplikeRest
ReadWriteSetlike ::
    SetlikeRest
```

Should probably be this:

```
ReadOnlyMemberRest ::
    AttributeRest
    MaplikeRest
    SetlikeRest
ReadWriteMaplike ::
    MaplikeRest
ReadWriteSetlike ::
    SetlikeRest
```

(Happy to open PRs as I come across stuff like this, but I’m not yet confident re: whether I’m just missing stuff, hence opening issues to sanity check my impressions first.)

**Comment by Ms2ger** [comment]
I think that change makes sense, yes.
