### ISSUE TITLE
Built-in module conventions

### ISSUE THREAD

**Issue by Ms2ger** [heycam/webidl#755]
There's been a number of discussions around conventions for built-in modules, in particular:

* Enumerability of methods/accessors (see also #719)
* Same-realm brand checks (see also #718)
* Freezing

Let's figure out what we want, and involve TC39 in the discussion as well, potentially at the 23-25 July 2019 F2F meeting.

CC @domenic @annevk @bzbarsky

**Comment by domenic** [comment]
For the record: in [KV Storage](https://wicg.github.io/kv-storage/#storagearea-iteration), I've so far adopted same-realm brand checks (easy to loosen later), but not enumerability of methods/accessors or freezing.

**Comment by ljharb** [comment]
Are web platform built-in globals made enumerable for intentional reasons, or to be consistent with legacy choices? If the former, what are the reasons?

**Comment by domenic** [comment]
My impression is legacy choices, but the decision predates me. @bzbarsky or @heycam are our best bets here, perhaps?

**Comment by bzbarsky** [comment]
I believe they were enumerable in all browsers when the Web IDL spec was written, and the spec just reflected that.

**Comment by ljharb** [comment]
In that case (re enumerability) it seems like a clean break opportunity for the web to start mirroring the language, and go non-enumerable?
