### ISSUE TITLE
Can this be moved into the w3c github account

### ISSUE THREAD

**Issue by wheresrhys** [heycam/webidl#760]
This project is quite useful, but it's not entirely obvious that it is authoritative because it lives in a personal github account. Is there any reason it can't be moved into https://github.com/w3c?

**Comment by EdgarChen** [comment]
We are in the process of moving into WHATWG.

**Comment by TimothyGu** [comment]
See https://www.w3.org/2021/06/WHATWG-W3C-MOU_2021_update.html and https://github.com/w3c/whatwg-coord/issues/3

**Comment by ExE-Boss** [comment]
This has now been moved to @whatwg, see:
- <https://github.com/whatwg/webidl/issues/1016>
