### ISSUE TITLE
[SecureContext] handling for mixins seems to be slightly broken

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#762]
https://heycam.github.io/webidl/#SecureContext says:

> The [SecureContext] extended attribute must not be specified both on an interface, mixin, or namespace member, and on the partial interface, partial interface mixin, or partial namespace definition the member is declared on.

and

> The [SecureContext] extended attribute must not be specified on both an interface member and the interface or partial interface definition the interface member is declared on. It must also not be specified on both a namespace member and the namespace or partial namespace definition the namespace member is declared on.

So it disallows duplicated `[SecureContext]` for members in partial interfaces _twice_ (once in each of those quotes), same thing for partial namespaces.  It disallows it for interfaces and namespaces in the second quote and partial mixins in the first quote, but never disallows it for non-partial mixins, as far as I can tell.

Seems to me that we should just have a single thing disallowing the duplication on both a member and its containing construct no matter what that containing construct is.

**Comment by annevk** [comment]
So given interfaces `[SecureContext] A` and (insecure) `B`, and mixin `[SecureContext] C`. I think both A and B should be able to include C. A partial interface that has `[SecureContext]` should probably not work for A, but should work for B. And then members should indeed not duplicate the container (but duplicating the container's container should be fine for mixins and probably not for partial interfaces).

**Comment by bzbarsky** [comment]
> So given interfaces [SecureContext] A and (insecure) B, and mixin [SecureContext] C. I think both A and B should be able to include C. 

Sure, this already works in the spec.

> A partial interface that has [SecureContext] should probably not work for A

Apart from being redundant, why not?  I guess redundancy is the same reason we disallow duplication between members and their containers...
