### ISSUE TITLE
Should `includes` be allowed as operation names?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#767]
`includes` has been a reserved keyword since we introduced mixins, but IndexedDB is using that word for an operation: https://github.com/w3c/IndexedDB/commit/98b28b9890eb92b36eaadbedb31cea2d3bcd64aa

```webidl
[Exposed=(Window,Worker)]
interface IDBKeyRange {
  // -- snip --

  boolean _includes(any key);
};
```

@bzbarsky raised a concern that we shouldn't force escaping here. What do you think?

**Comment by bzbarsky** [comment]
We should generally not make backwards-incompatible changes unless we're forced to.  So yes. ideally we would keep allowing "includes" as an identifier-like thing in all the cases that are unambiguous.

**Comment by inexorabletash** [comment]
It'd let me remove a note from the spec explaining that `_includes` is just the IDL, not the actual method name. So 👍 as a spec author, not sure how much work updating the blink implementation would be.

Would want WPT and Bikeshed updates too.
