### ISSUE TITLE
Should `async` be allowed as an attribute name?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#768]
```webidl
[Exposed=Window,
 HTMLConstructor]
interface HTMLScriptElement : HTMLElement {
  // -- snip --
  [CEReactions] attribute boolean async;
  [CEReactions] attribute boolean defer;
  // -- snip --
};
```

The attribute [`async`](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:dom-script-async) now has an invalid syntax after #720. Should it be just escaped with `_async` or should we add `async` to `AttributeName`?

cc @Ms2ger @bzbarsky

**Comment by bzbarsky** [comment]
The latter, imo.
