### ISSUE TITLE
Should nullable optional dictionary argument have a default value?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#774]
The [Media Session spec](https://w3c.github.io/mediasession/) has the following IDL:

```webidl
dictionary MediaPositionState {
  double duration;
  double playbackRate;
  double position;
};

[Exposed=Window]
interface MediaSession {
  // -- snip --
  void setPositionState(optional MediaPositionState? state);
};
```

Currently the prose says:

> If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional and have a default value provided.

Per my understanding the spec requires a default value for optional nullable dictionaries, but is it intended?

**Comment by annevk** [comment]
Why is this dictionary made nullable? (It's not clear to me we should allow that at all.)

**Comment by saschanaz** [comment]
AFAIK somehow an author decided to do that without any real benefit, per my reading.

**Comment by annevk** [comment]
Filed https://github.com/w3c/mediasession/issues/231. Perhaps we should look into forbidding this? At least when there's no required members? And even then it seems like a poor pattern, but I vaguely recall it being too late for nested dictionaries...

**Comment by Ms2ger** [comment]
I don't think the prose you quote actually requires a default here (it's not a dictionary type or a union type), but agree that the API doesn't make sense as specced.

**Comment by annevk** [comment]
Thanks, then we can close this I think as there's already a downstream issue.

**Comment by saschanaz** [comment]
👍 Thanks for the details!

**Comment by saschanaz** [comment]
Note that I found this when I run my webidl2.js validator (which currently incorrectly suggests adding a default value for an invalid nullable dictionary argument) against WPT, maybe we can still catch this type of problems there.
