### ISSUE TITLE
Update the ecosystem to constructor operations

### ISSUE THREAD

**Issue by Ms2ger** [heycam/webidl#778]
See #636, #700.

Tools
=====
* [x] [webidl2.js](https://github.com/w3c/webidl2.js) - https://github.com/w3c/webidl2.js/pull/300
* [x] [idlharness.js](https://github.com/w3c/respec) - https://github.com/web-platform-tests/wpt/pull/18722
* [x] [widlparser](https://github.com/plinss/widlparser) - https://github.com/plinss/widlparser/issues/44
* [ ] [bikeshed](https://github.com/tabatkins/bikeshed) - https://github.com/tabatkins/bikeshed/issues/1513
* [ ] [respec](https://github.com/w3c/respec)

Specs
=====
- [x] dom - https://dom.spec.whatwg.org/
  - AbortController
  - Comment
  - CustomEvent
  - DocumentFragment
  - Document
  - EventTarget
  - Event
  - MutationObserver
  - Range
  - Text
  - XPathEvaluator
- [x] webaudio - https://webaudio.github.io/web-audio-api/
  - AnalyserNode
  - AudioBufferSourceNode
  - AudioBuffer
  - AudioContext
  - AudioWorkletGlobalScope
  - AudioWorkletNode
  - AudioWorkletProcessor
  - BiquadFilterNode
  - ChannelMergerNode
  - ChannelSplitterNode
  - ConstantSourceNode
  - ConvolverNode
  - DelayNode
  - DynamicsCompressorNode
  - GainNode
  - IIRFilterNode
  - MediaElementAudioSourceNode
  - MediaStreamAudioDestinationNode
  - MediaStreamAudioSourceNode
  - MediaStreamTrackAudioSourceNode
  - OfflineAudioCompletionEvent
  - OfflineAudioContext
  - OscillatorNode
  - PannerNode
  - PeriodicWave
  - StereoPannerNode
  - WaveShaperNode
- [ ] css
  - css-animations - https://drafts.csswg.org/css-animations-1/
    - AnimationEvent
  - web-animations - https://drafts.csswg.org/web-animations/
    - AnimationPlaybackEvent
    - Animation
    - DocumentTimeline
    - KeyframeEffect
  - css-font-loading - https://drafts.csswg.org/css-font-loading
    - FontFaceSetLoadEvent
    - FontFaceSet
    - FontFace
  - cssom-view - https://drafts.csswg.org/cssom-view
    - MediaQueryListEvent
  - CSS Transitions - https://drafts.csswg.org/css-transitions-1/
    - TransitionEvent
  -  Resize Observer - https://drafts.csswg.org/resize-observer/
    - ResizeObserver
- [ ] MediaStream Recording - https://w3c.github.io/mediacapture-record/
  - BlobEvent
  - MediaRecorderErrorEvent
  - MediaRecorder
- [ ] FileAPI - https://w3c.github.io/FileAPI/
  - Blob
  - FileReaderSync
  - FileReader
  - File
- [ ] HTML
  - BroadcastChannel
  - CanvasRenderingContext2D
  - CloseEvent
  - DataTransfer
  - DragEvent
  - ErrorEvent
  - EventSource
  - HashChangeEvent
  - ImageData
  - MessageChannel
  - MessageEvent
  - OffscreenCanvas
  - PageTransitionEvent
  - PopStateEvent
  - PromiseRejectionEvent
  - SharedWorker
  - StorageEvent
  - TrackEvent
  - WebSocket
  - Worker
- [ ] Clipboard API and events - https://w3c.github.io/clipboard-apis/
  - ClipboardEvent
- [ ] UIEvents - https://w3c.github.io/uievents
  - CompositionEvent
  - FocusEvent
  - InputEvent
  - KeyboardEvent
  - MouseEvent
  - UIEvent
  - WheelEvent
- [ ] Ambient Light Sensor - https://w3c.github.io/ambient-light/
  - AmbientLightSensor
- [ ] DeviceOrientation Event - https://w3c.github.io/deviceorientation/
  - DeviceMotionEvent
  - DeviceOrientationEvent
- [ ] WebIDL - https://heycam.github.io/webidl/
  - DOMException
- [ ] fxtf
  - geometry
    - DOMMatrixReadOnly
    - DOMMatrix
    - DOMPointReadOnly
    - DOMPoint
    - DOMQuadReadOnly
    - DOMQuad
    - DOMRectReadOnly
    - DOMRect
- [ ] DOM Parsing and Serialization - https://w3c.github.io/DOM-Parsing/
  - DOMParser
  - XMLSerializer
- [ ] Service workers - https://w3c.github.io/ServiceWorker/
  - ExtendableEvent
  - ExtendableMessageEvent
  - FetchEvent
- [ ] XHR - https://xhr.spec.whatwg.org/
  - FormData
  - ProgressEvent
  - XMLHttpRequest
- [ ] Gamepad - https://w3c.github.io/gamepad/
  - GamepadEvent
- [ ] Fetch - https://fetch.spec.whatwg.org/
  - Headers
  - Request
  - Response
- [ ] IDB - https://w3c.github.io/IndexedDB/
  - IDBVersionChangeEvent
- [ ] MediaStream Image Capture
  - ImageCapture
- [ ] Intersection Observer - https://w3c.github.io/IntersectionObserver
  - IntersectionObserver
- [ ] Encrypted Media Extensions - https://w3c.github.io/encrypted-media
  - MediaEncryptedEvent
  - MediaKeyMessageEvent
- [ ] Media Source Extensions - https://w3c.github.io/media-source/
  - MediaSource
- [ ] Media Capture and Streams - https://w3c.github.io/mediacapture-main/getusermedia.html
  - MediaStream
- [ ] Payment Request API - https://w3c.github.io/payment-request
  - MerchantValidationEvent
  - PaymentMethodChangeEvent
  - PaymentRequestUpdateEvent
  - PaymentRequest
- [ ] Web MIDI API - https://webaudio.github.io/web-midi-api/
  - MIDIConnectionEvent
  - MIDIMessageEvent
- [ ] Notifications API - https://notifications.spec.whatwg.org/
  - NotificationEvent
  - Notification
- [ ] Performance Timeline - https://w3c.github.io/performance-timeline/
  - PerformanceObserver
- [ ] Pointer Events - https://w3c.github.io/pointerevents/
  - PointerEvent
- [ ] Presentation API - https://w3c.github.io/presentation-api/
  - PresentationConnectionAvailableEvent
  - PresentationConnectionCloseEvent
  - PresentationRequest
- [ ] Push API - https://w3c.github.io/push-api/
  - PushEvent
- [ ] Reporting API - https://w3c.github.io/reporting/
  - ReportingObserver
- [ ] WebRTC - https://w3c.github.io/webrtc-pc/
  - RTCDataChannelEvent
  - RTCDTMFToneChangeEvent
  - RTCIceCandidate
  - RTCPeerConnectionIceEvent
  - RTCPeerConnection
  - RTCSessionDescription
  - RTCTrackEvent
- [ ] Content Security Policy - https://w3c.github.io/webappsec-csp
  - SecurityPolicyViolationEvent
- [ ] Web Speech API - https://w3c.github.io/speech-api
  - SpeechGrammarList
  - SpeechRecognitionErrorEvent
  - SpeechRecognitionEvent
  - SpeechRecognition
  - SpeechSynthesisErrorEvent
  - SpeechSynthesisEvent
  - SpeechSynthesisUtterance
  - SpeechSynthesisUtterance
- [ ] Encoding - https://encoding.spec.whatwg.org/
  - TextDecoder
  - TextEncoder
- [ ] Touch Events - https://w3c.github.io/touch-events
  - TouchEvent
  - Touch
- [ ] URL - https://url.spec.whatwg.org/
  - URLSearchParams
  - URL
- [ ] WebVTT - https://w3c.github.io/webvtt/
  - VTTCue
  - VTTRegion
- [ ] WebGL
  - WebGLContextEvent

**Comment by bzbarsky** [comment]
@ms2ger Are there browser issues filed for this already?

**Comment by Ms2ger** [comment]
Not yet; I'll do that on Monday.

**Comment by bzbarsky** [comment]
@ms2ger filed some browser bugs:

* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1578173
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=201397

I don't see a Blink issue, but not sure whether that's because I'm just not finding it in their bug tracker.

**Comment by foolip** [comment]
Filed https://github.com/tabatkins/bikeshed/issues/1519 about another Bikeshed issue that needs to be resolved before rolling this out to lots of specs.

**Comment by marcoscaceres** [comment]
Just reflecting on the last few weeks...  I think in the future, we should  make sure ReSpec, BikeShed, WebIDL2.js, and Peter's IDL parser are first updated/fully tested before exported definitions are yanked out of the WebIDL spec and we file spec bugs. 

The last few weeks saw a lot of significant breakage across the ecosystem, leaving Editors confused about error messages they couldn't fix. It meant a lot of us having to shift work/weekend priorities to deal with the fallout. Also, some folks were on vacation, etc. so things couldn't be fixed in a timely manner. 

The above is not a rebuke or criticism as we are still learning how to best deal with these kinds of changes - but something to keep in mind in the future to make these kinds of changes easier to manage for all of us.

**Comment by domenic** [comment]
I've spot-checked ~10 specs on this list and they are all updated. Let's close this out.
