### ISSUE TITLE
"Perform some steps once a promise is settled" awkward to use in return value form

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#783]
What prose do we expect spec authors to write to replace the "transforming" from the promises guide? The best I've got is

> Return the result of [=upon settling|performing the following steps=] once _p_ is settled, with the fullfilment handler which takes an argument |x|:

This seems kind of terrible. What could work better? Should we reintroduce "transforming"?

Related problem: the algorithm name is "perform some steps once a promise is settled", but you cannot link to it by that name, because it has `lt="upon settling"`. All usage sites use "upon settling".

**Comment by jakearchibald** [comment]
Just ran into this, and I think it may have led to a broken example https://github.com/heycam/webidl/issues/788.

Suggestions:

Let |promise| be the result of [=transforming promise=] |promise|:

Let |promise| be the result of [=continuing promise=] |promise|:

Let |promise| be the result of [=reacting to promise=] |promise|:

ECMA seems to refer to the fulfill/reject callbacks as "reactions".

**Comment by jakearchibald** [comment]
"Reacting" works even if you don't use the return value:

[=React to promise=] |promise|:

Or

Let |promise| be the result of [=reacting to promise=] |promise|:

The substeps would remain the same as https://heycam.github.io/webidl/#ref-for-dfn-perform-steps-once-promise-is-settled%E2%91%A1.

**Comment by domenic** [comment]
I like react(ing). Since this is blocking several specs I'll do a quick PR myself.
