### ISSUE TITLE
"Upon settling" example incorrect

### ISSUE THREAD

**Issue by jakearchibald** [heycam/webidl#788]
https://heycam.github.io/webidl/#ref-for-dfn-perform-steps-once-promise-is-settled%E2%91%A1

This example tries to resolve/reject a promise that's already settled. I guess it's supposed to resolve |p| rather than |promise|.

I think this error indicates the example is perhaps convoluted? "Upon settling" returns a new promise like `promise.then(onFulfilled, onRejected)`. If the example takes advantage of this, it wouldn't need two similarly-named promises in the same scope.

**Comment by Ms2ger** [comment]
The example can't take advantage of that, because the resolve/reject run in parallel. I guess that actually means they should queue tasks.

**Comment by jakearchibald** [comment]
Fair point. I guess each branch of the promise reaction could create & return a new promise. That'd be closer to how `promise.then` works, but I don't know if it's necessary here.
