### ISSUE TITLE
What is ArgumentNameKeyword for?

### ISSUE THREAD

**Issue by peria** [heycam/webidl#799]
Reading #700, #779, and whatwg/html#4869, I wonder why we need a list of keyword to allow them to be used in arguments name.

Even without it, we can use any reserved words as identifiers if we attach a leading "_" (https://heycam.github.io/webidl/#idl-names), and _ArgumentName_ accepts identifiers in grammar.
Do we have any reason to allow these (limited) reserved words to be used in arguments' names without "_", though we can also use other words in practice?

**Comment by bzbarsky** [comment]
The purpose is twofold: ergonomics and not invalidating existing IDL.  Yes, we could force people to scatter `_` (what I assume was meant above but got munged by githubs markdown parser) about, but most IDL authors don't even know about that feature and it looks ugly.   And when new keywords get added, it's best if existing argument name uses don't become invalid and have to be modified to include `_`.
