### ISSUE TITLE
Make the length property for interfaces that support indexed properties mandatory

### ISSUE THREAD

**Issue by nox** [heycam/webidl#80]
Currently, interfaces that support indexed properties only make the length property mandatory if they are iterable. The length property is also mentioned as a sufficient condition for the interface to have an `@@iterator` symbol.

It should probably be made crystal-clear that interfaces that support indexed properties should always have a length attribute.

**Comment by heycam** [comment]
Yeah, we may as well. All interfaces that use indexed properties in the platform should have a length IDL attribute already.

**Comment by bzbarsky** [comment]
@tobie Is there a corresponding idlharness issue?

**Comment by tobie** [comment]
It now does: https://github.com/w3c/testharness.js/issues/234
