### ISSUE TITLE
Is the longer form of stringifier operations a thing?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#816]
Can't find any example of `stringifier DOMString customIdentifier();`, is there any known use?

**Comment by bathos** [comment]
On Mozilla Central all that comes up is a [test](https://dxr.mozilla.org/mozilla-central/search?q=regexp%3A%22stringifier%5Cs%2BDOMString%5Cs%2B%5Cw%2B%5C(%22+ext%3Awebidl).

**Comment by annevk** [comment]
I tried GitHub's blame UI but got stuck rather quickly when everything got converted to Bikeshed. GitHub Unicorns and "file too big" before that.

I think there are potential uses for `stringifier TYPE ();`, in particular if the specification wants to return a byte sequence and have that turned into a string (i.e., `ByteString`, although that's not how that's defined right now) or give some kind of assertion that the return value is UTF-8-safe which can be helpful for tooling (i.e., `USVString`).

The `customIdentifier` bit seems somewhat bogus as new APIs should follow the pattern that results in a `toString()` on the object and therefore never use that.

**Comment by bathos** [comment]
Currently, neither ByteString or USVString seem to be permitted:

> Stringifiers declared with operations must be declared to take zero arguments and return a DOMString.

([link](https://heycam.github.io/webidl/#idl-stringifiers#ref-for-idl-DOMString%E2%91%A2))

**Comment by annevk** [comment]
Interesting, that seems a little bogus, but in that case removing this seems fine and the differently-typed version can be added when there's a need.

**Comment by bzbarsky** [comment]
Yeah, I'd lean toward removing the operation version, since nothing uses it at the moment.  We can add it if/when someone has a use case.
