### ISSUE TITLE
All supported property names should be enumerable or none of them

### ISSUE THREAD

**Issue by nox** [heycam/webidl#82]
Currently in the platform, the only interface with [unenumerable](http://heycam.github.io/webidl/#dfn-unenumerable) property names is [NamedNodeMap](https://dom.spec.whatwg.org/#dom-htmlcollection-item). In that interface, they are *all* unenumerable.

WebIDL should reflect that and forbid mixing unenumerable and enumerable property names.

**Comment by annevk** [comment]
I think you might be correct that this is an all-or-nothing affair, but `NamedNodeMap` is not the sole class. HTML has a number of them too.

**Comment by nox** [comment]
https://html.spec.whatwg.org/#the-htmlallcollection-interface:unenumerable
https://html.spec.whatwg.org/#the-htmlformcontrolscollection-interface:unenumerable
https://html.spec.whatwg.org/#the-htmloptionscollection-interface:unenumerable
https://html.spec.whatwg.org/#the-form-element:unenumerable
https://html.spec.whatwg.org/#named-access-on-the-window-object:unenumerable
https://html.spec.whatwg.org/#plugins-2:unenumerable
https://html.spec.whatwg.org/#plugins-2:unenumerable-2

At this point, I feel like we really should just make an `[UnenumerableNamedProperties]` extended attribute on such interfaces.

**Comment by annevk** [comment]
Bikeshed: `[LegacyUnenumerable]` since this should not happen again.

**Comment by bzbarsky** [comment]
I guess we could add something for this case, but is it really worth the effort?  If no one is supposed to ever use this again, then new specs will simply not say anything is unenumerable and existing specs can just stay as-is.

Note that named properties in general are something I think should not happen again, of course.

**Comment by annevk** [comment]
Yeah, perhaps we should start by renaming `getter` to `legacygetter`.

**Comment by nox** [comment]
Using an extended attribute let us piggy back the existing infrastructure in WebIDL parsers and idlharness.js. Prose doesn't.

**Comment by bzbarsky** [comment]
Piggy back in what sense?   What work gets saved and for whom?

**Comment by nox** [comment]
@bzbarsky Maybe that's just my limited knowledge of idlharness.js, but I don't know how to share a test between multiple interfaces in an easy way there. Just testing the unenumerability of named properties of interfaces with `[LegacyUnenumerable]` sounds more straightforward to me.

I just realised while writing this that it doesn't need to be in the spec to be tested this way, but it still sounds nicer to me to formalise the meaning of that attribute here.

**Comment by bzbarsky** [comment]
Ah, I see.  Sure, adding an extended attribute for that use makes sense.

**Comment by domenic** [comment]
I don't think we should be adding things to specs to work around deficiencies in testing frameworks... am I misunderstanding?

**Comment by bzbarsky** [comment]
Well, I think if we'd had this extended attribute all along browsers might have used it too.  It's just that right now browsers already have code to handle this per the prose... though they could perhaps get rid of that code or auto-generate it given the extended attribute if they wanted to.

**Comment by annevk** [comment]
I'd basically see it as a refactoring of legacy code. Rather than eight more or less duplicate paragraphs of prose, define it once in IDL. Not high priority, but not wrong either.

**Comment by domenic** [comment]
OK, makes sense; thanks for reassuring me.
