### ISSUE TITLE
Check if NodeFilter.length is defined correctly.

### ISSUE THREAD

**Issue by Ms2ger** [heycam/webidl#83]
Seems to be 0 in Gecko/Chrome, not sure if the spec backs that.

**Comment by bzbarsky** [comment]
The spec seems to only define a "length" property for non-callback interfaces, implying that there is no such property on the `NodeFilter` object.  So doing `NodeFilter.length` will return `Function.prototype.length`, which is 0.

That said, `NodeFilter.hasOwnProperty("length")` actually returns true in both Gecko and Blink.

**Comment by Ms2ger** [comment]
I'm not sure where `Function.prototype.length` comes from, given

> Remember that interface objects for callback interfaces only exist if they have constants declared on them; when they do exist, they are not function objects.

**Comment by bzbarsky** [comment]
Oh.  Well, `NodeFilter.__proto__ == Function.prototype` is `true` in both Gecko and Blink.  Yes, that's not what IDL says right now.  It's not clear to me why IDL says what it does and which should change.

**Comment by nox** [comment]
@bzbarsky That condition is false in Safari.

**Comment by nox** [comment]
Mentioning #78 because NodeFilter is the only legacy callback interface we have.

**Comment by bzbarsky** [comment]
@nox What is it in IE?  Seems to me like we should do the simplest thing that requires the fewest UAs to change.

**Comment by nox** [comment]
@bzbarsky No idea, I don't have any Windows box. :(

**Comment by domenic** [comment]
`NodeFilter.__proto__ === Function.prototype` in latest Edge.

**Comment by ArkadiuszMichalski** [comment]
Hmm, more results for:
```
<script>
	console.log(NodeFilter.__proto__ == Function.prototype);
	console.log(typeof NodeFilter);
	console.log(NodeFilter.length);
	console.log(NodeFilter.hasOwnProperty("length"));
</script>
```
IE11: `false, object, undefined, false`
Opera 12.x: `true, function, 0, false`
Firefox and Chrome: `true, function, 0, true`

**Comment by arronei** [comment]
Edge: true, function, 0, false (length is a known Edge bug and should be true)
