### ISSUE TITLE
Set `[[IsClassConstructor]]` for interfaces without overriden constructor steps

### ISSUE THREAD

**Issue by ExE-Boss** [heycam/webidl#831]
The&nbsp;`[[IsClassConstructor]]` internal&nbsp;slot is&nbsp;set&nbsp;to&nbsp;`true` for&nbsp;function&nbsp;objects created&nbsp;with the&nbsp;**ES6**&nbsp;`class`&nbsp;keyword.

In&nbsp;interfaces&nbsp;without overriden&nbsp;constructor&nbsp;steps, step&nbsp;1&nbsp;ensures that&nbsp;this&nbsp;interface was&nbsp;declared with&nbsp;a&nbsp;`constructor`&nbsp;operation and&nbsp;step&nbsp;2&nbsp;ensures that&nbsp;`NewTarget` is&nbsp;not&nbsp;`undefined`.

The&nbsp;`[[IsClassConstructor]]` Function&nbsp;internal&nbsp;slot takes&nbsp;care&nbsp;of&nbsp;step&nbsp;2 by&nbsp;throwing a&nbsp;`TypeError` at&nbsp;the&nbsp;beginning of&nbsp;the&nbsp;`[[Call]]` internal&nbsp;operation, which&nbsp;is&nbsp;faster, as&nbsp;the&nbsp;`[[Call]]`&nbsp;algorithm only&nbsp;needs&nbsp;to&nbsp;check a&nbsp;boolean&nbsp;internal&nbsp;slot, instead&nbsp;of&nbsp;needing&nbsp;to&nbsp;prepare and&nbsp;push&nbsp;the&nbsp;constructor&nbsp;implementation to&nbsp;the&nbsp;execution&nbsp;context&nbsp;stack.

---

This&nbsp;also&nbsp;means that&nbsp;**WebIDL2JS** isn’t&nbsp;quite&nbsp;spec&nbsp;compliant, as&nbsp;it&nbsp;has&nbsp;<code>[[IsClassConstructor]]&nbsp;===&nbsp;true</code>, whereas&nbsp;native&nbsp;implementations have&nbsp;it&nbsp;currently&nbsp;set&nbsp;to&nbsp;`false`.

**Comment by domenic** [comment]
Can you re-state this in terms of observable, testable things?

**Comment by ExE-Boss** [comment]
Well, [there’s&nbsp;the&nbsp;`isCallable`&nbsp;proposal](https://github.com/caitp/TC39-Proposals/blob/master/tc39-reflect-isconstructor-iscallable.md), which&nbsp;intends to&nbsp;return&nbsp;`false` for&nbsp;class&nbsp;constructors.

This&nbsp;also&nbsp;affects @ljharb’s&nbsp;[is‑callable](https://github.com/inspect-js/is-callable)&nbsp;package, which&nbsp;returns&nbsp;`true` for&nbsp;native&nbsp;implementations, but&nbsp;returns&nbsp;`false` for&nbsp;**WebIDL2JS**&nbsp;implementations.

---

See&nbsp;also: https://github.com/tc39/proposal-function-implementation-hiding/issues/43

**Comment by ljharb** [comment]
I'm a bit confused how this applies here; `is-callable` relies on toString output (since there's no other non-Proxy way to distinguish constructors). What's the effect *not counting* is-callable, and what exactly are you suggesting to fix it? (perhaps you already said this, but it's not clear to me)

**Comment by TimothyGu** [comment]
There seems to be no observable effect of this. The ES spec [says](https://tc39.es/ecma262/#sec-built-in-function-objects):

> If a built-in constructor has any [[Call]] behaviour other than throwing a **TypeError** exception, an ECMAScript implementation of the function must be done in a manner that does not cause the function's [[IsClassConstructor]] internal slot to have the value **true**.

but doesn't say anything about constructors whose sole [[Call]] behavior is to throw a **TypeError**, which I suppose could have [[IsClassConstructor]] either be **true** or **false**. Web IDL inherits this sentence as interface objects are also built-in functions.

I recommend this issue be closed. Issues with any particular implementation of Web IDL, including webidl2js, should be filed at the respective location.
