### ISSUE TITLE
Consider adding a `[CrossOriginIsolated]` extended attribute.

### ISSUE THREAD

**Issue by mikewest** [heycam/webidl#875]
We have a [`[SecureContext]`](https://heycam.github.io/webidl/#SecureContext) extended attribute that governs whether or not a given construct is exposed within a given context. I'd suggest that something similar would be helpful as we begin restricting access to APIs based on whether or not a given context is cross-origin isolated. 

The [Securer Contexts](https://github.com/mikewest/securer-contexts) proposal talks about this attribute in terms of `[SecureContext=Isolated]`, but I now think it's probably a better idea to create a new attribute (`[CrossOriginIsolated]`) for this purpose, as it would give us the opportunity to reformulate `[SecureContext]` in the future to something more specifically related to the aspect of security it actually governs.

That is, for upcoming APIs like [`performance.measureMemory()`](https://github.com/WICG/performance-measure-memory), I'd like them to be able to define the API as limited to isolated and secure contexts in a standardized way. Perhaps along the lines of:

```
partial interface Performance {
  [SecureContext, CrossOriginIsolated] Promise<MemoryMeasurements> measureMemory();
}
```

That would have the effect of exposing the method only when the context is cross-origin isolated via COOP and COEP (as defined in https://github.com/whatwg/html/issues/4732#issuecomment-570223375).

WDYT?

@annevk @camillelamy @domenic

**Comment by annevk** [comment]
Is https://github.com/whatwg/html/issues/5435 still something that is being pursued by Google? (It would be doable in Firefox, but I'm not sure we want to lead with shipping that as well.)

Note that if you have `[CrossOriginIsolated]` there should be no need to list `[SecureContext]`. It's effectively a subset.

**Comment by mikewest** [comment]
> Is whatwg/html#5435 still something that is being pursued by Google?

I think so? Either @arturjanc or @ulan pinged me about it earlier this week, and it seems like a reasonable thing to do that this would layer on top of.

> Note that if you have `[CrossOriginIsolated]` there should be no need to list `[SecureContext]`. It's effectively a subset.

If we keep `[SecureContext]`, I think I'd suggest that folks list both for clarity.

(As part of Securer Contexts, I'd secretly like to deprecate `[SecureContext]` by making it the default, and annotating all unrestricted APIs with `[UnsafelyExposedToNetworkAttackers]` or something similar... but that's a bit off topic for this particular issue).

**Comment by ExE-Boss** [comment]
Make sure to include [the `Legacy` prefix](https://heycam.github.io/webidl/#es-legacy-extended-attributes), eg.: `[LegacyUnsafelyExposedToNetworkAttackers]` or `[LegacyInsecureContext]`, if the former is deemed too long for something that would be listed on many, <em>many</em>¹ APIs.

---

1. I don’t have an exact figure, but I’d expect that at least ⅔ of all Web APIs don’t currently have `[SecureContext]`.

**Comment by mikewest** [comment]
My hope is that we'd mostly be putting the attribute on interfaces rather than literally every attribute or method. I filed https://github.com/heycam/webidl/issues/876, which is probably a better place for that conversation. :)
