### ISSUE TITLE
Add datetime, timedelta?

### ISSUE THREAD

**Issue by guettli** [heycam/webidl#886]
I had a look at the list of types: https://heycam.github.io/webidl/#idl-types

Why is there no support for datetime and timedelta types?

**Comment by TimothyGu** [comment]
Because it doesn't need to be in Web IDl proper, as it can be defined on top of existing Web IDL types. For instance, the [`DOMHighResTimeStamp`](https://w3c.github.io/hr-time/#sec-domhighrestimestamp) type in the W3C High Resolution Time spec is defined as a `double`.

**Comment by annevk** [comment]
Closing per @TimothyGu's comment. Feel free to reply if anything is unclear still.
