### ISSUE TITLE
What does [Exposed] mean on [LegacyNoInterfaceObject] interfaces?

### ISSUE THREAD

**Issue by saschanaz** [heycam/webidl#919]
Currently the spec allows `[Exposed]` and `[LegacyNoInterfaceObject]` coexist [with Example 74](https://heycam.github.io/webidl/#LegacyNoInterfaceObject), while `[Exposed]` is optional in such case.

What does it mean to have both, though?

**Comment by annevk** [comment]
The way I see `[Exposed]` is as a list of globals/realm that can have instances of the object "present in them". And the other is really about whether the global object has a property pointing toward the constructor.

**Comment by saschanaz** [comment]
Makes sense, but then does `[LegacyNoInterfaceObject]` alone implicitly mean `[Exposed=Everywhere]`?

**Comment by annevk** [comment]
I strongly suspect it appearing alone to be an error. I thought we required Exposed. If we don't, we should.

**Comment by saschanaz** [comment]
We don't, #423 somehow allowed omitting it.

https://github.com/heycam/webidl/blob/6bccbcaf3a22c658e342fb032ebac7cc24c7836f/index.bs#L1019-L1021
