### ISSUE TITLE
[upon fulfillment, upon rejection] reword

### ISSUE THREAD

**Issue by croraf** [heycam/webidl#923]
In **upon fulfillment** https://heycam.github.io/webidl/#upon-fulfillment this part seems incorrect and confusing: 
![image](https://user-images.githubusercontent.com/19698636/93589233-d0250680-f9ac-11ea-898f-bc68684fee0e.png)

When the `promise` is fulfilled with the value `v` the `onFulfilled` gets called with `v`. This is not the same as "performing _steps_ with `v`". `onFulfilled` is produced using all the steps in 1. and 2. of https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled

I guess the intention of **upon fulfillment** was:

> 1. **React** to _promise_ providing _steps_ as the steps to be run when the promise is fulfilled.

So I think it should be changed into that.

------------------

NOTE 1: If this is correct, and when doing this change, the question which pops up is "is **upon fulfillment** needed at all or is it more clear and concise to always call **react** directly".

NOTE 2: Same discussion applies to **upon rejection**

**Comment by domenic** [comment]
The two phrases you provide are equivalent (in the English language sense).

**Comment by croraf** [comment]
Which two phrases exactly?

**Comment by domenic** [comment]
The screenshot and the blockquote.

**Comment by croraf** [comment]
I don't think so. Objective semantic difference is explained in the paragraph between. 

And also subjectively, I think the blockquote version is easier to understand (less ambiguous).

**Comment by domenic** [comment]
There is no objective difference, because they are equivalent English phrases. You seem to be interpreting "was fulfilled" to mean `onFulfilled`, but we didn't say `onFulfilled`, we said "was fulfilled", i.e. we gave the steps to run when the promise was fulfilled.

**Comment by croraf** [comment]
The screenshot literally says: "If promise was fulfilled **with value `v`**, then". That can only mean that `onFulfilled` is called with `v`. I can see no other interpretation.

**Comment by domenic** [comment]
I'm sorry that you can't see the correct interpretation. `onFulfilled` is very different from "was fulfilled". "was fulfilled" denotes the steps that happen when something is fulfilled, which is what the "react" algorithm expects.

I'll close this as I'm not sure how we'll be able to make much further progress, but it's possible others might be able to help you understand the difference between the variable `onFulfilled` and the English phrase "was fulfilled" or its equivalent "steps that happen when the promise is fulfilled".

**Comment by croraf** [comment]
You seem to be missing a comma. If it said:

"If _promise_ was fulfilled, then" 

that would be much different than what it currently says: 

"If _promise_ was fulfilled with `v`, then (and then using the result of fulfillment `v` on steps which have no direct access to this argument)"
