### ISSUE TITLE
Define DOMException.prototype.toString() (as this.name + ": " + this.message)

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#93]
I can't find `toString` in http://heycam.github.io/webidl/#es-DOMException-prototype-object but it's supported by Blink, Gecko and WebKit as `this.name + ": " + this.message`. IE11 appears to stringify as either the name or the message, I can't tell because they're the case I tested.

**Comment by bzbarsky** [comment]
In Gecko, `DOMException.prototype.hasOwnProperty("toString")` is false.  However, Gecko implements this sentence from the spec you link to:

> The DOMException prototype object MUST have an internal [[Prototype]] property whose value is %ErrorPrototype% ([ECMA-262], section 6.1.7.4).

and if you look at http://www.ecma-international.org/ecma-262/6.0/#sec-error.prototype.tostring you will see that it does precisely the `this.name + ": " + this.message` with some complications if name or message undefined.

So this seems to be perfectly well defined already, and implemented as written by Gecko... what am I missing?

**Comment by foolip** [comment]
Oh, it's on `Error.prototype.toString( )`, sorry I didn't think to look there. It looks like Chromium actually has that as well, so that `DOMException.prototype.toString` is just a redundant override. I'll look into removing it.
