### ISSUE TITLE
Should namespace objects have "length" and "name" own properties?

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#949]
I can't find anything in https://heycam.github.io/webidl/#namespace-object to suggest that a namespace object should have `length` or `name` properties, but looking at namespace objects in implementations the results are mixed:
- `CSS.length` is 0 and `CSS.name` is "CSS" in Chrome, Firefox and Safari
- `console.length` is 0 and `console.name` is "console" in Firefox, but both are undefined in Chrome and Safari
- `WebAssembly.length` and `WebAssembly.name` are undefined in Chrome, Firefox and Safari

I don't think this has caused any problems, but it could be a future nuisance making it harder to introduce a new namespace which has a `name` member. (Wanting a `length` member seems less likely.)

With confirmation that these shouldn't be there, I could add negative tests for it.

**Comment by domenic** [comment]
They should not. This is due to incorrect implementations of them as functions instead of namespace objects. You could also test that typeof x === "object" (not "function").

**Comment by TimothyGu** [comment]
It appears to be a bit more nuanced. On Chrome 88, `CSS.length` and `CSS.name` are both undefined, contrary to @foolip's findings. OTOH `typeof CSS` is `"object"` on both Chrome and Firefox here, though it's `"function"` on WebKit.

**Comment by foolip** [comment]
I was testing in Chrome 87. In Chrome Canary, I see that `CSS.length` and `CSS.name` are indeed both undefined. And `typeof CSS` has changed from "function" to "object". This was a recent fix, perhaps in https://chromium-review.googlesource.com/c/chromium/src/+/2463092. @yuki3 was that an intentional effect of that CL?

Regardless, sounds like we should have tests for each of the namespace objects to ensure they're objects, not functions. Checking that they don't have `length` and `name` is then a bit redundant, but maybe we should.

**Comment by foolip** [comment]
Turns out idlharness.js tests this. In https://wpt.fyi/results/css/cssom/idlharness.html?label=experimental&label=master&aligned, the 'CSS namespace: typeof is "object"' test fails in Safari. I'll file bugs.

**Comment by foolip** [comment]
OK, I've filed https://bugs.webkit.org/show_bug.cgi?id=220855.

**Comment by yuki3** [comment]
Yes, the change was intentional.  https://chromium-review.googlesource.com/c/chromium/src/+/2434404 is the patch to make CSS an IDL namespace.

**Comment by saschanaz** [comment]
I think Gecko does have a bug here, filed https://bugzilla.mozilla.org/show_bug.cgi?id=1688335

**Comment by foolip** [comment]
Thanks for confirming @yuki3, I didn't think to check if `CSS` was recently changes to a namespace and just assumed it was a bug with namespace objects generally.

And thanks @saschanaz for filing that Gecko bug, I forgot about `console` when I closed the issue.
