### ISSUE TITLE
Need an error for "User refused permission"

### ISSUE THREAD

**Issue by alvestrand** [heycam/webidl#95]
In #85, a new "not allowed" error was added. The description says:

"The request is not allowed by the user agent or the platform in the current context."

This does not include the user refusing permission.
We (WEBRTC) have been using SecurityError for this, and were considering switching to this one, (https://github.com/w3c/mediacapture-main/issues/317) - but the description doesn't allow it to be used for users' refusal to allow.

Should we either add an UserRefusedPermission error, or change the description of this one?

**Comment by beverloo** [comment]
The Push API defines a `PermissionDeniedError` that'd we also like to use in background sync. Could we perhaps adopt that one in WebIDL?

https://w3c.github.io/push-api/#dfn-permissiondeniederror

/cc @nicolassatragno @jkarlin

**Comment by tobie** [comment]
Note BackgroundSync [defines it](https://wicg.github.io/BackgroundSync/spec/#permissiondeniederror) too.

**Comment by jan-ivar** [comment]
The user agent is an agent of the user, is that not sufficient? If a web page could know for certain that the user is the obstacle, then it could pester the user.

**Comment by Ms2ger** [comment]
I think you're reading the description in an overly narrow way. Using `NotAllowedError` seems perfectly fine to me.

**Comment by tobie** [comment]
Yes. Given how many editors are rolling their own `PermissionDeniedError`, paving the cow-path might be the right thing to do, though.

**Comment by alvestrand** [comment]
I'd prefer to fix this problem by improving the description. Having more error codes that mean almost the same thing is bad for the platform.
The reason for my original formulation is that 1) I don't know what the WebIDL authors intended about users, and 2) I don't want to dictate which way they choose to fix this. The important thing is that it gets fixed.

**Comment by mounirlamouri** [comment]
Using `NotAllowedError` sgtm. We might want to update the description if it is considered not good enough.

**Comment by binarykitchen** [comment]
hello guys, i just landed here from a google search and would like to know where i can look up what the error message "The request is not allowed by the user agent or the platform in the current context." really means.

for my www.videomail.io app i am trying to rephrase it so that it becomes more human friendly to read.

**Comment by tobie** [comment]
@binarykitchen: that's going to be context dependant. But probably something to do with the user refusing to give permission to access an API.

**Comment by binarykitchen** [comment]
@tobie thanks - if this is w3c specified, can i know the link?

i really need to know, not "probably" :) this because traffic is high on that site and such an unclear error message can impact usability ...

**Comment by tobie** [comment]
@binarykitchen it's the [`NotAllowedError`](https://heycam.github.io/webidl/#notallowederror). It's used in multiple specs. It's generally related to users refusing to give permission to use a particular API. Think you want to look for APIs that require user permission and see where you're not catching errors (rejected promises?) properly.

**Comment by tobie** [comment]
Here's where it's used in Mozilla src code: http://searchfox.org/mozilla-central/search?q=notallowederror.

**Comment by binarykitchen** [comment]
@tobie i've been investigating. there have been Error objects with the name `PERMISSION_DENIED` in the past. do they mean the same?

**Comment by tobie** [comment]
They were specific to geolocation.

**Comment by binarykitchen** [comment]
geolocation? huh, i cannot follow ...

**Comment by tobie** [comment]
See: https://dev.w3.org/geo/api/spec-source.html#position_error_interface

**Comment by binarykitchen** [comment]
ah, weird, that's something totally different. alright, i ll ignore that for now then. thanks for the links @tobie
