### ISSUE TITLE
Add [[PlatformBrand]] internal slot to all platform objects

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#97]
The [[PlatformBrand]] internal slot would be a List (in the ECMAScript sense) of strings. One string per interface on the interface chain of the object. So e.g., Text would have "Text, "CharacterData", "Node", "EventTarget".

This would allow us to be more specific what we mean with instances of something and would also clear up a lot of language in IDL I think.

**Comment by dominiccooney** [comment]
Is the [[PlatfromBrand]] on the instance (for example a text node in the DOM, not the Text interface or Text interface prototype object?)

For what it is worth Blink implements the check for HTMLElement in custom elements as if the brand is on the instance; see [CustomElementDefinition::checkConstructorResult](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/custom/CustomElementDefinition.cpp?sq=package:chromium&dr=CSs&rcl=1472642334&l=76). Sorry for the C++, but basically it checks the element instance is a HTMLElement; it doesn't consult JavaScript prototypes or anything.

**Comment by annevk** [comment]
Yes, on the instance. All internal slots are I think.

**Comment by annevk** [comment]
(Once we add this StructuredSerialize can be simplified a little bit as all platform objects will have this slot and therefore can be treated like promises or WeakMap objects.)

**Comment by annevk** [comment]
The other thing that would be useful here is some shorthands around it. When you check against the list of platform brands, there's a difference if the matched  value is first in the list or somewhere else (or last and somewhere else, depending on order).

E.g., in DOM we sometimes want to match DocumentFragment, but not ShadowRoot (a subclass).

**Comment by littledan** [comment]
It sounds like we'd have two "entrypoints" to `[[PlatformBrand]]`:
- In WebIDL, when evaluating the phrase, "is a platform object that implements"
- In all the other specs, when they use the phrase, "a new XYZ object"

Is that what you were picturing, @annevk? The first one will be pretty easy to update, but the second would be a lot of work to go around fixing up. Would it be reasonable to add a "create a new platform object of interface |interface|" algorithm to WebIDL and update all the other specs to call into that?
