### ISSUE TITLE
Bug (sort of)

### ISSUE THREAD

**Issue by halindrome** [heycam/webidl#98]
On the W3C web site, https://w3.org/TR/WEBIDL/ does not resolve to this spec.  Rather it points to a much older Candidate Recommendation.  Please update that short name to redirect to this short name.

**Comment by domenic** [comment]
In general anything with /TR/ in the URL should not be trusted ("TR stands for trash" is the colloquialism). I believe there are organization-wide efforts underway to fix that, and maybe this issue will help spur along this particular case, but it's worth remembering that rule for the forseeable future.

https://platform.html5.org/ is a pretty good source that tends to link to the latest URLs in all cases; the few cases that are TR there have been actively vetted to make sure there are no superceding specs.

**Comment by halindrome** [comment]
I was basically reporting this error with my W3C AC hat on.  The W3C short names should work all the time, regardless of whether they are perceived as "trash" in the community.  But thanks for the pointer.

**Comment by tobie** [comment]
So this is something to see with the W3C systeam and/or webmaster. The short answer is they're willing to re-direct the ED (which they already did), but not modify a published document.

Closing on this side.
