### ISSUE TITLE
Add a PermissionDeniedError

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#99]
[Push-API defines](https://w3c.github.io/push-api/#dfn-permissiondeniederror) a `PermissionDeniedError`  as: _The operation failed because the user denied permission to use the API._

I'd need to use something similar for the Generic Sensor API. Think you could add it to the Spec?

**Comment by marcoscaceres** [comment]
Wondering why NotAllowedError is insufficient? Is there a use context where it would be ambiguous?

**Comment by tobie** [comment]
@marcoscaceres: @Ms2ger just suggested the same over irc.If that's the case, then maybe a note should be added to the spec.

**Comment by tobie** [comment]
Note BackgroundSync [defines it](https://wicg.github.io/BackgroundSync/spec/#permissiondeniederror) too.

**Comment by tobie** [comment]
Closing as dupe of #95.
